### ISSUE TITLE
Android App moved to SD card does not start up

### ISSUE THREAD

**Issue by espinielli** [bitwarden/mobile#1018]
## Describe the Bug
Android App moved to SD card instead of Internal storage does not start up. 

## Steps To Reproduce

1. Install Bitwarden from Google Play Store
1. Open the Bitwarden App: all is ok. So installation was successful. 
2. Open Android phone Settings -> Apps - > Bitwarden 
3. Click on Storage -> Change
4. Select 'SD card' (it was previously 'Internal storage') 
5. Press 'Move' 
6. Open Bitwarden App: it flickers and do not start up 

## Expected Result
Bitwarden App should work even if moved to 'SD card' storage

## Actual Result
Bitwarden App moved to SD card does not work / start up. 

### Phone
- Device: Huawei P8 
- Operating system: EMUI 4.0.3 (Android 6.0) 
- Build Version: GRA-L09C432B520
- Kernel Version: 3.10.86-g9d4e5d5
### App
- Version: 2.5.0 (3093)
- Is this a Beta release? N

**Comment by mportune-bw** [comment]
Due to inherent limitations with running on external storage we don't support it.

@cscharf We don't specify the `installLocation` in the manifest, which normally means the system should default to `internalOnly`.  However I'm not sure if EMUI respects that flag so we may need to be explicit about it by adding `android:installLocation="internalOnly"` within `application` in the Android manifest.

Additional details:  https://developer.android.com/guide/topics/data/install-location
