### ISSUE TITLE
http URL was saved when adding a new login

### ISSUE THREAD

**Issue by yegle** [bitwarden/mobile#1021]
## Describe the Bug

When adding a new login from Android Chrome, a http:// URL was saved instead of https:// URL.

## Steps To Reproduce

1. In Chrome Android incognito tab, open a login form (e.g. https://github.com/login), confirm you are accessing using HTTPS.
2. When prompt "Autofill with Bitwarden", go to my vault.
3. Add a new login.

## Expected Result

The url `https://github.com/login` should be in the URL field.

## Actual Result

The url `http://github.com/login` is used in the URL field.

## Environment

- Device: Google Pixel 4 XL
- Operating system: Android 11 Beta 2
- Build Version (go to "Settings" → "About" in the app): 2.5.0 (3093)
- Is this a Beta release? N

**Comment by RePacked** [comment]
I can't reproduce this. Shows correct URI for me.

Device: OnePlus 8
Operating system: Android 10 (OxygenOS 10.5.9.IN21BA)
Build Version: 2.5.0 (3093)
Is this a Beta release? No

**Comment by yegle** [comment]
I can also reproduce it on an Android 10 Pixel 3A phone (QQ3A.200805.001).

**Comment by MGibson1** [comment]
@yegle, What is the Autofill framework you have enabled? From your issue and description I think you're using Accessibility with Draw-Over enabled. Is this correct?

If so, this is _kind of_ an upstream issue with Chrome. The way accessibility grabs the URI is through the address bar in Chrome. Chrome has made the choice to remove the URI scheme from that bar, and so our accessibility code can't get it. We are currently attempting to prepend `http://` and see if that's a valid URI. If it is, we use that. That's why you get `http://github.com/login` instead of `https://...`. The reason for that choice is it's more likely to work. However, these days we really should assume `https://` first.

I'm submitting a PR to update this fallback case when we find no scheme to first attempt to prepend `https://`, then `http://`.

Again, the above assumes you're using Accessibility for your Autofill needs.

**Comment by yegle** [comment]
Ah yes I use accessibility instead of the Autofill API.

Thanks for the fix! I agree the default should be https:// nowadays.

**Comment by MGibson1** [comment]
I'm going to mark this closed since #1186 should have fixed this specific issue. We'll continue to have these problems with accessibility-based autofill, but hopefully the autofill framework fro android shores up in the future and it won't be a problem.
