### ISSUE TITLE
Autofill only fills in email for the BBC iPlayer App

### ISSUE THREAD

**Issue by Trevonn** [bitwarden/mobile#1030]
## Describe the Bug
When I use autofill on the BBC iPlayer App it only fills in the email field leaving the password field blank

## Steps To Reproduce

1. Open the BBC iPlayer app to the login screen
2. Tap on the bitwarden prompt
3. Tap on the saved credentials for BBC iPlayer

## Expected Result
Both the email and password will be filled in.

## Actual Result
Only the email field is filled in.

## Screenshots or Videos
![Screenshot_20200803-131955](https://user-images.githubusercontent.com/3117355/89181709-28827f00-d58c-11ea-9e42-65578fabc1f1.png)

## Environment

- Device: Pixel 4
- Operating system: Android 10
- Build Version: 2.5.0 (3093)
- Is this a Beta release? [Y/N] N

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
