### ISSUE TITLE
Support Yandex Browser for android

### ISSUE THREAD

**Issue by makcum15** [bitwarden/mobile#1036]
Please add yandex browser support for android. At the moment we have to use browser plugin, but it does not work quite stably.

**Comment by cscharf** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by makcum15** [comment]
![Screenshot_20200812-162008](https://user-images.githubusercontent.com/69586893/90026843-2325e280-dcb8-11ea-871e-0597e7204d10.png)

**Comment by makcum15** [comment]
![Screenshot_20200812-162008](https://user-images.githubusercontent.com/69586893/90027336-b95a0880-dcb8-11ea-8c51-5c61c5a2c3fe.png)

Okay, but then change the description here.
https://bitwarden.com/help/article/auto-fill-android/

**Comment by cscharf** [comment]
Ah, thank you for pointing that out!

**Comment by mportune-bw** [comment]
@makcum15 Can you provide more detail as to which version of the yandex browser you're using, and how you've configured autofill and/or accessibility in the Bitwarden app?  We already have yandex support when using accessibility services, so if it's not working for you perhaps we need to revisit.

**Comment by makcum15** [comment]
> @makcum15 Can you provide more detail as to which version of the yandex browser you're using, and how you've configured autofill and/or accessibility in the Bitwarden app? We already have yandex support when using accessibility services, so if it's not working for you perhaps we need to revisit.

Sorry, it's OK. 
The android application offered to enter the password, but did not find it, you had to manually search and select it, so it was on all sites.
In the yandex browser for android has the ability to install Google Chrome extensions, I installed Bitwarden (https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb ) and it filled automatically stable in almost all sites, but to use so not very convenient on the phone.

It turned out that I had a problem with the system, rebooting the phone helped. Now Bitwarden application for android fills in all data stably.

Thank you for your support ;)

**Comment by mportune-bw** [comment]
Great to hear, thanks for letting us know!
