### ISSUE TITLE
Bitwarden will not launch on iOS 13.6

### ISSUE THREAD

**Issue by ryanpcmcquen** [bitwarden/mobile#1039]
## Describe the Bug

Bitwarden no longer launches on iOS 13.6.

## Steps To Reproduce

1. Upgrade to iOS 13.6.
2. Launch Bitwarden.

## Expected Result

Bitwarden would launch.

## Actual Result

Bitwarden flashes briefly, then closes.

## Screenshots or Videos

https://video.drift.com/v/abLuTIrQiwg/

## Environment

- Device: iPhone SE
- Operating system: iOS 13.6
- Build Version: Cannot verify in app, app store says 2.5.0.
- Is this a Beta release? No.

**Comment by cscharf** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
