### ISSUE TITLE
Search does not look in NOTES

### ISSUE THREAD

**Issue by wsw70** [bitwarden/mobile#1040]
## Describe the Bug

Search does not search in NOTES

## Steps To Reproduce

1. add a keyword in the NOTES section of any entry
2. try to search for this keyword from the global search
3. the search fails (does not return the entry with the keyword)

## Expected Result

Search is done against all available fields of an entry.

## Actual Result

It does not (at least for NOTES)

## Environment

- Device: Samsung Galaxy 9+
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): 2.5.0 (3093)
- Is this a Beta release? N

## Additional Context

The issue is also present in the Chrome extension (https://github.com/bitwarden/browser/issues/1360)

**Comment by cscharf** [comment]
Thank you for getting in touch with us. This is expected behavior as we currently we do not support full text search for mobile but it is on our roadmap and being tracked here on our community forms: https://community.bitwarden.com/t/search-within-and-inside-all-notes/10850. For now this issue will be closed.
