### ISSUE TITLE
iOS keyboard passwords app identification

### ISSUE THREAD

**Issue by fopina** [bitwarden/mobile#1052]
Not sure about the proper name of the feature, but when we select "passwords" from the keyboard in the login form of a website/app, it'd be useful to see the URL/appId that is used to look for matches, so we can fix entries and then it matches in future uses.

As it is, I get "no website/app matches" and need to click search and look for it.
Not a big issue, but if I knew what was the match criteria I could edit the record.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
