### ISSUE TITLE
Feature request - Clear clipbord

### ISSUE THREAD

**Issue by laserstrike** [bitwarden/mobile#108]
For those pesky apps that don't support auto fill, it would be nice to have a clear clipboard function set perhaps on a timer for extra security. With options like 15 seconds, 30 seconds etc. I want to leave MiniKeePass for this, so I hope you at least consider it on iOS since android's upcoming autofill will be open to third party apps whereas iOS 11's implementation won't be. (I think.) Thanks.

**Comment by vinaooo** [comment]
+1

**Comment by froman753** [comment]
+1, would also be a nice feature to have with the new desktop apps

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/automatically-clear-clipboard-after-x-seconds-when-using-copy-functions/29

This issue will now be closed. Thanks!
