### ISSUE TITLE
More visibility for TOTP codes

### ISSUE THREAD

**Issue by vinaooo** [bitwarden/mobile#112]
Two suggestions to improve TOTP visibility:

1) Add a special folder or category to show all TOTP cadastred codes on top of other cadastred logins
2) Add option to show and copy TOTP codes directely from logins list

**Comment by MatyCZ** [comment]
This will be very helpful. +1

**Comment by berlincount** [comment]
I'd want this as well.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
