### ISSUE TITLE
Make Bitwarden compatible with Android 4.3

### ISSUE THREAD

**Issue by Vistaus** [bitwarden/mobile#115]
Hello, first let me thank you for this wonderful service! I've made the switch from LastPass to Bitwarden yesterday and I cannot be happier! :) One thing I miss though compared to LP is the mobile app. LP is compabile with my Android version, 4.3, but Bitwarden isn't. Could you make it compatible so that I can use Bitwarden on the go as well?

**Comment by kspearrin** [comment]
We use several APIs that are 4.4 and up so I am not sure this can be done.

**Comment by Vistaus** [comment]
If it's not possible, then I'll accept it. But I still hope you can a way to do it :)

**Comment by King-Tut-Tut** [comment]
One way to solve the problem would be to flash a custom ROM with a newer version of Android, if available.

**Comment by davidwhitman** [comment]
Android 4.3 (and lower) has a lot of bugs in the OS itself that any app supporting them needs to work around. This slows down development, increases the risk of bugs, and makes it hard to use some newer features, all in order to support an OS that came out 5 years ago that only a tiny fraction of users are still on. 

I'm completely new to anything related to bitwarden, but just to throw another voice in, I'd strongly recommend against supporting anything below API 19. The cost isn't worth it.

**Comment by kspearrin** [comment]
We don't be doing this.
