### ISSUE TITLE
Won’t launch URI

### ISSUE THREAD

**Issue by dremelts** [bitwarden/mobile#1164]
## Describe the Bug

Cannot launch URI from bitwarden app

## Steps To Reproduce

Log into bitwarden
search vault for website 
click on the icon next to the URI

## Expected Result

I expect it to open a browser interface to the website that I selected

## Actual Result

NOTHING happens.  It does not blink or give any indication that I tapped the icon
## Environment

- Device: Google Pixel 3a
- Operating system:Android 11
- Security Update: November 5, 2020
- Build Version: RP1A.201105.002
- Is this a Beta release? [Y/N] N

**Comment by SumuduF** [comment]
I'm seeing the same issue. I noticed that not only is this affecting URIs on my vault items, but also seems to have broken the "Bitwarden Web Vault" and "Help and Feedback" items on the Settings page. That last one probably being the simplest example to investigate (AFAIK it is just a static URL and should be independent of any vault-specific stuff).

I have no experience with Android app dev but I'm wondering if maybe the problem is as simple as missing the Android 11 specific manifest stuff described here:
https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?tabs=android#get-started

**Comment by mportune-bw** [comment]
I'm unable to reproduce this on a Pixel 4a, but I'll take a closer look at the new manifest elements in case there's more going on here.

**Comment by Noah-Huppert** [comment]
I can reproduce this on my Pixel 2. The URL looks to be correctly formatted and everything. My father was able to reproduce this on the Pixel 3 as well.

**Comment by loaonline** [comment]
I can reproduce this issue using 2.8.0 (3349) from the playstore.  Using a Pixel 3, Android 11, January 5 2021 security update.

Can not launch to web sites in the URIs/Website field using icon provided.  Tapping provides no feedback or action.

**Comment by dmxgit** [comment]
Same on Galaxy Note20. Even the Help and Feedback button does nothing.
Unless the default browser is not Firefox. When using samsung's browser as default, everything works. 

If using the Bitwarden Firefox extension, from it, it works. But setting Firefox as the default browser, requests from the Bitwarden app to open a URI don't work.

**Comment by rizi** [comment]
Same issue on my Pixel 4a

**Comment by codihuston** [comment]
Same issue on Samsung Note 10+. There is also no auto-fill prompt at login screens in the browser (not sure if this is a feature). I.e.) visiting google.com in chrome and tapping the username input does not yield a dropdown menu or token in the keyboard tray for auto-filling the inputs.

**Comment by Noah-Huppert** [comment]
@codihuston although the fix was merged it doesn't look like it's made it into a release yet, so the bug is still in the app. But I'm sure pretty soon we'll get an upgrade.

I'd search around and see if there is a different issue which exists for your auto fill troubles. That's outside the scope of this issue.

**Comment by codihuston** [comment]
I did see the merge request right after I posted, how exciting! I'll check around regarding the other issues. Thank you!

**Comment by tiptruck** [comment]
Briefly today, I was able to open URIs then it stopped working again. Samsung Tab S7 Android 11 Bitwarden Version: 2.8.2 (3365)

**Comment by grillop** [comment]
Just updated to Version: 2.8.2 (3365).  Launch still fails (does nothing) on Pixel 3a and 4a.  Android 11.  Fails even when trying to get help and feedback

**Comment by Noah-Huppert** [comment]
@grillop and @tiptruck version 2.8.2 (latest version rn) was released on January 25th which is about one month before the patch for this bug was merged. This bug should still be present,  but I'm sure pretty soon we'll get an upgrade.
