### ISSUE TITLE
[Feature Request] Associate login with existing profile

### ISSUE THREAD

**Issue by jakauppila** [bitwarden/mobile#117]
When in the 'Possible Matching Logins' screen after clicking the notification I have the option to press the plus to add a new login which autofills the 'androidapp://' URI. I assume the same thing happens with a website?

Could some workflow be added to quickly associate the incoming URI with an existing profile/login? Possibly an option on the ellipsis?

**Comment by kspearrin** [comment]
I don't really have any ideas as to how this could be done in an intuitive manner. We offer domain rules in the web vault to aide in this.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
