### ISSUE TITLE
[Fix] Bitwarden doesn't work in Android Vivaldi Stable

### ISSUE THREAD

**Issue by the4anoni** [bitwarden/mobile#1171]
## Describe the Bug
Like in topic, autofill doesn't work.

## Steps To Reproduce

1. Tap on log in field.

## Expected Result

Autofill pops out.
## Actual Result

No autofill option
## Screenshots or Videos
![Screenshot_20201208-201408_Vivaldi](https://user-images.githubusercontent.com/13403084/101530251-f47ff600-3991-11eb-9df3-9c09332c6f5b.png)

## Environment

- Device: SGS10
- Operating system: Android Q
- Build Version G973FOXM9DTJB
- Is this a Beta release? N

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
