### ISSUE TITLE
Android 11 Inline Autofill: TOTP not copied when choosing an account from inline prompt

### ISSUE THREAD

**Issue by yegle** [bitwarden/mobile#1207]
## Describe the Bug

It looks like when using the inline Autofill prompt, TOTP is not copied.

## Steps To Reproduce

1. Enable Inline Autofill
1. Go to any website with TOTP configured 
1. Login using the Inline Autofill prompt

## Expected Result

TOTP should be copied

## Actual Result

TOTP not copied

## Environment

- Device: Pixel 4 XL
- Operating system: Android 11
- Build Version (go to "Settings" → "About" in the app): 2.7.2 (3000)
- Is this a Beta release? N

**Comment by Zoran-B** [comment]
The same issue exists with the Andorid AutoFill service. I haven't tested it with the Accessibility service, but I'm guessing it's will be the same result. 
A) If the vault is locked, and the option to unlock sends the user to the app, and the item is selected _from the app_, TOTP gets copied.
B) However, if the vault is already unlocked, and an item is selected _directly in the Bitwarden pop-up_, TOTP does NOT get copied.

**Comment by shivindera** [comment]
bump! any updates on this?

**Comment by tiptruck** [comment]
I logged in to report this bug.  Is there any update?

**Comment by Seedthis** [comment]
Also seeing this on Lineage OS 17 (Android 10).

Zoran-B's description of that issue is exactly what I'm experiencing.

Also, when you go to your vault to manually select your entry in order to be able to copy the TOTP code, you have to refresh the page because it seems to kill Bitwarden autofill functionality (no autofill pop-up).

Hope it gets fixed sooner rather than later.

**Comment by Ri-Dearg** [comment]
I have this issue no matter which option I choose. Android 11 Xiaomi, Miui 12.5
