### ISSUE TITLE
Exception Message

### ISSUE THREAD

**Issue by ThoLorax503** [bitwarden/mobile#1216]
## Steps To Reproduce

1. Go to 'Bitwarden App'
2. Click on 'App'
3. Input credentials 
4. Click on 'Log In'

## Expected Result
I expected to be logged into the app and see my Bitwarden vault. 

## Actual Result
 I receive an error message and cannot login to the app, even after re-installing and restarting my phone multiple times.

## Environment

- Device: [google Pixel 4a]
- Operating system: [CalyxOS 2.1.0]
- Build Version [RQ1A.210105.002.2021.01.06.14]
- Is this a Beta release? [N]

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
