### ISSUE TITLE
Version 2.6.1 newest Version in Google Play store

### ISSUE THREAD

**Issue by TheDuffman85** [bitwarden/mobile#1233]
## Describe the Bug

The newest available version in Google Play store is version 2.6.1 released on 2020-09-23. This was 121 days ago! I already opened an issue for this, but it was closed without further investigation. Also I'm not the only one affected. 

## Steps To Reproduce

1. Go to Google Play
2. Search for Bitwarden
3. See version in App details

## Expected Result

Version 2.8.0 or at least 2.7.2

## Actual Result

Version 2.6.1

## Screenshots or Videos

![Screenshot_20210122-103538](https://user-images.githubusercontent.com/9296618/105473948-00075200-5c9e-11eb-9c4c-996860437d6d.jpg)

## Environment

- Device: OnePlus 7 Pro
- Operating system: Android 10
- Is this a Beta release?: N
- Country: Germany
- Language: German

**Comment by cscharf** [comment]
Hi @TheDuffman85 , thanks for the report, however that's expected as `2.7.2` we halted the rollout of due to some vault timeout issues that were found within the first 30% rollout, and therefore halted in favor of `2.8.0` which has that fix (and is currently only at a 20% rollout). This will continue being rolled out over the next day or so while we monitor to ensure there're no larger issues across devices, etc. Thanks for your patience!

**Comment by TheDuffman85** [comment]
Hi Chad,

thank you very much for the information. This is absolutely understandable. Keep up the good work you are doing.
