### ISSUE TITLE
Auto-fill doesn't work on Android 4.4.2

### ISSUE THREAD

**Issue by SilenceIsG0lden** [bitwarden/mobile#125]
No matter which one of the settings I use -- the default Scan Always or the other two -- bitwarden finds the sites/passwords but doesn't fill them. 
I do get the notification to "tap this notification to auto-fill" but once I picked the correct entry it doesn't fill it it in. Instead, a new notification gets generated -- and I'll go around in circles.

Tried it with 3 different apps (imdb, HEB and goodreads), but it's always the same problem. 
My non-phone device has android 4.4.2 and I always have enabled: Background data restricted and Quiet mode.

**Comment by kspearrin** [comment]
v4.4 should not even attempt to perform an autofill when selecting the entry from the list and instead only offer you options to copy/paste. Autofill requires Android 6 and up.

**Comment by SilenceIsG0lden** [comment]
How odd that it's possible to enable it then, I mean inside my android version. I did the same thing for LastPass, and that worked on and off, within different apps.
I assume that's why some password managers have a virtual keyboard, correct? Are there any plans to offer a virtual keyboard? That would also help with filling passwords into browser login dialogues, I would think. Isn't a copy & paste option using the devices clipboard, which is typically considered a security risk?

**Comment by kspearrin** [comment]
I have made some adjustments in the next version to only offer copy/paste options after tapping the notification from the service. It's still called the "autofill service" but it can't really autofill for you on 4.4. It will just help you by presenting the list of filtered logins for you to use.

Copy/pasting can be considering bad for security if you have malicious applications on your device, yes. There are currently no plans to offer a keyboard since newer versions of Android have much better support for these type of things. 4.4 is a very small percentage of our users.
