### ISSUE TITLE
No pop-up on DuckDuckGoBrowser

### ISSUE THREAD

**Issue by sandoxy** [bitwarden/mobile#1252]
Hey,

on the DuckDuckGoBrowser no pop-up appears in the passwordfield. On other browsers it works fine.

Thanks.

**Comment by clayadams5226** [comment]
Hey @sandoxy, Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
