### ISSUE TITLE
iOS - Search Results Don’t Include Notes

### ISSUE THREAD

**Issue by mycahmason** [bitwarden/mobile#1253]
## Describe the Bug
When performing a search, the results don’t include content from the Notes field.

## Steps To Reproduce

1. Go to the app
2. Click on the search icon
3. Type a search that one of your entries has in the Notes field
4. Results for the expected entry don’t show up

## Expected Result

The search results would include your entry that matched the search from content in the Notes field.
## Actual Result

The results don’t include the expected results.

## Environment

- Device: iPhone XR
- Operating system: iOS 14.4
- Build Version (go to "Settings" → "About" in the app): 2.8.0 (449)
- Is this a Beta release? N

## Additional Context
The web app returns results from the Notes field as expected.

**Comment by sso-bitwarden** [comment]
Hi @mycahmason  ,

This is expected behavior. Only basic search can be performed on mobile app
https://bitwarden.com/help/article/searching-vault/#basic-search

Full-text search is only available in Web Vaults, Desktop Applications, and Browser Extensions.

**Comment by mycahmason** [comment]
@sso-bitwarden Thanks for the reply and the link but I am not trying to use a Full-text Search. I am trying to do a basic search for “iCloud” (e.g. not using: `>notes:iCloud`) which does work in the web app as a Basic Search to return my entry with “iCloud“ (only in the Notes field) but does not work in the iOS app.

I would expect the Basic Search to include Notes after confirming it works in the web app (vs. it being a feature request) which is why I opened the issue here.

Thanks again, Bitwarden is a great app!

**Comment by clayadams5226** [comment]
Hey @mycahmason, basuc search only looks at the following fields, it doesn't currently support notes.    

-  Item Name
-     For Login, Username
-     For Login, URI
-     For Card, Brand or last four digits
-     For Identity, Name

This is currently the intended behavior. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
