### ISSUE TITLE
No save promt in Browser on Android

### ISSUE THREAD

**Issue by JakeGame3** [bitwarden/mobile#1267]
## Describe the Bug

For me, unfortunately, there is no prompt after saving a password in the browser on Android. It works in the apps, but not in the browser. Can you set it so that it also works in the browser?
I also use Bitwarden_rs, is it perhaps because?
In addition, the auto sync between mobile and Pc does not work automatically, I always have to do it manually. Is it possible to do it automatically?

## Expected Result

A prompt when I save a password in the browser on Android.

## Actual Result

No prompt when I save a password in the browser on Android.

## Screenshots or Videos
N/A

## Environment

- Device: Samsung Galaxy S9
- Operating system: Android 10
-Build Version (go to "Settings" → "About" in the app): 2.8.0 (3349)
- Is this a Beta release? [Y/N] N

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by ili101** [comment]
@BLITZ-GIT Was this ever fixed?
Is this a bug or is this feature doesn't exist?

**Comment by BLITZ-GIT** [comment]
@ili101 I don't think so. But I don't use it anymore.
