### ISSUE TITLE
Offer to link to an existing entry (augment domain rule) when login not found

### ISSUE THREAD

**Issue by softmoth** [bitwarden/mobile#127]
When a matching login isn't found, it would be nice for the app to offer to update an existing entry (i.e., add the current site to a domain rule).

The workflow I have in mind is that on the "There are no logins in your vault for com.example.package" screen, there is "ADD A LOGIN" and also "CHOOSE EXISTING LOGIN". If I select the latter, I wind up at my Vault and can search or scroll to select the existing entry I want to use for the current site. At that point, the app would automatically add a domain rule (if needed) and add the current `andiodapp://com.example.package` or `example.com`.

If I don't find an existing entry, then I can just go back and click "ADD A LOGIN" (or there could be a "+" button on the search page, similar to how Contacts works when adding a phone number).

Currently I have to open my browser, log in to vault.bitwarden.com, find the domain settings page, switch back to the bitwarden app and remember the package name, type the package name correctly & save the domain rule, then restart the login to get it to match.

**Comment by kspearrin** [comment]
I've made some attempts to greatly improve the existing detection with #131 . This should reduce the need for having to add lots of domain rules to begin with.

**Comment by softmoth** [comment]
Thanks, it looks like that will reduce the priority of this enhancement request a lot.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
