### ISSUE TITLE
Android: Larger than "default" font sizes are too large

### ISSUE THREAD

**Issue by jgodfrey** [bitwarden/mobile#1272]
## Describe the Bug

On the below-mentioned device, setting the system font (_Settings | Display | Advanced | Font size_) to anything larger than _Default_ (so, _Large_ or _Largest_) causes the text used in Bitwarden to be far larger than expected. 

## Steps To Reproduce

* Set the system font to _Default_
* In Bitwarden, verify the text size looks _as expected_
* Set the system font to something larger than _Default_
* In Bitwarden, verify the text size is _much_ larger than expected, and larger than the Android UI and other apps on the same device with the same font settings.

## Expected Result

I expect the text to be a _reasonable_ size when using larger than default system font sizes.

## Actual Result

The text in Bitwarden is much larger than expected and larger than other apps on the same device using the same font setting.

## Environment

- Device: Pixel 4 XL
- Operating system: Android 11
- Build Version): 2.8.0 (3349)
- Is this a Beta release? N

**Comment by endlessterror** [comment]
New bitwarden user here with nearsightness. Just finished configuring setup on my Samsung s21plus mobile, only to be stricken by how large fonts are, to the point of becoming an obstruction, instead of a mere nuisance.

See also discussion in https://community.bitwarden.com/t/big-font-size-in-bitwardenandroid/16508/10

I do not understand why issue was closed, unless things were much much worse.

Please consider reopening the issue, I'll be more than happy to pay both bw screenshots as well as from other apps for comparison.
