### ISSUE TITLE
Autofill Support for Mull Browser (secure Firefox fork)

### ISSUE THREAD

**Issue by wrkerr** [bitwarden/mobile#1288]
Autofill does not currently work on Mull Browser in Android (us.spotco.fennec_dos).

Mull Browser is a fork of Firefox for Android, built for better security and privacy, with proprietary blobs removed.
https://github.com/Divested-Mobile/mull-fenix
https://gitlab.com/divested-mobile/mull

**Comment by kendratodd** [comment]
Hi @wrkerr! We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by neekless** [comment]
> Hi @wrkerr! We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

How is this a feature request and not a bug? Your autofill is not working on an app. Something that is supposed to be working is not working. You're telling me this is a feature request?
