### ISSUE TITLE
[Feature Request] Log out from the app if the pin was invalid for a certain amount of tries

### ISSUE THREAD

**Issue by tomose-shunsaku** [bitwarden/mobile#1314]
Make a feature that logs you out from the app, For example, it will work when you input the wrong pin / password for 5 - 10 times.

It is useful when you lost your device, and someone is trying to force their way in.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
