### ISSUE TITLE
Please add custom value for lock time

### ISSUE THREAD

**Issue by ElTopo** [bitwarden/mobile#132]
Android app, Settings/Lock Options

1 minute is too short, while 15 minutes are too long.

Chrome extension has 5 minutes option, but Android app does not.

I like 5 minutes, but it would be better to allow user input a custom value (0: immediately, -1: Never, or other numbers in minutes).

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
