### ISSUE TITLE
iOS: Unlock vault with fingerprint on iPad

### ISSUE THREAD

**Issue by philippederyck** [bitwarden/mobile#1338]
## Describe the Bug

The iPad iOS app does not allow unlocking the vault with fingerprint. The iPhone iOS app does support this.

## Steps To Reproduce

NA

## Expected Result

Unlock iPad vault with fingerprint (both during app launch and during autofill)

## Actual Result

I have to retype my master password every time (which briefly shows the last typed character)

## Environment

- Device: iPhone 8 / iPad Pro 10,5 inch
- Operating system: iOS 14.4 (both devices)
- Build Version (go to "Settings" → "About" in the app): 2.9.1 (544) (both devices)
- Is this a Beta release? N

## Additional Context

This is not a feature request, since the code is clearly already available. Not sure why this function is not available on iPad though.

**Comment by kendratodd** [comment]
Hi @philippederyck - Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
