### ISSUE TITLE
Android: please make all Identity files copiable

### ISSUE THREAD

**Issue by guestisp** [bitwarden/mobile#1391]
Currently, only custom fields in Identity cipher can be copied with the icon button.

Please add the same for any other field, in example, the fiscal code, address or similiar, very useful when you have to fill a document.

Actually i have to enter in edit mode, manually copy the field value and then exit

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
