### ISSUE TITLE
Copying new password and selecting generated password is left blank in entry after app locks out

### ISSUE THREAD

**Issue by ikwyl6** [bitwarden/mobile#1396]
## Describe the Bug
When creating a new entry in BW and creating a new password, using the password generator, copying it and also hitting the ‘Select’ button does not keep it in the Password field if you do not save it before the app locks. 

## Steps To Reproduce
1. On any website go to your account settings and choose to update your password
2. Go into the BW entry for this website and choose “Edit”
3. Click the two arrows that form a circle to generate a new password. This brings you to the Password Generator. 
4. Select “Copy password” and then click Select. This inserts that password into your BW entry on the previous screen.
5. Change back to the website (Safari) and paste your password. Update your account settings and update other settings on website (at this time BW app probably has locked out). 
6. go back to BW app to save your password 
7. The password field is blank when you unlock BW app. 
8. repasting it does nothing (blank) to try and figure out what is the new password you just changed to. Reposting into another application on iPhone does nothing (blank). User has to do a Forgot Password on website just after updating the password..

## Expected Result
The app should keep the selected password in the password field. It shouldn’t blank it out after the app locking out. 

## Actual Result
BW blanks/resets/removes the password field when you have selected it from the Password Generator. 

## Screenshots or Videos
None at this time but I can provide if the reproducing steps are not clear enough. 

## Environment

- Device: iPhone XR
- Operating system: iOS 14.4.2
- Build Version (go to "Settings" → "About" in the app): Version: 2.9.1 (544)
- Is this a Beta release? N

## Additional Context
none at this time

**Comment by Krychaz** [comment]
Could you provide which type of Vault timeout and vault timeout action you are running? and also are running unlock with biometrics or pin code?

**Comment by ikwyl6** [comment]
Vault timeout Action = Lock
Vault Timeout = 1 minute
Unlock with PIN code = Disabled
Not running unlock for biometrics or pin. I unlock it by entering my master password after the 1minute.

**Comment by SergeantConfused** [comment]
Hi @ikwyl6,

While I understand your point, you must save your changes in our clients for them to remain when and if the client closes/locks/logs out. This also applies to other clients and that is why we ask to copy and save the newly generated passwords, before pasting and setting them as the new passwords, in step #6 here: https://bitwarden.com/help/article/getting-started-webvault/#generate-a-strong-password

Furthermore, if this does happen again, you can view your password generator history like so: https://bitwarden.com/help/article/product-faqs/#q-can-i-see-the-history-of-the-passwords-i-have-generated instead of resetting the password for that account.

Lastly, you can also increase the time your data remains in your clipboard under Settings > Options, to give yourself more time to paste it somewhere else.

I hope this helps. Please do not hesitate to reply to this message if you have any further questions.

**Comment by eliykat** [comment]
As @SergeantConfused has given a fairly comprehensive answer, and this doesn't appear to be a bug, I'm closing this issue.

We use GitHub issues as a place to track bugs and other development related issues. If you need any help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/).
