### ISSUE TITLE
Can the quick settings tile invoke auto fill, like LastPass, rather than bringing up the vault?

### ISSUE THREAD

**Issue by hacker1024** [bitwarden/mobile#140]

**Comment by kspearrin** [comment]
Currently no. It’s just a quick way to launch the app for now.

**Comment by hacker1024** [comment]
Are there plans to implement this in the future?

**Comment by ivysrono** [comment]
+1

**Comment by Primokorn** [comment]
Actually *Quick Settings* are shortcuts to access **app settings**. For now the QS tile only opens the app so I don't understand why it has been added.

**Comment by mathearts** [comment]
I am also eagerly awaiting the possibility of the quick tile for autofill (instead of the persistent notification).

**Comment by machinagod** [comment]
+1

This was one of my favorite functionalities from LastPass.

Quick settings being only settings doesn't match my view. Most are, but flashlight (one of the defaults) is hardly a setting, but an action (sure... Could also argue the opposite)

**Comment by kriswilk** [comment]
Count me in for this as well. I prefer not having auto fill notifications appearing, and I dislike the idea of a persistent notification even more...my notification pane is already cluttered with a couple of persistent notifications that I wish I could get rid of.

A quick settings tile which performs auto fill would be ideal. Accessible when needed and completely out of the way at all other times.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
