### ISSUE TITLE
Pressing save when a new item is added sends you back to the home page.

### ISSUE THREAD

**Issue by SZE2** [bitwarden/mobile#1409]
## Describe the Bug

When adding a NEW Item saving it should show the new saved item, just like when editing an already existing item.
This is especially annoying when trying to add a login with TOTP, as I cannot see the 6 digit code when editing, only once saved, so I need to go and search the newly created item to get the code.

## Steps To Reproduce

1. Add new Login from Homepage.
1.2 - Add TOTP with camera
2. Save
3. Search for login from home screen so I can verify the TOTP code.

## Expected Result

2. Save
3. Still be on the entry page for that item so I can copy the TOTP code,
4. tap the Back button if I want to go to the homepage.

## Actual Result

Sends me back to the home page of the app.

## Screenshots or Videos
N/A

## Environment

- Device: Galaxy S10E
- Operating system: android 11
- Build Version : [e.g. 2.10.0 (3516)]
- Is this a Beta release? [N]

## Additional Context

NA

**Comment by SZE2** [comment]
This is an issue on the browser version as well, so maybe this should be a feature request?
I'll post there if needed.

**Comment by eliykat** [comment]
Hey @SZE2, yes I agree this is a feature request rather than a bug.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked. (You can make one topic for all clients, e.g. browser and mobile.)

This issue will now be closed. Thanks!
