### ISSUE TITLE
Ability to share from the mobile app

### ISSUE THREAD

**Issue by ohthehugemanatee** [bitwarden/mobile#144]
On Android I can't find an option to share a record with a collection.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/manage-collection-associations-from-more-than-just-the-web-vault/21

This issue will now be closed. Thanks!
