### ISSUE TITLE
iOS - Bitwarden does not clear the clipboard.

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/mobile#1464]
## Describe the Bug

Regardless of what option do you choose, Bitwarden won't clear the clipboard on iOS 14.6

## Steps To Reproduce

1. Go to Options > Clear Clipboard and set to anything that is not _Never_.
2. Copy any password
3. Wait for your time setting
4. Try to paste the password

## Expected Result

Nothing should be pasted because the clipboard has been cleared.

## Actual Result

The password gets pasted.

## Environment

- Device: iPhone SE 2020
- Operating system: iOS 14.6
- Build Version (go to "Settings" → "About" in the app): 2.10.0(616)
- Is this a Beta release? N

**Comment by THEOCKID** [comment]
I don't think this has ever worked on Android (specifically Galaxy S7, Note 10, S20 and S21 Ultra).

**Comment by felixier** [comment]
This definitely used to work on iOS a couple of months ago.
I experience the same issue since summer.
Btw. iOS has an API to copy contents to clipboard with expiration time, so practically it might be iOS issue, but other similar app (competitor) do work and copy to clipboard using Apple Shortcuts also works as expected.
