### ISSUE TITLE
HarmonyOS2 Bitwarden Crash

### ISSUE THREAD

**Issue by hruis** [bitwarden/mobile#1489]
Describe the Bug
The application shows the splash screen for a second and then closes.

Actual Result
The application shows the splash screen for a second and then closes.

Screenshots or Videos
N/A.

Environment
Device: HUAWEI MATEPAD11
Operating system: HarmonyOS2
Build Version: 2.11.3
Is this a Beta release? N.
Additional Context
Rebooting the device does not help.

**Comment by clayadams5226** [comment]
Thanks for getting in touch! Please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
