### ISSUE TITLE
My Vault search not working on latest beta

### ISSUE THREAD

**Issue by josh-haberman** [bitwarden/mobile#153]
In Bitwarden 1.12.0 on the Moto Z Droid with Android 7.1.1 searching "My Vault" doesn't do anything. I've downgraded back to 1.11.1 and this restored the ability to search.

**Comment by kspearrin** [comment]
This seems to be something specific to your device since we haven't received any other reports of this (yet) and I cannot reproduce it on my test devices (emulator and Nexus 5X). If you have some time I'd like to get with you and have you try some custom builds with additional debugging information running so that we can try to see where the issue is occurring.

**Comment by josh-haberman** [comment]
Sure, let me know when/how.

**Comment by kspearrin** [comment]
Awesome. Are you available now? If you could join me in the developer chat now we could go through a few things together. https://gitter.im/bitwarden/Lobby

**Comment by josh-haberman** [comment]
I'm in now.

**Comment by kspearrin** [comment]
Seems syncing resolved this issue. Not sure why though.
