### ISSUE TITLE
building with open source dependencies and tool chain

### ISSUE THREAD

**Issue by DavHau** [bitwarden/mobile#1531]
Open source software is valuable because it potentially allows to verify the app's functioning and important privacy/security features.
In order to verify that, it is important that the software:
 - does not enforce proprietary dependencies (which obviously cannot be verified).
 - can be built using open source tools which have verifyable behavior.

Looking at the build instructions of the current readme. `Visual Studio` and `xamarin` are listed as a requirement, which AFAIK are not open source software.

If the app can only be built using proprietary tools, there is no way for the public to verify the build process and therefore no guarantee that the resulting app behaves like expected.

Therefore I would be interested to build your app using a linux system with open source tools only.

As of now, I cannot find any build instructions provided by bitwarden for building on linux.

Looking at the github pipeline [./.github/workflows/build.yml](https://github.com/bitwarden/mobile/blob/master/.github/workflows/build.yml) , I can see that windows is used to build all android artifacts, including the one pushed to the bitwarden F-Droid repository.

Is there any intention of the bitwarden team to provide a truly open source built mobile app?

As a paying customer I'm doing a security review of my apps right now, and I find it worrisome that it seems like nobody ever actually built bitwarden using an open source tool chain.

**Comment by eliykat** [comment]
[Xamarin is open source](https://github.com/xamarin) as far as I know.

I don't know whether there's an open source alternative to Visual Studio, but we don't have any plans to change our current toolchain/build dependencies at the moment.

We use GitHub issues as a place to track bugs and software defects. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one. Or there's a user-to-user support section where you might be able to get input from other users on how to go about this.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
