### ISSUE TITLE
Inline Autofill broken on Microsoft Edge 93.X.XXX.XX

### ISSUE THREAD

**Issue by x-keita** [bitwarden/mobile#1537]
### Steps To Reproduce

1. Install latest Microsoft Edge stable release (93.0.961.XX at the time of this bug report)
2. Try to log in on any site using keyboard inline autofill suggestions

### Expected Result

Credentials show on the suggestions area on the keyboard

### Actual Result

Blank suggestions area

### Additional Context

Downgrading to the latest beta release (version 92.0.902.80 beta) of Microsoft Edge (not Beta, Canary or Dev) works as expected.

### Operating System

Android

### Operating System Version

11

### Device

Samsung Galaxy S21 Ultra 5G

### Build Version

G998BXXU3AUHB

### Beta

- [X] Using a pre-release version of the application.

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
