### ISSUE TITLE
[Feature Request] Remove internet connectivity dependency

### ISSUE THREAD

**Issue by OhjeezwhathaveIdone** [bitwarden/mobile#164]
With KeePass I have to sync the database with a third party application like Dropbox to be able to access it on mobile using MiniKeePass.  This happens automatically on desktop but not on mobile and as a result requires manual user intervention to sync the KeePass database on mobile with the desktop version.  This can obviously cause sync issues. 
 Bitwarden, by design, removes this syncing complexity by requiring the Bitwarden Application to communicate with the Bitwarden Server but what if the Bitwarden Server is inaccessible from the mobile device?  Regardless of the internet connectivity status KeePass can still view, edit and create entries, on mobile, locally.

In the instances where the Bitwarden Server is not accessible I'd like to have the ability to still edit and create entries via the Bitwarden App.  The modification should be stored locally and sync'd to the Server when next connected.

Examples for when the Bitwarden Server may not be contactable:
- When on a secure/limited network and with no mobile signal
- The Bitwarden Server itself is not accessible (whether it's the cloud or self hosted version) for whatever reason

**Comment by kspearrin** [comment]
Just FYI: you can still view and use (autofill) all information in your vault without an internet connection. The apps effectively run in a "read only" mode.

**Comment by OhjeezwhathaveIdone** [comment]
@kspearrin but that does not allow me to create entries on mobile unless I have an active connection to the Bitwarden Server, correct?  I did test this last night and Bitwarden requested an active internet connection, but in case I am wrong, I'd like to confirm.

I know in my use case of Bitwarden that I **won't** be able to connect to the Bitwarden Server all of the time, however regardless of connectivity status I'd still need to make modifications, hence I'd like the ability to sync any modifications that have been created whilst the device has been disconnected from the Bitwarden Server once reconnected.

**Comment by kspearrin** [comment]
That is correct. I was commenting on your above statement:

> In the instances where the Bitwarden Server is not accessible I'd like to have the ability to still ***view***, edit and create entries via the Bitwarden App.

You can still *view* things today without an internet connection.

**Comment by OhjeezwhathaveIdone** [comment]
Ah, my apologies.  Understood.

**Comment by jerryn70** [comment]
I think  @Ohjeezwhatthaveldone is requesting for a feature . 
The ability to add and edit entries without internet connection.

**Comment by jerryn70** [comment]
Are you planning to give Bitwarden  add & edit ability without internet

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/offline-management-of-writeable-vault-items/107

This issue will now be closed. Thanks!
