### ISSUE TITLE
Manage collections through app

### ISSUE THREAD

**Issue by amenk** [bitwarden/mobile#167]
It does not seem to be possible to manager org collections through the app.

Can this be implemented or is it technically impossible?

**Comment by kspearrin** [comment]
It could be done but we likely will not make such things available in all the client apps. You can access and use the web vault on your mobile device.

**Comment by amenk** [comment]
Okay, I understand that.
Unfortunately the web vault presents a bit a security risk, as it could be man-in-the-middle attacked (I believe). So I would prefer that commonly used functions like collection management (adding users, adding passwords to them) would work from the extension and/or mobile.

**Comment by kspearrin** [comment]
I am not sure how you are determining a greater risk of MITM attacks in the web vault? They all talk to the same endpoints over SSL.

**Comment by amenk** [comment]
https://github.com/bitwarden/web/issues/146 :)

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

----

There is this request already: https://community.bitwarden.com/t/manage-collection-associations-from-more-than-just-the-web-vault/21
