### ISSUE TITLE
bitwarden should not show popup to fill if it does not has any

### ISSUE THREAD

**Issue by sheikh-azharuddin** [bitwarden/mobile#1701]
### Steps To Reproduce

Open any website for which password is not saved in bitwarden.on clicking login, website shows username and password field however if bitwarden does not has any password for that site it should not show the popup. This is frustrating because sometime I click that notification which takes me to the app and on searching no result found which is expected..but why confuse the user?

### Expected Result

Like lastpass bitwarden should not show the popup in login field if it does not has any password stored for that site

### Actual Result

Bitwarden showing prompt to fill password even though it has none saved for the site!

### Screenshots or Videos

Why should I see this prompt?
In lastpass no such prompt showing if password not saved for the site

![Screenshot_20211229-194001447 (1)](https://user-images.githubusercontent.com/58127841/147670905-a8412a7f-2648-426d-b62f-ec3fea94ac6a.jpg)

### Operating System

Android

### Operating System Version

android 11

### Device

asus rog 3

### Build Version

2.15.0

### Beta

- [X] Using a pre-release version of the application.

**Comment by eliykat** [comment]
This is the intended behaviour, so that you can create a new login if required, and then fill it into the form.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
