### ISSUE TITLE
Fingerprint reading issue on galaxy s8

### ISSUE THREAD

**Issue by IOI-655321** [bitwarden/mobile#176]
Just curious about fingerprint support, on my galaxy s8 I have issues with Bitwarden getting my fingerprint right. Paypal, Ebay and even LastPass always works a lot more smoothly. Is this something that can be looked at?

**Comment by kspearrin** [comment]
Does it prompt you to read you fingerprint? What happens?

**Comment by BigNickBurgess** [comment]
Yeah it prompts to read fingerprint but seems to be a lot more prone to not picking it up and eventually dumping me to a page with a button to click to 'unlock with fingerprint' or some such.  On Paypal, Ebay and LastPass it usually works first time but Bitwarden can sometimes take 3 or 4 attempts.

I know the S8 scanner is a bit more awkward than most but seems a bit odd that this isn't happening in all apps in the same manner.

**Comment by BigNickBurgess** [comment]
Having thought about this some more could the fingerprint screen just be improved to lessen the annoyance factor if the fingerprint isn't read for whatever reason?

In the screenshots below from Solid Explorer their Fingerprint sensor panel gives the feedback from the sensor about making sure the sensor is fully covered (LastPass also provide this but as a Toast notification) 

Rather than using the logout link or eventually ending up at the app screen with a button to use fingerprint or logout could we enable an app pin alongside fingerprint as a secondary login method or if this pin isn't setup have an option to login with Master Password from the fingerprint panel?

![screenshot_20180104-104446_solid explorer](https://user-images.githubusercontent.com/31211392/34560165-b6d19976-f13c-11e7-8db6-6c69234b86d6.jpg)
![screenshot_20180104-104452_solid explorer](https://user-images.githubusercontent.com/31211392/34560166-b6e846a8-f13c-11e7-895f-315316f57243.jpg)

**Comment by kspearrin** [comment]
PIN + Fingerprint is now available in next version.
