### ISSUE TITLE
[Feature Request] Picture-in-picture / Draw over other applications

### ISSUE THREAD

**Issue by pzmarzly** [bitwarden/mobile#177]
Notification drawer is quite uncomfortable to reach. Something like SuperSU dialog would be appreciated.

![screenshot_20171120-162242](https://user-images.githubusercontent.com/8074163/33025760-1a484500-ce0f-11e7-9687-b6dfbc1990ed.png)

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
