### ISSUE TITLE
What is Google Cloud Messaging used for?

### ISSUE THREAD

**Issue by pzmarzly** [bitwarden/mobile#179]
I am using a device without Google Services nor its alternatives (microG) installed, so GCM doesn't work in any app for me.

But I haven't noticed any missing functionality in the application so far. So is the lib unnecessary?

If there is a reason to use push notifications, could you consider switching to [MQTT push-notification protocol](https://github.com/mqtt/mqtt.github.io/wiki/software)?

**Comment by kspearrin** [comment]
Real time updates for changes to your vault.

**Comment by pzmarzly** [comment]
Yet the app does a full sync every now and then, right? Could we get a option to specify the interval, by the way?

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
