### ISSUE TITLE
iOS requiring master password every time when autofill despite vault timeout value

### ISSUE THREAD

**Issue by xingped** [bitwarden/mobile#1853]
### Steps To Reproduce

1. Unlock vault and set vault timeout to 4hrs
2. Open browser (any) and go to login page
3. Click on login form field
4. Click passwords option on iOS keyboard
5. See that master password prompt is displayed

### Expected Result

Vault master password prompt should not display (like on Android)

### Actual Result

Master password prompt displays

### Operating System

iOS

### Operating System Version

15.3.1

### Device

iPad 9th gen

### Build Version

Version: 2.16.2 (1434)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Larry-Sussman** [comment]
Hi @xingped, thanks for submitting this issue report! Unfortunately, this is a limitation of iOS and our iOS Bitwarden app will prompt for authentication every time, unlike on Android. Kyle has mentioned this in a Reddit thread [here](https://www.reddit.com/r/Bitwarden/comments/cbgypq/comment/etflucz/?utm_source=reddit&utm_medium=web2x&context=3), and I'll paste a quote below:
>  iOS extensions do not share the same memory space with the main app. So it is not possible for us to share the same lock timer. Therefore, the extension locks every time you close it.

A potential workaround for you to save time in this scenario is to use biometric unlock on your Bitwarden app on iOS, you can  learn more about this here: https://bitwarden.com/help/biometrics/

I hope this helps shed some light on this issue, thanks again for the report! 😄

**Comment by d0x7** [comment]
Before opening a new issue, I thought I'd comment there. What you stated is actually incorrect. I've been using Bitwarden for a few years now and I had it setup so that it autofills without any further auth, no password, no touch/face id. Now, with iOS 17, this behavior has changed. I need to enter the master password every single time I wanna fill something. In some apps that have username and password on different intents, I need to enter my master password twice - once for the username/email field, to then be taken to the next intent with a password field and be required to fill my master password again. Afaic it's usually that you need to enter bio (face/touch), even if not enabled in Bitwarden (iPhone thing), but if you go into your iOS settings -> Touch/Face ID & password and in there disable the "Use Touch/Face ID for: AutoFill password", then is completely auth-less; so to speak. Can just click the username/email above the keyboard in a login intent and it instantly fills without further popups. With iOS 17 this is no longer the case. I need to enter the Bitwarden master PW every time, which is both super annoying and frustrating, but also defeats the point of a password manager, if I have to enter my, well, password every time i wanna auto fill another one. Not sure what you mean about shared memory and such, because the settings on the Bitwarden app are clearly set to never lock, do not use touch/Face ID, do not use a passcode. So this is from my point of view definitely a bug, or bad design. I've temporarily migrated to a competitor, because this behavior is unacceptable if I have hundreds of auto fills a day on which I need to enter my master pass every single time, sometimes twice because of separate user/pass intents, but I would prefer to stay with Bitwarden in the long run if this gets fixed. Two other PW manager do not have this issue on iOS and are working like Bitwarden did in pre-iOS 17.

**Comment by eliphatfs** [comment]
Still meeting this in 2024... Just switched from another password manager and feel very disappointed about this. even using faceid, which can possibly be less safe than the master password, it is a much slower workflow if i need to do once for user, once for password, once for totp/passkey.
