### ISSUE TITLE
Bitwarden Android Client with on-Premise server - won't resolve host name

### ISSUE THREAD

**Issue by amsteel** [bitwarden/mobile#1873]
### Steps To Reproduce

Bitwarden running in Docker.
Server version: 1.47.1
Web version: 2.27.0
Firefox desktop extension version: 1.57.0
Firefox mobile extension version: 1.57.0

The server is hosted on-premise with no public access, host name: bitwardenserver.lan.local

Everything works from desktop, on Windows 10, 11 and varies Linux.

The Firefox extension works in Android.

The only issue is Android client. If bitwardenserver.lan.local is used, then it complains that the host name won't be resolved. If bitwardenserver is used, then it connects but complains the server name is not matching the name in the certificate, which is correct.

I tried IP tools and Network Analyzer on Android, the DNS lookup worked for bitwardenserver.lan.local. It returned the correct LAN IP of the server. 

I am not sure if is an bug with Bitwarden or if it is just something new with Android. My phone is running Android 12.

The other thing I have noticed is that the Android browser (Firefox and Chrome), both can't open https://bitwardenserver.lan.local, saying address is not found. However both are ok to open: https://bitwardenserver and I can login to see my vault.

Anyone has similar issue?

### Expected Result

Android Client should be able to login

### Actual Result

hostname is not resolved

### Operating System

Android

### Operating System Version

12

### Device

Poco X3 Pro

### Build Version

2.17.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by tangowithfoxtrot** [comment]
@amsteel 

You usually want to avoid using `.local` in your domain name, as [it is a special-use domain name conflicts with the mDNS protocol](https://en.wikipedia.org/wiki/.local) used by Android (and other operating systems) to discover devices on your local network. As such, you will usually run into issues using `.local` for your TLD.

I recommend running through our [self-hosted setup guide](https://bitwarden.com/help/install-on-premise-linux/) again, and setting your domain to something that doesn't conflict with the mDNS protocol. Something like `bitwardenserver.lan` should work.

We use GitHub issues as a place to track bugs and other development related issues. If you need further assistance configuring Bitwarden, please contact our Customer Success team here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by amsteel** [comment]
@tangowithfoxtrot If the issue is related the .local domain name, would it impact both the client and the browser extension? The extension works without any issue in Firefox (Android). That is why I think there maybe a bug in the mobile client itself and did not post it in the community forums. Any comments?

**Comment by tangowithfoxtrot** [comment]
@amsteel Not necessarily. Some software might not need or opt to use mDNS, even if the operating system does. Since this can vary greatly, it's recommended to avoid using `.local` as your domain suffix.
