### ISSUE TITLE
App icon not themed on Android 12

### ISSUE THREAD

**Issue by ffactory-ofcl** [bitwarden/mobile#1884]
### Steps To Reproduce

1. (Android 12) Activate themed icons in the pixel launcher
2. Open the home screen
3. Bitwarden's icon is not themed for use with material you

### Expected Result

Bitwarden should follow the Material you guidelines and bundle a themed icon, as described [here](https://developer.android.com/about/versions/13/features#themed-app-icons). 

### Actual Result

It has the default blue icon. 

### Screenshots or Videos

![Screenshot_20220419-065451_VLC](https://user-images.githubusercontent.com/33554869/163922869-0b7c18e8-d7ae-4c9c-8a55-807c0bdcda17.png)
(see the other icons in the background)

### Operating System

Android

### Operating System Version

12L

### Device

Pixel 6

### Build Version

Version: 2.17.0 (4526)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by tangowithfoxtrot** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by vvolkgang** [comment]
@ffactory-ofcl #1940
