### ISSUE TITLE
Recent / frequently used sites

### ISSUE THREAD

**Issue by benshep** [bitwarden/mobile#190]
I don't find the **Favorites** screen very useful, as I only have one record in it (my personal details autofill record). A more useful thing (for me) would be a **frequently used** and/or **most recently used** screen. This applies to the browser plugin as well as the app, but it's most relevant for the app since the first screen after login is currently **Favorites**.

**Comment by BigNickBurgess** [comment]
Theres a new option to make the vault the first page in settings in the current Android beta.

**Comment by benshep** [comment]
Cool! How do I sign up for the beta?

Any plans to add frequent or recent logins then?

**Comment by kspearrin** [comment]
Click the join button on the google play page.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
