### ISSUE TITLE
My vault frame drops on scrolling

### ISSUE THREAD

**Issue by pc00per** [bitwarden/mobile#1908]
### Steps To Reproduce

The very first "My Vault" menu after opening/unlocking bitwarden app vault.

### Expected Result

Scrolling has to be smooth

### Actual Result

Scrolling lags & frame drops occur.

### Screenshots or Videos

Can't show (due to privacy)

### Additional Context

Tried disabling website icons too. Same behaviour.

### Operating System

Android

### Operating System Version

Lineage OS 18.0 (R)

### Device

Redmi Note 10

### Build Version

2.18.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by aj-bw** [comment]
Hi @pc00per!
Thank you for getting in touch and bringing this to our attention! I did some testing and so far have been unable to reproduce the issue. However, we would like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
