### ISSUE TITLE
Allow user to download files rather than trying to open them

### ISSUE THREAD

**Issue by r3r57** [bitwarden/mobile#192]
Unfortunately I'm not able to open or simply download attached files to my Android device. 

### What did I do? 
I attached a text file **without or unknown file extension** to an entry and tried to open/download it on my Android device.

### What happened?
The error message "Your device can't open this file" appeared.

### Expected behaviour
The "Open With..." dialog shows up or the file is downloaded

### Possible solution
Bitwarden should not try to [open](https://github.com/bitwarden/mobile/blob/a2c962c2f63c7f93c453d08b0b4d4e7e7df64c03/src/Android/Services/DeviceActionService.cs#L52) the file but to download it.

**Comment by kspearrin** [comment]
I don't think this is possible? Android requires that you provide a type hint to the open with dialog. Without an extension there is no hint to give.

**Comment by R3r57** [comment]
A lot of extensions won't work, but I see this is an Android related issue and not Bitwarden's?

**Comment by kspearrin** [comment]
Unless there is some way to tell android to allow any file to open (a wildcard) I do not see a way this is possible. Are there other apps that let you open this type of file?

**Comment by R3r57** [comment]
What about letting the user choose whether to open or just download attachements if this is possible?

Currently I'm using attachments mainly to save certificates, SSH keys and confidential configuration files which are used with other Android apps like [JuiceSSH](https://juicessh.com/) or [Termux](https://termux.com/). Bitwarden doesn't allow me to access/save these files locally at the moment because it tries [to open it and checks whether it (or better Android) can do so or not](https://github.com/bitwarden/mobile/blob/a2c962c2f63c7f93c453d08b0b4d4e7e7df64c03/src/Android/Services/DeviceActionService.cs#L52) and in my case it can't. 
In some cases It's not in my interest to open the file directly with some sort of app because I know Android can't and shouldn't deal with these kind of files.
For my use cases it would be totally sufficient to download the file to my home directory so I can work with it.

Unfortunately I'm not an Android developer and therefore I can't judge if just downloading the file is possible but I hope you can tell me and maybe 'just downloading attachements' might be worth discussing?

**Comment by kspearrin** [comment]
@R3r57 I am not sure if this is possible yet or not. Will have to explore it more.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
