### ISSUE TITLE
Feature Request: iOS Force/3D Touch Passcard Functionality

### ISSUE THREAD

**Issue by trparky** [bitwarden/mobile#194]
I would like to see the ability to Force/3D Touch a Passcard and have a popup come up asking if I want to copy the username or password to the iOS system clipboard.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
