### ISSUE TITLE
iOS Crash on previously opened item

### ISSUE THREAD

**Issue by steakknife** [bitwarden/mobile#1970]
### Steps To Reproduce

1. Unlock vault with FaceID
2. Select an item to view its detail
3. Switch to another app
4. Wait long enough for the vault to lock
5. Login to the vault with FaceID

### Expected Result

Not crashing.

### Actual Result

Old item shows, but then the a crashes to the launcher.

### Operating System

iOS

### Device

iPhone 13 Pro

### Build Version

Version: 2022.05.0 (1736)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by aj-bw** [comment]
Hi @steakknife,

Thanks for reaching out! So far I am unable to reproduce this issue on a like device / version of iOS. We'd like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content, the issue here will be closed.

**Comment by steakknife** [comment]
Still happening. This isn't resolved.

**Comment by dbosompem** [comment]
Hello @steakknife , sorry for the inconvenience. It could be that this problem is one that is specific to you and may not be a general bug. We kindly ask that you contact support [here](https://bitwarden.com/contact) so we could further assist you. If you have any other additional info that might be helpful, you could share that as well too. Hope this helps.

**Comment by steakknife** [comment]
This is still an issue. And it's consistent. The app is also set to upload
crash logs. Did you review them?
