### ISSUE TITLE
an unhandled error has occurred when i signed in with android version browser extension and others 

### ISSUE THREAD

**Issue by baldhead233** [bitwarden/mobile#2026]
### Steps To Reproduce

when i signed in showing an ### unhandled error has occurred 
when i signed in with android version browser extension and others 

### Expected Result

succeed to sign in and save my account and password 

### Actual Result

**an unhandled error has occurred** when i signed in with android version browser extension and others 

### Operating System

Android

### Operating System Version

Android 9

### Device

vivo x21a ,chrome,  edge

### Build Version

latest version

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
Hi @baldhead233 this was likely happening due to the scheduled maintenance window for the 2022.8.0 release: 
In case you experience this again, please check out our status page over at https://status.bitwarden.com/ 

Closing this now, but please feel free to comment if you are still experiencing issues.
