### ISSUE TITLE
Requiring providing master password on application restart is not respected when a pin is set together with biometrics unlock

### ISSUE THREAD

**Issue by mfronczyk** [bitwarden/mobile#2032]
### Steps To Reproduce

1. Go to 'settings'
2. Enable 'unlock using Face Id'
3. Click on 'unlock using pin'
4. Set a pin
5. On the question 'do you want to require providing master password after application restart', click 'yes'.
6. Shutdown the application
7. Open new instance

(These might not be the exact English labels because my app renders in Polish, but I think it's close enough to reproduce)

### Expected Result

Application should require the master password in order to unlock

### Actual Result

It can be unlocked using master password or biometrics

### Additional Context

I'd basically like Bitwarden to require providing the master password from time to time in order to help me remembering it (not forgetting). I couldn't find such option, but it seemed the setting a pin and then requiring the master pass to be provided on restart would help he to mimic such behavior, but it doesn't seem to work as I expected.

I'd also be grateful if you could let me know if there's somewhere an option to request providing the master key from time to time.

### Operating System

iOS

### Operating System Version

15.6

### Device

iPhone 13 Pro

### Build Version

2022.6.2 (1951)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by grapexy** [comment]
Is there anything holding up the fix on this issue? It has been 2 years since it was reported and is actually a pretty significant security issue. There were even 2 PRs in this time, without any attention from BW team.

One would think BW team would be more interested in resolving this, given the recent vulnerability with biometrics on Windows. Persisting keys across app restarts and even device reboots is something users should be able to turn off, and probably should be a default anyway (it's how KeepassXC and KeepassDX work, for example).

Right now, BW's key security with biometrics just relies on the assumption that device can store the key securely when used with biometrics, which is another vulnerability waiting to happen, if not already a vulnerability.

Current model means, that if someone were able to get access to the device, either by forcing the user to use biometrics, or using an exploit in any of the components responsible for storing key data, they will, in 100% of cases also get access to the BW. This is dissimilar to Keepass or other password managers, which only persist the key in volatile memory, device exploit there would leave database protected.

The title/description of this issue is also misleading. The issue is not that master password is not required when both Pin and Biometric are used, it's that master password is never, ever going to be required on device if biometrics is used. This behavior even got ported to BW beta app.

**Comment by micahblut** [comment]
Thanks all for the continued interest here. I can confirm that the native app is behaving as expected.

The reason we have this setting in place is so that users can decide whether or not their userKey is persisted on disk or only in memory when encrypted with the PIN. Because PIN is lower entropy, some users may not want their PIN-encrypted userKey to stay on disk when the application is restarted. 

However, biometrics-encrypted userKeys have a much higher entropy and do not need to be protected in the same way. Therefore, we allow unlock with biometrics following application restart.

We will make the copy when setting a PIN more clear so users understand what to expect.

**Comment by grapexy** [comment]
@micahblut  I strongly disagree with closing this issue as "completed." The current behavior represents a significant security vulnerability, not an intended feature.

The core problem is that biometrics-encrypted keys are being persisted to disk indefinitely, allowing unlimited future unlocks without ever requiring the master password again. This fundamentally undermines the security model of a password manager.

- Biometric security is not infallible. There have been numerous vulnerabilities found in biometric systems across devices. Relying solely on biometrics for long-term key protection is risky.
- This creates a single point of failure. If the device's secure enclave or biometric system is compromised, the vault is permanently exposed.
- Users have no way to enforce periodic master password entry, which is a standard security practice for sensitive data.
- The current behavior violates the principle of least privilege by keeping the encryption key accessible for longer than necessary.
- It's inconsistent with how other reputable password managers handle key storage.

The suggestion to simply "make the copy more clear" misses the point entirely. Users should have the option to require periodic master password entry, regardless of biometric settings. This is about security, not just user expectations.
Please implement proper key lifecycle management. At minimum, provide an option to require master password entry on a configurable schedule or app restart, even when biometrics are enabled. Security-conscious users shouldn't have to choose between convenience and proper key hygiene.

**Comment by micahblut** [comment]
@grapexy you make some excellent points. I encourage you to open a feature request on our community forum so that others can contribute and weigh in on whether such a feature is desired. As is, the features are behaving as intended and we will make this more clear to users by updating the copy.

**Comment by ottomorac** [comment]
@grapexy I fully agree with you and this is one of the key reasons that I have not enabled biometrics unlock on my Bitwarden app on mobile. I was tempted to use biometrics when I first saw a friend use it, but upon further research there

> Users have no way to enforce periodic master password entry, which is a standard security practice for sensitive data

This to me is the feature that is required in order to do more robust biometrics login. Periodically requiring master password re-prompt in a configurable schedule would be the better way of doing biometrics on mobile.

> Users should have the option to require periodic master password entry, regardless of biometric settings. This is about security, not just user expectations. Please implement proper key lifecycle management. At minimum, provide an option to require master password entry on a configurable schedule or app restart, even when biometrics are enabled. Security-conscious users shouldn't have to choose between convenience and proper key hygiene.

That comment is spot on as well. I was tempted to use the "session timeout" as way to enforce this, but sadly it can only go up to 24 hours, and not something like every 2 or 3 days which would my desirable balance between using the convenience of biometrics and requiring periodic prompting of the master password.

@grapexy Do you know if your or anyone else ended up creating feature request for this in the forums? I would be willing to upvote it for sure.
