### ISSUE TITLE
password records for web url's with unicode failed to find

### ISSUE THREAD

**Issue by icegood** [bitwarden/mobile#2052]
### Steps To Reproduce

1. Go to ['...'](https://xn----9sbmbgknu2ce4eva.xn--j1amh/)
2. Create account with password here in browser for desktop
3. Check that desktop searches OK. 
4. Goto mobile android application. Try to autofill bitwarden record

### Expected Result

bitwarden record was found and auto-filled

### Actual Result

The are no items in your vault for "зубные щетки.укр"

### Operating System

Android

### Operating System Version

10

### Device

Huawei p20 pro CLT-L29

### Build Version

10.0.0.201 (C432E8R1P3)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Larry-Sussman** [comment]
Hi @icegood, thanks for the report! 

Your issue appears to be describing the intended behavior of the software, I don't believe we support Unicode URLs this way: 
> For now, we can only support puny code versions of the domain. An external library would be required to decode it back if we wanted to support it further in the future.

There is some more info available here: https://github.com/bitwarden/clients/issues/910
If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
