### ISSUE TITLE
[android] Fix color on android Navigation Bar

### ISSUE THREAD

**Issue by Jean-BaptisteC** [bitwarden/mobile#2062]
### Steps To Reproduce

1. Open app
2. Unlock Bitwarden

### Expected Result

Android Navigation Bar color follow Bitwarden navigation bar
- To fix bug add new item `navigationBarColor` on each Themes Android with Bitwarden navigationBarColor

### Actual Result

Android Navigation Bar color doesn't follow Bitwarden navigation bar color

### Screenshots or Videos

Android Navigation Bar is black and Bitwarden navigation bar is white
<img src="https://user-images.githubusercontent.com/87148630/188503233-a5331fc6-2b48-46d1-89bb-ab90a7ec89f3.png" height="500"/>
Android Navigation Bar is black and Bitwarden navigation bar is dark
<img src="https://user-images.githubusercontent.com/87148630/188503373-27e29b23-5cce-4e58-b044-55c8690a7334.png" height="500"/>

### Operating System

Android

### Operating System Version

Android 13

### Device

Pixel 6

### Build Version

2022.8.0(4911)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vphan916** [comment]
Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
