### ISSUE TITLE
[Feature request] Default View to Search page option

### ISSUE THREAD

**Issue by BigNickBurgess** [bitwarden/mobile#208]
Can you add an option to expand the folders on the vault by default please now we can set it as the start page?

Would just save a click through or using the search to quickly scroll and click the item I want.

**Comment by kspearrin** [comment]
So an option to default to the search page?

**Comment by BigNickBurgess** [comment]
Yeah that'd work as well

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
