### ISSUE TITLE
Regex matching not working on Android Chrome (works on desktop)

### ISSUE THREAD

**Issue by NlC1ww5DhElfAmDbyMosN7iMkGUJEelYWkTYIBU** [bitwarden/mobile#2124]
### Steps To Reproduce

1. Create a login with regex type matching. For testing, I used: `\?page=admin$`. (Match _any_ URL ending in the literal string "?page=admin".)
2. Visit a domain which should match the regex. ("{anydomain.com}?page=admin")
3. Tap on a field requesting login credentials.

### Expected Result

I expect Bitwarden on Android Chrome to have the same matching results it has on Windows Edge, where I see the expected matching result.

### Actual Result

Bitwarden on Android fails to find any login matches.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16807422/195136332-6ca8e9fe-af6a-4610-9fb7-2e345ae7f7fb.png)

![Screenshot_20221011-113911](https://user-images.githubusercontent.com/16807422/195137378-26ec6608-3e4c-424d-880b-9d94c10b2505.png)

### Additional Context

I saw there was a previous issue with Android Chrome not matching _starts with_ patterns because the schema is not shown in the address bar. This is not related to that issue because in this case, whether the schema is shown or not, the makeshift "ends with" pattern should match.

### Operating System

Android

### Build Version

2022.9.1 (5047)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hello,

Please try reproducing the issue with the beta version of the native app. The beta program can be joined, and the app downloaded from here: https://community.bitwarden.com/t/about-the-beta-program/39185

Recent updates have been made in the beta builds, so it would be helpful to check if the issue still occurs with the latest version.

Thank you for your cooperation, and looking forward to the feedback!

**Comment by joshuataylor** [comment]
This doesn't seem to been working on the release build for Android either (as of 2024-09-15).

The beta build (Version: 2024.8.1 (19099) works with this.

**Comment by jasmines** [comment]
Still not working in 2025.3.0

**Comment by SaintPatrck** [comment]
Hi all,

The Android autofill framework only exposes the web domain and web scheme. Unfortunately that means it is not currently possible for us to perform Regex matching on the port, path, or query string. I double checked [2024.8.1-beta (19099)](https://github.com/bitwarden/android/releases/tag/v2024.8.1) and I'm seeing the same behavior.

We have submitted an [issue tracker ticket](https://issuetracker.google.com/issues/378464307) with Google, but have yet to receive a response.

Below is a screenshot of an autofill request received from `https://10.0.2.2:8080`. As you can see, the port information is not present.

<img width="268" alt="Image" src="https://github.com/user-attachments/assets/f2686747-9d6a-402f-a74b-416b0f10d791" />

Similarly, when we receive an autofill request from `https://cloudcarpenter.com/?page=admin`, the query string `?page=admin` is nowhere to be found so we are unable to filter appropriately.

As a friendly reminder, this repository will be archived in the near future. There are new repositories for the [iOS](https://github.com/bitwarden/ios) and [Android](https://github.com/bitwarden/android) clients. This issue was transferred to [Regex matching not working on Android Chrome (works on desktop) bitwarden/android#2124](https://github.com/bitwarden/android/issues/2124). Please report issues in the appropriate client repository to ensure the correct team is notified.

**Comment by jasmines** [comment]
@SaintPatrck it seems that for a simpler match, such as https://mydomain.com/file.html the exact match, starts with and regex are not working as well. Can you confirm?

**Comment by SaintPatrck** [comment]
Since path data is absent, attempting to match against `https://mydomain.com/file.html` would never succeed because `/file.html` is part of the URL path. In order for exact, starts with, or regex matching to work one of the associated URIs saved in Bitwarden would need to be some variation that only includes the domain and/or scheme. E.g., `https://mydomain.com`, `mydomain.com`, `*.mydomain.com`.
