### ISSUE TITLE
Android client got no response randomly.

### ISSUE THREAD

**Issue by Hj6RYPIsHtGa4d4ft1OAULv5GIXDmPo3gDUYhEy** [bitwarden/mobile#2147]
### Steps To Reproduce

This happens really randomly. 

The app appears to be frozen(it feels like it was masked by some layer honestly speaking), with no buttons tappable. But fingerprint auth prompts out at the start normally, and I could finish the auth, after which everything is still irresponsive, including the password entries, and sections on the bottom.

I tried clearing the data and launching it again, but it still acts like the aforementioned. 

I dropped the phone aside for a while and it magically recovered normally...

I met with this situation for many times and I decide to record it this time.

Thx the dev for making Bitwarden better!! Looking forward to a reply.

### Screenshots or Videos

Check out this video that was shot then.
https://img.niubi.tk/bitwarden2.mp4

And this clip after a data clear..
https://img.niubi.tk/bitwarden.mp4

### Operating System

Android

### Operating System Version

MIUI 12.5.16 android11

### Device

Xiaomi Mi 11

### Build Version

2022.10.0 from playstore

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. If you're still experiencing issues with Bitwarden becoming unresponsive, it might be helpful to check for common offenders that could be affecting the app's performance:

1. Blue/Yellow Light Filters: These filters can sometimes activate automatically based on time settings, potentially causing Bitwarden to become unresponsive. You can try adjusting these settings or disabling the filters temporarily to see if it resolves the issue. 
2. Translator Apps and Streaming Apps: Apps like translator or streaming services can 'seize' control of the screen, which might cause Bitwarden to appear unresponsive underneath. Consider disabling these apps or adding exceptions to prevent them from interfering with Bitwarden. Similar issues have been reported with other apps like [NewPipe](https://github.com/TeamNewPipe/NewPipe/issues/6770).
3. Screen Orientation: Using Bitwarden in certain screen orientations (like pop-up, portrait, or landscape mode) can sometimes lead to interference. Try using Bitwarden in a different orientation to see if the issue persists.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
