### ISSUE TITLE
Add support to Smart Lock for Passwords

### ISSUE THREAD

**Issue by vinaooo** [bitwarden/mobile#223]
This could allow user to auto login without need to use a computer or other way to use secure passwords and 2fa

For example using passwords generated by bitwarden to login on bitwarden

**Comment by vinaooo** [comment]
https://developers.google.com/identity/smartlock-passwords/android/

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
