### ISSUE TITLE
ios null ptr access and sigabrt

### ISSUE THREAD

**Issue by irwincong** [bitwarden/mobile#2294]
### Steps To Reproduce

1. Open saved item in bw mobile app
2. Navigate to other app
3. Wait a bit
4. Navigate back to bw mobile app

### Expected Result

bw mobile app to not crash. 

### Actual Result

Mobile app crashes. 

```
{"app_name":"BitwardeniOS","timestamp":"2023-01-13 10:17:08.00 -0500","app_version":"2022.11.0","slice_uuid":"2713eb59-22cf-3b8d-9852-e6dceda3bf5e","adam_id":"1137397744","build_version":"2680","platform":2,"bundleID":"com.8bit.bitwarden","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.2 (20C65)","roots_installed":0,"name":"BitwardeniOS","incident_id":"CE81DE26-3C0C-4062-95CD-7B2FFA092CB4"}
…
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGABRT","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
…
```

### Operating System

iOS

### Operating System Version

16.2

### Build Version

Version: 2022.11.0 (2680)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I notice you are still running our previous version (2022.11.0), I would suggest you perform a clean reinstallation (uninstalling the application, resetting your device -power Off/On- and reinstalling) with our latest version (2023.1.0).

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists after the reinstallation, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
