### ISSUE TITLE
No auto-fill on most apps after 2023.01 update

### ISSUE THREAD

**Issue by Acharab** [bitwarden/mobile#2302]
### Steps To Reproduce

1 click on password or email input
2. Only the password or the email ar auto-filled and not both 

### Expected Result

To both auto-fill the Password and email or username field

### Actual Result

Only one the email or the password is showm

### Operating System

Android

### Operating System Version

13

### Device

Google pixel 7 pro

### Build Version

13

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there!

I attempted to reproduce your issue and was unable to do so. Please make sure you enable all the available autofill services on your Android device: https://bitwarden.com/help/auto-fill-android/#setup-auto-fill

If they are already enabling, consider disabling and enabling them again to refresh the options.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
