### ISSUE TITLE
[Android] App stuck at “Logging in…” after entering the password

### ISSUE THREAD

**Issue by meenbeese** [bitwarden/mobile#2306]
### Steps To Reproduce

1. Go to Android app
2. Enter email
3. Enter master pass (is correct, I checked)
4. “Logging in…” is displayed, but it never stops and doesn’t log me in

### Expected Result

I want the app to log in as I have always done before.

### Actual Result

Both my email address is correct but I cannot log in.

### Additional Context

Log in stopped working after the 2023.1.0 update.
I tested on Windows and iOS and they are unaffected.

### Operating System

Android

### Operating System Version

12

### Device

Redmi Note 10 Pro

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarsCandyBars** [comment]
Greetings,

Please restart your device and attempt to log in again. If that doesn't help, an uninstall/reinstall of the Android application may resolve the issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so that we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/). The issue here will be closed.
