### ISSUE TITLE
error occured 

### ISSUE THREAD

**Issue by rifqilubis** [bitwarden/mobile#2311]
### Steps To Reproduce

1. Go to 'bitwarden app Android'
2. Click on '+ button'

create username and regenerate password like usual. press save, then error will be occured 

### Expected Result

![Screenshot_2023-01-20-18-02-09-02_edf9c6c5202cf0aae90965d36a8e7fc4](https://user-images.githubusercontent.com/64082699/213687284-e7498259-107a-4875-93a0-22d67b6c7c4f.jpg)
![IMG_20230120_184240](https://user-images.githubusercontent.com/64082699/213687289-0c6c8877-04a9-48fe-9131-b1cf36bef277.jpg)

### Actual Result

![Screenshot_2023-01-20-18-44-19-71_edf9c6c5202cf0aae90965d36a8e7fc4](https://user-images.githubusercontent.com/64082699/213687591-6f661f1a-ccd3-4e97-be2b-4eb3b7349d7c.jpg)

### Screenshots or Videos

https://user-images.githubusercontent.com/64082699/213688352-e1883080-8aac-4d97-9496-086f27e21e5d.mp4

### Additional Context

this is the first time, i got an error.

### Operating System

Android

### Operating System Version

Android 12

### Device

realme narzo 20 pro

### Build Version

Version: 2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by joshtrichards** [comment]
Your video was definitely helpful, but I'm having a challenging time reproducing this.

Closest I got was blocking Internet connectivity on a phone... although the error message always had more details rather than being generic/blank like that (which is an issue in itself IMO).

Do you recall when you were last able to successfully add an entry or was this your first time adding an entry (wasn't sure if that's what you were referring to in your note)?

I'm also wondering if this was some weird semi-transient out-of-sync issue. Maybe force a Sync and, ideally, Log-out completely then back in (make sure you have your master password handy before doing so!)?

Also, can you confirm you can still add a similar entry via the web client (i.e. https://vault.bitwarden.com/) successfully?

DISCLAIMER: I'm just a user and am not associated with BW

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I'm able to create new items in both my Android and iOS device.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by rifqilubis** [comment]
Yeah it already fixed. i wait for a few days and it worked. sorry for late reply.
