### ISSUE TITLE
Autofill puts password in email field for Walmart

### ISSUE THREAD

**Issue by CmplxAdSys** [bitwarden/mobile#2326]
### Steps To Reproduce

1. Go to Walmart.com on a mobile browser on Android (I'm using Brave)
2. Click on sign in on the upper right. A field for email address should appear on the next page
3. Click on the email address field and have bitwarden autofill it

### Expected Result

The saved email address for Walmart is filled

### Actual Result

The password for Walmart is filled

### Additional Context

Using Brave 1.47.175

### Operating System

Android

### Operating System Version

12

### Device

Samsung Tab S6 tablet

### Build Version

Version: 2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by CmplxAdSys** [comment]
Just had the same thing happen on Brave browser for Best Buy and PayPal,too. Send like any sign on page that doesn't have the password field on the same page has this behavior.

**Comment by Adedamola-Aina** [comment]
Hi there, 

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
