### ISSUE TITLE
Bitwarden app autofills password in username field on Google 

### ISSUE THREAD

**Issue by thericle** [bitwarden/mobile#2341]
### Steps To Reproduce

1. Visit google.com on Chrome or Brave on Android (I haven't tried other browsers)
2. Try to log in to your Google account
3. When it asks for your email address, click to autofill with Bitwarden.

### Expected Result

 It should fill in the email address.

### Actual Result

 It fills in the password instead of the email address.

### Additional Context

This is not a new issue. I noticed it over a year ago.

### Operating System

Android

### Operating System Version

MIUI Global 12.5.14

### Device

Xiaomi Redmi Note 8 Pro

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment]
Hi there!
We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:
	•	mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
	•	browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform
In this case, we will go ahead and file an autofill report for you with the information you added here.
In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.
This issue will now be closed. 
Thanks!
