### ISSUE TITLE
Vault timeout not working

### ISSUE THREAD

**Issue by xehpuk** [bitwarden/mobile#2344]
### Steps To Reproduce

1. Open app
2. Unlock vault
3. Move app to background
4. Wait 15 minutes
5. Move app to foreground

### Expected Result

Vault is locked.

### Actual Result

Vault is not locked.

### Additional Context

- Vault timeout: 15 minutes
- Vault timeout action: Lock
- Unlock with biometrics: On
- Unlock with PIN code: Off
- Approve login requests: Off

### Operating System

Android

### Operating System Version

EMUI 12.0.0.144(C431E3R2P2patch01)

### Device

Huawei P30 Pro

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @xehpuk,

I attempted to reproduce your issue and was unable to do so on Android 12 with Bitwarden 2023.1.0. I would recommend that you test a fresh new installation; Please uninstall Bitwarden off your Android device, turn your device off (long press) and back on, install Bitwarden anew from the Google Play Store, and test that once more.
Please remember to activate all your Autofill services like so: https://bitwarden.com/help/auto-fill-android/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thank you.

**Comment by xehpuk** [comment]
EMUI 12 is some sort of Android 10, not 12.

**Comment by SergeantConfused** [comment]
Hi @xehpuk,

Could you please create a support ticket using this form (https://bitwarden.com/contact/) so we'll troubleshoot this? Please remember to include a link to this GitHub thread.


Thank you in advance,
