### ISSUE TITLE
Clear clipboard no longer works on Samsung

### ISSUE THREAD

**Issue by E9oReqJy3uvB8Vbnk6eJmP8kWLXPgqyIv3McRYZ** [bitwarden/mobile#2356]
### Steps To Reproduce

1. Enable Clear Clipboard
2. Copy a password from bitwarden
3. Optionally paste it somewhere else and wait for the time that was set for Clear Clipboard

### Expected Result

The clipboard should no longer have the password.
What used to happen on Samsung was that the password wasn't deleted but a new empty entry was added into the clipboard. This stopped the password from popping up whenever any text field was selected and could only be viewed by going into the clipboard.

### Actual Result

Nothing changes in the clipboard. If you now go to any text field such as in the browser, the keyboard shows the last thing that was in the clipboard which will now be a password or TOTP token etc. This creates a risk of it accidentally showing up if you forget to clear your clipboard.

### Screenshots or Videos

Can't provide screenshot as it contains sensitive information.

### Additional Context

I think this problem may have been caused by the change #2220.
If i understand correctly, Samsung uses its own clipboard which the `clipboardManager.ClearPrimaryClip()` function does not work on.
You may be able to replace [line 17](https://github.com/bitwarden/mobile/blob/master/src/Android/Receivers/ClearClipboardAlarmReceiver.cs#L17) in ClearClipboardAlarmReceiver from
`if ((int)Build.VERSION.SdkInt < 33)`
to
`if (Build.MANUFACTURER == "samsung" || (int)Build.VERSION.SdkInt < 33)`
but i am not sure.

### Operating System

Android

### Operating System Version

13

### Device

Samsung Galaxy Z Fold4

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. This is related to how Android on Samsung devices operates; The operating system itself keeps a record of data that was injected into the clipboard, even if that data has since been removed from the clipboard. This is not an aspect of the operating system which Bitwarden can control, and it's up to the vendor to potentially make the necessary changes and possibly allow deactivating that function.

Due to this, I will now close this GitHub report. If anyone has any questions or concerns, please feel free to [get in touch with us](https://bitwarden.com/help/), and please include a link to this GitHub report if you do so.

Thank you all again,

**Comment by DobbyAHouseElf** [comment]
Hey @SergeantConfused,
I am aware that the clipboard can't be cleared on the Samsung keyboard but i still think the old behaviour was better than what happens now. It used to add a new entry which was blank into the clipboard which hides the password when the keyboard opens but doesn't remove it from the clipboard history so can still be viewed if the clipboard button is pressed. Currently, the password is visible any time the keyboard opens until the X is pressed to hide it. The original comment has more details on this.

Is using an approach where a new empty entry is added before clearing the clipboard not an option that would be considered? This would allow the clipboard to be cleared on keyboards that support it and hide it on keyboards that don't unless someone intentionally goes in to the clipboard history.
