### ISSUE TITLE
Can't Login Or Edit Items Android 9 Version 2023.1.0

### ISSUE THREAD

**Issue by PaidThaFossToBeDaBoss** [bitwarden/mobile#2360]
### Steps To Reproduce

1. Go to Android App (Version 2023.1.0).
2. Click on 'Log In'. 
3. If you are not logged in you get "An error occurred". 
4. If you are logged in from a previous app version you can't edit any items. 
5. If you are logged in from a previous version you can still use the auto fill feature. 

### Expected Result

To be able to log in or if you are already logged in to be able to add, delete or change entries. 

### Actual Result

You either can't log in getting the error message: "An error occurred " or if you are logged in from a previous version you can't make any changes to the entries. 

### Additional Context

I realised this is an issue of the app and not my password because I could log in both on the web vault and the browser add on with the same password I was using on the app (copy paste). After downgrading to the previous version of the app (2022.11.0) I could log in and edit my entries normally. 

### Operating System

Android

### Operating System Version

9 (Pie)

### Device

Sony Xperia XZ Premium 

### Build Version

2023.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by PaidThaFossToBeDaBoss** [comment]
Before downgrading I tried almost everything I could think. Clearing the cache and data of the app, uninstalling the app and reinstalling it, installing the F-Droid version, changing Wi-Fi, restarting my device, restarting my Wi-Fi router, disabling my adblocker & local VPN, turning off 2FA, lowering the number of iterations. Nothing worked. Only downgrading solved this issue.

**Comment by atjbramley** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in our security features, as described here:

https://bitwarden.com/help/unusual-traffic-error/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by jawz101** [comment]
My phone gives an error that the operation was cancelled when I set the iterations to 600,001
