### ISSUE TITLE
Android app does not recognize subscription status for child account, will not show TOTP codes

### ISSUE THREAD

**Issue by sonic331va** [bitwarden/mobile#2385]
### Steps To Reproduce

1. Be a child member of an active and current family subscription with no access to subscription settings in the account section of the web vault. (Not the primary subscription holder/manager.)
2. Add TOTP code generation to a vault item.
3. Save the vault item and view it.

### Expected Result

The android app will show the new TOTP code every 30 seconds for the vault item to which it was added when it is viewed.

### Actual Result

The android app states that a premium membership is required to view TOTP codes.

### Additional Context

Resyncing the vault, locking/unlocking, logging out/logging in, clearing app data, and uninstalling/reinstalling the app produces the same result. The account in question is over 3 months old - age should not be a factor in this case. The Windows desktop app and Chrome browser extension both work with TOTP codes as expected using the same child account.

### Operating System

Android

### Operating System Version

13

### Device

Samsung Galaxy S23 Ultra

### Build Version

2023.1.0 (5786)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @sonic331va,

Thank you for this report. I am unable to reproduce this behaviour; Could you please create a support ticket (https://bitwarden.com/contact/) so we'll troubleshoot this together? Please also include a link to this GitHub thread in your message.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you again.
