### ISSUE TITLE
Distinguish the difference between numerical and alphabetical characters

### ISSUE THREAD

**Issue by JAGFin1** [bitwarden/mobile#24]
Would it be possible to colourise or somehow distinguish the difference between letters and numbers when showing the password? The monospace font works very well 99% of the time but it is incredibly hard to tell the difference between a zero and the capital letter O. 

I don't consider this a bug, rather a very mild peeve.

**Comment by kspearrin** [comment]
Good idea.

**Comment by sreich** [comment]
Probably a better font needs to be chosen. 

There are plenty of good open source fonts that distinguish entirely between ambiguous glyphs. 

Colorizing isn't a good idea as you'd need a legend, and many people are color blind (it's bad accessibility to have a feature depend on a person's ability to read color)

**Comment by timdvail** [comment]
When I researched monospaced fonts my favorite common one regarding differentiating characters was Apple new front Menlo which is actually based on open source deja vu sans mono but has slashed instead of dotted zero. Meslo in turn is based on menlo which is what I use as my monospace font in my home computer in terminals and text editors. In any case 5 and S and ! l I | are other characters I check when evaluating fonts.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
