### ISSUE TITLE
Cannot connect self-hosted server

### ISSUE THREAD

**Issue by jcrovetti** [bitwarden/mobile#2400]
### Steps To Reproduce

1. Open android app parameters
2. Type in your self-hosted server URL
3. Save
4. Try to login

### Expected Result

I expect to be prompted for password

### Actual Result

The connection fails with message "Operation was canceled" after about 40 to 60 seconds

### Additional Context

I have checked my server logs : no requests are reaching the server (nothing in Nginx Proxy Manager or int bitwarden logs)
So after that I tried to check outgoing trafic from my phone with PCAPdroid and that's where it got strange : when the packet capture is running, I can connect.
I have no idea what is going on.
I tried on other android devices (different brand, different version of android), same problem.

### Operating System

Android

### Operating System Version

10

### Device

Galaxy note 9

### Build Version

2023.2.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by DenisKnez** [comment]
For easier debugging next time please include more info about where your self hosting your bitwarden server do you use static ip or dynamic dns and things like that because that really matters when you have connection issues to it.

PCAPdroid claims that they simulate a VPN but don't use a remote VPN server. That means that the simulated VPN probably by passes some restrictions by your server. Maybe you have some firewall rules.

Try to connect to a 4G/5G network (of course turn off wifi on your phone) and then try to login. If you're able to connect over 4G then it's highly like some miss configuration bug on your end and not a bug. But again it is highly dependent on how are hosting your bitwarden server. And are you able to connect to your bitwarden server on the web client?

**Comment by jcrovetti** [comment]
Hi,
Thanks for the feedback.
As for the hosting info, it's in my homelab, behind a router/isp box with a static public IP. I have a real domain name pointing to it, no dynamic ip resolver.

I do not think the problem was on the server side : i can access the web interface and the web browser plugin works ok.

But anyways, it seems to have resolved itself overnight. I really cannot explain what happened sinc it works fine now, on the three android devices I tested yesterday.

Sorry for reporting something that does not seem related to the mobile app.

And thank you again for the help.
