### ISSUE TITLE
Android Watch integration

### ISSUE THREAD

**Issue by patschi** [bitwarden/mobile#241]
Quite similiar issue like #76, but wishing a simple, cool integration with Android Watch instead. In the first place a feature for getting TOTP PINs easily on the watch would be cool, like how [Authenticator Plus](https://play.google.com/store/apps/details?id=com.mufri.authenticatorplus) offers: 

![image](https://user-images.githubusercontent.com/2029878/34583381-e0a581d0-f197-11e7-8871-a13ec25b52bd.png)

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
