### ISSUE TITLE
US Bank Application will not autofill on Android

### ISSUE THREAD

**Issue by makitso** [bitwarden/mobile#2416]
### Steps To Reproduce

 I have both the Wells Fargo and US Bank Android apps installed on my Android tablet.  When I launch the Wells Fargo app it autofills correctly.  However, if I launch the USBank application no autofill.  I have set the URI to what is defined in the Google Play Store.  I have tried different URIs, com.usbank.mobilebanking and androidap://com.usbank.mobilebanking but nothing works.
I have tried the same thing on my Google 6a phone with same results. 

### Expected Result

Autofill works

### Actual Result

Autofill does not work

### Operating System

Android

### Device

Google 6a and Samsung Table

### Build Version

Android version 2023.2.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @makitso, 

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different forms depending on the platform:

For mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

For the browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, I have gone ahead and filed an autofill report for you with the information you provided.

In the future, if you encounter a webpage or an application that doesn't autofill as expected, please feel free to use the relevant form directly.

This issue will now be closed. 

Thank you.
