### ISSUE TITLE
Bitwarden thinks it is opening an app instead of a website

### ISSUE THREAD

**Issue by ViktorKahu** [bitwarden/mobile#2433]
### Steps To Reproduce

1. Open internet browser (in my case the dev branch of Bromite)
2. Navigate to any website requiring a log on and password (foe example github).
3. Use autofill
4. Receive a message: there are no stored elements for org.bromite.bromite.dev

### Expected Result

For bitwarden to fetch the logon and password details of the website (not the app package).

### Actual Result

There are no stored elements for org.bromite.bromite.dev

### Additional Context

It has been confirmed that other passwerd managers (keepass dx) work correctly in the above scenario, hence bug is with Bitwarden and not my browser.

### Operating System

Android

### Operating System Version

Android 13 GrapheneOS

### Device

Pixel 7 Pro

### Build Version

2023.3.0 (6070)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @ViktorKahu, 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.  

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by rootinchase** [comment]
This issue is affecting me as well.

When using the dev version of Bromite (org.bromite.dev), and I attempt to login to anything using bitwarden, it gets treated as an app, not a browser.

Here is the versions that aren't working: [https://github.com/uazo/bromite-buildtools/releases](https://github.com/uazo/bromite-buildtools/releases)

**Comment by djsmith85** [comment]
Related to https://github.com/bitwarden/mobile/pull/2491
