### ISSUE TITLE
[Android autofill] Auto-select entry if it is the only one

### ISSUE THREAD

**Issue by Ndr6** [bitwarden/mobile#244]
If you have only one password entry with a corresponding androidapp:// URI and try to autofill in this app, the app could automatically select the entry after authenticating, skipping the "Items for com.androidapp" screen.

**Comment by quthla** [comment]
Same für ios please @kspearrin

**Comment by EddHub** [comment]
Yes, please!

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
