### ISSUE TITLE
Cannot login and save/edit files

### ISSUE THREAD

**Issue by Moat6** [bitwarden/mobile#2442]
### Steps To Reproduce

Cannot login and save/edit files

### Expected Result

Files are not saving as they should be and now I just freshly installed the app and cannot login too

### Actual Result

There is a prompt  and it says "An error has occurred."

### Screenshots or Videos

![Screenshot_20230324-235104](https://user-images.githubusercontent.com/113278199/227608462-ed640979-1fa7-4574-9d08-e2cea38b804a.png)
Couldn't take full screenshot due to security policy.

### Additional Context

I was not able to save/files new files. Then I updated it to the latest android version 2023.3.1  but it was still not working.  I tried unistalling it and now I am not able to login too..

### Operating System

Android

### Operating System Version

Android 12

### Device

Samsung galaxy m31

### Build Version

2023.3.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. The issue could be related to our security mechanisms and protocols, are you using a VPN, Tor, or proxy? You may wish to disable these temporarily and then try again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
