### ISSUE TITLE
The camera is stretched when scanning for QR codes to set up TOTP

### ISSUE THREAD

**Issue by FaviFake** [bitwarden/mobile#2448]
### Steps To Reproduce

1. Open a login
2. Click on "Set up TOTP"
3. See error

### Expected Result

The camera view is not stretched

### Actual Result

The camera view is stretched

### Screenshots or Videos

https://user-images.githubusercontent.com/86537048/227742136-2c5ff612-4070-48c8-b8c4-411b850f0708.mp4

### Additional Context

See the video recording

### Operating System

Android

### Operating System Version

Android 12

### Device

Samsung Galaxy A72

### Build Version

Version: 2023.2.0 (5944)

### Beta

- [x] Using a pre-release version of the application.

**Comment by joshtrichards** [comment]
Possibly related (and still open) #1130

**Comment by SergeantConfused** [comment]
Hi @FaviFake and @joshtrichards,

Thank you. I'm going to close this thread for now in order to consolidate this topic here (https://github.com/bitwarden/mobile/issues/1130); If you have anything else you'd like to add, please feel free to do so in that thread.

I thank you in advance for your understanding.
