### ISSUE TITLE
Auto-fill is broken with Pokémon GO in v2023.3.2

### ISSUE THREAD

**Issue by Fai1edMit0sis** [bitwarden/mobile#2469]
### Steps To Reproduce

1. Go to apps
2. Open Pokémon GO
3. Wait for it load
4. Tap on Trainer Club

### Expected Result

The prompt shows up to auto-fill in the credentials.

### Actual Result

The prompt doesn't always show up, and when it does, tapping on the credentials doesn't fill them in.

### Screenshots or Videos

![Screenshot_20230412_235637_Pokmon GO - Copy](https://user-images.githubusercontent.com/21115188/231647161-5eacf75f-105e-45c1-aece-86abfd69e83a.jpg)

### Additional Context

Uninstalling and re-installing doesn't fix the issue.

### Operating System

Android

### Operating System Version

13

### Device

Samsung A51

### Build Version

2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by c1-jack** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
