### ISSUE TITLE
Does not enter password in Openkeychain via Fairmail

### ISSUE THREAD

**Issue by ntelogo** [bitwarden/mobile#2470]
### Steps To Reproduce

1. Go to Fairmail
2. Open encrypted email
3. Click on decrypt (Openkeychain pop up appears)
4. Select password from Bitwarden dropdown

### Expected Result

Password is copied in the password field

### Actual Result

Password is not copied in the pass field

### Operating System

Android

### Operating System Version

12

### Device

Poco X3 NFC

### Build Version

SKQ1.211019.001

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @ntelogo !

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

    mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

    browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by atjbramley** [comment]
Hi @ntelogo - in order to let me complete the Autofill report for you, could you please let me know the following:

- Are you using the Autofill Service?
- Have you enabled Inline Autofill?
- Have you enabled 'Use Accessbility'?
- Are you using Draw-Over?
- What Bitwarden App version are you using?
