### ISSUE TITLE
An error has occured

### ISSUE THREAD

**Issue by aarshps** [bitwarden/mobile#2477]
### Steps To Reproduce

1. Go to Bitwarden Android app and login
2. Click on an of the already saved record
3. Scroll down to anywhere and update any record value
4. Click on save

### Expected Result

The record needs to be saved with the expected updated value

### Actual Result

Error is being thrown

### Screenshots or Videos

![Screenshot_20230415-224945](https://user-images.githubusercontent.com/11371727/232242267-33eb0eac-5411-414c-864a-64412171fd54.png)

### Operating System

Android

### Build Version

2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hello there, 

When you get that error, do you have an active and working Wi-Fi connection? You need either a cellular or Wi-Fi connection to connect to the app, but it does not have to be cellular specifically. You could reboot your modem / router, then test again to see if that provides any relief? Also, what happens if you test on a different Wi-Fi network or over LTE as well? 

Another question, did you have an active VPN connection or any other special network configurations when attempting to connect? Sometimes those can interfere and the login can be canceled. Could you try temporarily disabling them and try again to login?

As an additional step, could you log into the Web Vault (https://vault.bitwarden.com) and go to Settings > My Account. Scroll to the bottom of the page and select Deauthorize Sessions, then wait a few minutes and try to log in again with your phone.

If you are still unable to login after these suggestions, please note the exact time when you see this error and share the timestamp with us (don't forget to note your timezone) along with your IP address (you can search for the term "what is my IP address" on Google, DuckDuckGo or your preferred search engine).

**Comment by aarshps** [comment]
Disable sessions worked. Thanks. 👍

Thanks & Regards
Adarsh (Aarsh) Ps
