### ISSUE TITLE
master password field emptied automatically  after typing password in retype master password field for ios device 

### ISSUE THREAD

**Issue by Sundar1709** [bitwarden/mobile#2483]
### Steps To Reproduce

1. Go to the application
2. Click on 'Create account
3. Scroll down to gmail account
4. give a password in master password
5. type previous in retype master password field 

### Expected Result

master password field should not be emptied while putting password retype master passowrd field 

### Actual Result

it  is getting emptied

### Operating System

iOS

### Operating System Version

15.3.1

### Device

IPhone 13

### Build Version

000

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @Sundar1709,

Thank you for following up on this. I tested this on iOS 16.5 with Bitwarden 2023.4.0, and whilst attempting to create a new Bitwarden account via the iOS client, neither the (Master password) field nor the (re-type master password) field were emptied. I recommend that you start with a fresh installation; Please uninstall Bitwarden off your iOS device, turn your device off (long press) and back on, install Bitwarden anew from the Apple App Store, and give that another try. If you encounter the same behaviour, please feel free to create a support ticket (https://bitwarden.com/help/) so we'd troubleshoot this together; Please also include a link to this GitHub report.

Alternatively, you can seek assistance from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you again,
