### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by fxzxmicah** [bitwarden/mobile#2493]
### Steps To Reproduce

Just open it.

### Expected Result

opened

### Actual Result

crashed

### Screenshots or Videos

![IMG_20230424_222131](https://user-images.githubusercontent.com/48860358/234026117-31a49b9b-359d-44f5-ad1f-859504cfae1d.jpg)

### Operating System

Android

### Operating System Version

10

### Build Version

2023.3.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @fxzxmicah,

Thank you for your report. Could you please create a support ticket (https://bitwarden.com/help/) and include a link to this GitHub report and mention what is the make and model of your phone and to what language is the interface set? I ask because I am unable to reproduce this behaviour, and I'd like to proceed and assist in troubleshooting it.

We use GitHub issues as a place to track bugs and other development related issues; The issue here will be closed.


Thank you again,
