### ISSUE TITLE
Android app close does not lock vault

### ISSUE THREAD

**Issue by Pee-Jey** [bitwarden/mobile#2514]
### Steps To Reproduce

1. Open android app
2. login (or unlock) vault
3. Close app in normal way (i.e. usual android swipe up)
4. Open app (within configured vault timeout period)

### Expected Result

On reopening the app I'd expect it to be either logged out or locked

### Actual Result

The app opens with the vault unlocked - maybe this is by design but it is not intuitive and I only found out by accident

### Operating System

Android

### Operating System Version

11

### Device

Oukitel WP12 Pro

### Build Version

2023.4.0 (6203)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so in both the past versions nor the latest version of the Android application. Does restarting your device or reinstalling the application help resolve the issue?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
