### ISSUE TITLE
Android - “an error has occured”

### ISSUE THREAD

**Issue by zarathustra19** [bitwarden/mobile#2516]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Cannot save or edit items on vaults. 

### Actual Result

Cannot save or edit items on vaults. When i trying to add new items on login vaults and press SAVE says: “an error has occurred”.
Same happens on secure notes too.

### Additional Context

Cannot save or edit items on vaults. 

### Operating System

Android

### Operating System Version

Android 13

### Build Version

2023.4.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by micodls** [comment]
I am encountering the same issue. Tried the following:
- clearing the cache
- reinstalling the latest app from Google Play 
- connecting via different networks and mobile data

but shows "an error has occurred".

**Comment by zarathustra19** [comment]
hope devs will soon solves it with new updates.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a network issue.

Please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

The issue here will be closed.

Thanks!

**Comment by zarathustra19** [comment]
Thanks 🙏

Issue was resolved. Now i can access on vault from my phone.
