### ISSUE TITLE
Autofill broken

### ISSUE THREAD

**Issue by jdpottle** [bitwarden/mobile#2518]
### Steps To Reproduce

Opening any page requiring password

### Expected Result

Icon should appear to launch bitwarden to allow selection of correct site. Username and Password should autofill 

### Actual Result

the BitWarden icon appears above the keyboard like normal. However, clicking on it does not open the app. If I launch the app manually and log in, then return to the page, I see suggested matching sites but clicking any of them does nothing, no autofill.

### Operating System

Android

### Operating System Version

14 beta, upside down cake

### Device

Pixel 6

### Build Version

UPB2.230407.014

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @jdpottle ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.  Please perform a clean re-install, and then setup autofill again on your device from scratch using the guides here:

https://bitwarden.com/help/auto-fill-android/
https://bitwarden.com/help/auto-fill-android-troubleshooting/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by miaojs** [comment]
I am also having this issue on Android 14 beta and Chrome. None of the bitwarden buttons do anything in Chrome on Android 14. Works fine in Firefox and other apps.

**Comment by ThomasOrlita** [comment]
Can confirm this in Android 14. Turning "Allow display over other apps" make autofill work again.
