### ISSUE TITLE
Auto Fill and Save hangs on Android

### ISSUE THREAD

**Issue by Aimhere2k** [bitwarden/mobile#2532]
### Steps To Reproduce

This happens when I attempt to use Bitwarden to auto-fill a login prompt within another app for which I have a login saved, but not yet associated with the app by Bitwarden.

1. In any app with a login prompt, the "Auto-fill with Bitwarden" overlay/popup appears.
2. Tap "Auto-fill with Bitwarden.
3. Authenticate with Bitwarden.
4. Search for and locate the login I want to use for the other app.
5. Tap the login. I get the prompt "Auto-fill and save, auto-fill, cancel".
6. I want to associate this login with the other app, so I tap "Auto-fill and save".
7. Bitwarden displays the message "Saving..." with spinning circle, but never moves on from this.

### Expected Result

I expect BitWarden to save the association between the selected login and the third-party app, and return to the other app's screen so that app will proceed with the login process.

### Actual Result

Bitwarden remains on the "Saving..." message, and never returns to the other app.

### Operating System

Android

### Operating System Version

Android 13

### Device

Google Pixel 6a

### Build Version

2023.4.0 (6203)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I recommend uninstalling and re-installing the Bitwarden mobile app, and also restarting your phone. The Help Center has some additional information on general Android autofill troubleshooting here: https://bitwarden.com/help/auto-fill-android-troubleshooting/

If your issue persists, please contact Bitwarden support using our contact form so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
