### ISSUE TITLE
bitwarden android can't contact the server while on wired ethernet

### ISSUE THREAD

**Issue by RE-Specto** [bitwarden/mobile#2557]
### Steps To Reproduce

1. connect android phone with usb to ethernet otg adapter
2. wait until phone switches to using ethernet ("Ethernet cable is connected" notification)  
3. try saving anything in the vault of the Bitwarden app

### Expected Result

should work the same as wifi or cellular network

### Actual Result

stuck on `Saving...` for a while, then returns:
```
An error has occurred.  
Exception message: The operation was canceled.  
```

### Screenshots or Videos

Can't take screenshot due to security policy

### Additional Context

will provide on request

### Operating System

Android 12 (build N976BXXU8HVGA)
(stock samsung firmware)

### Device

Samsung Galaxy Note10+ 5G SM-N976B

### Build Version

2023.5.0 (6330)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by cbbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of your network settings or connection.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
