### ISSUE TITLE
Top panel does not respond in Android

### ISSUE THREAD

**Issue by noamgot** [bitwarden/mobile#2587]
### Steps To Reproduce

1. Open the app
2. Click on the magnifier or the ellipsis (three dots)
3. (no response)

Notice that the whole top panel does not respond, even on other screens - for example, if I press the "Login" button, on the new screen the "Go back" button does not respond

### Expected Result

Response :)

### Actual Result

No response :(

### Operating System

Android

### Operating System Version

10 (QKQ1.190828.002)

### Device

Xiaomi Pocophone f1

### Build Version

2023.5.0 (6330)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @noamgot ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a other apps installed on your phone - notably several either OEM or 3rd party blue light filters will display over the top of your app and prevent access.  Please try removing these, or configuring them to allow exceptions for Bitwarden.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
