### ISSUE TITLE
ByBit iOS app doesn't accept login

### ISSUE THREAD

**Issue by b4barrett** [bitwarden/mobile#2590]
### Steps To Reproduce

Please fix iOS ByBit app login, only can do password and not login field

### Expected Result

obvious

### Actual Result

no login field entry

### Operating System

iOS

### Build Version

latest

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @b4barrett !

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

    mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

    browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

Could you please go ahead and file an autofill report for the mobile client - I am afraid that I am not able to do this for you as more information is required.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by b4barrett** [comment]
So you tell me to do it one way then I have to do it another? How is it my
job to improve your product?
