### ISSUE TITLE
Whitelist Bromite browser fork

### ISSUE THREAD

**Issue by hj-collab** [bitwarden/mobile#2622]
### Steps To Reproduce

1. Install Bromite browser fork. https://github.com/uazo/bromite-buildtools/releases
2. Login into Bitwarden Vault in the android app
3. Visit any login page for which you have credentials stored in your vault.
4. Nothing will appear in the autofield and you will need to manually copy paste.

### Expected Result

Inline autofill will work in the Bromite browser fork

### Actual Result

Inline autofill does not work in the Bromite browser fork

### Additional Context

There is a pull request to fix this issue pending. Please merge it at the earliest. https://github.com/bitwarden/mobile/pull/2491

### Operating System

Android

### Operating System Version

13

### Build Version

2023.7.0 (6781)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests](https://community.bitwarden.com/c/feature-requests) section for submitting, voting for, and discussing requests like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

There also seems to be some discussion about name-changes in the linked issue, which will need to be updated in the community PR or replaced by another PR.

This issue will now be closed. Thanks!
