### ISSUE TITLE
Accessibility Keeps Getting Turned Off [Android]

### ISSUE THREAD

**Issue by rahaaatul** [bitwarden/mobile#2635]
### Steps To Reproduce

1. Turn on Accessibility.
2. Do something else.
3. Try to fill in your credentials 
but there's no option to do it because accessibility is turned off for Bitwarden.

### Expected Result

Bitwarden's accessibility should not be turned off. 

### Actual Result

Bitwarden's accessibility and autofill gets turned off.

### Screenshots or Videos

![Screenshot_2023_0721_164924](https://github.com/bitwarden/mobile/assets/86149861/4066449c-5a37-46b8-916c-b8d72f9b8a64)

### Additional Context

Note: **I whitelisted Bitwarden in Battery Optimization settings.**

My Solution is either:

- Add support for shizuku to keep the accessibility on.

or

- Add ADB permission "WRITE_SECURE_SETTINGS" to keep the accessibility on like FooView does.

Please, do something about it, because I have to turn on bitwarden's accessibility everytime I want to fill in the credentials automatically, otherwise I have to do it manually one by one.

### Operating System

Android

### Operating System Version

11

### Device

Vivo Y20 2021

### Build Version

2023.7.0 (6781)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @rahaaatul ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a conflict with other software on your device.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by rahaaatul** [comment]
How can you close this as completed? I am genuinly facing this problem for months. 

> I attempted to reproduce your issue and was unable to do so.
Possibly because your device is better or different than mine. And not all device are the same.

> I think your error could have its origin in a conflict with other software on your device.
How can other software disable bitwarden's accessibility? And if that really does, is the solution to not use the other app? I don't install any app I don't need.

I'm sorry but I'm upset that the issue got closed without investigating it further. @atjbramley

**Comment by atjbramley** [comment]
Hi @rahaaatul,

We use GitHub issues as a place to track bugs and other development related issues.  We do not offer tech support via Github.  If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

We can re-open the issue if necessary after we have helped you via our Tech Support team.

We look forward to receiving your email.

**Comment by i8degrees** [comment]
Operating System
Android

Operating System Version
13 (TP1A.220624.014)

Device
Google Pixel 4XL

Build Version
2024.10.2

Hi,

I, too, am plagued by this same issue. It has been driving me crazy for months now!

I have recently discovered that this occurs exactly in line with when my Bitwarden Vault is set to lock after X minutes. In my instance, this is set to `4hrs`. I am now testing with it set to **On App Restart**. In theory, this should only occur upon a reboot, which only happens every few days for me generally speaking. I feel as though this is rather extreme measure to take, but something has got to give here.

I believe that this issue only started happening when the mobile app was updated to use native Android APIs -- roughly about August, 2024.

My apologies for filing this bug report on a closed ticket. I shall also be contacting you via the provided contact link. Thank you

**Comment by Bertybassett99** [comment]
I experience the same problem. I turn on the accessibility option. Then after a while it turns off. This completely spoils the point of bitwarden.

**Comment by frankbonatelli** [comment]
Still happening
To say it is locally occurring on only the one device is a weak response from what I hoped was a global class firm.
Yes it is occurring on this device. Yes it is occurring on my second device yes it's occurring on my third device oh and wait I have a forth.
Google pixel fold brand new yep it is a constant struggle
Samsung Galaxy fold 5 5g yup here too
Tripletek tablet 7 inc you guessed it here as well
Tripletek tablet 9 inch pro and here

So what is the real issue is it the user that's lame the user has tried meant different apps for this very task and only this one has this issue. 
Each device has different OS version
Each device has varying hardware specs
One is fully rooted 
The rest are all in as new from factory states.

Clearly not the user/device.

I'm a long time user of your app I'm a paid subscriber to your app I've quietly worked around it for too long now. Let's fix this issue please.
