### ISSUE TITLE
Unlock with Biometrics doesn't work

### ISSUE THREAD

**Issue by NeeL21YT** [bitwarden/mobile#2636]
### Steps To Reproduce

If you go the the Android settings and select Unlock with Biometrics it says to input fingerprint.

### Expected Result

It should accept the fingerprint and allow me to login using fingerprint 

### Actual Result

Doesn't save the fingerprint. It thinks like the scanner is not there

### Screenshots or Videos

Can't take screenshots due to restrictions 

### Operating System

Android

### Operating System Version

Android 13

### Device

Realme 9 5G Speed Edition 

### Build Version

Version: 2023.7.0 (6781)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment]
Hi @NeeL21YT 

I attempted to reproduce your issue and was unable to do so. this could be due to misconfiguration or issues with the bitwarden app. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
