### ISSUE TITLE
Whitelist Cromite browser 

### ISSUE THREAD

**Issue by Bahasnyldz** [bitwarden/mobile#2639]
### Steps To Reproduce

1. Open Cromite
2. Visit any website that requires a login and password,
3. Use Bitwarden Autofill
4. Bitwarden opens and It shows org.cromite.cromite instead of website

### Expected Result

Url of the site should appear.

### Actual Result

Just shows org.cromite.cromite

### Additional Context

Cromite is fork of bromite by uazo one of the maintainers of bromite.

### Operating System

Android

### Operating System Version

Android 10

### Device

Huawei P30 Lite 

### Build Version

2023.7.0 (6781)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests](https://community.bitwarden.com/c/feature-requests) section for submitting, voting for, and discussing requests like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by djsmith85** [comment]
@Bahasnyldz: Thank you for your contribution. I have seen and linked your PR with this issue, but as this issue is just for requesting the feature, I'm closing it.

**Comment by avipars** [comment]
Any progress?
