### ISSUE TITLE
cant login to android app

### ISSUE THREAD

**Issue by mattheartman** [bitwarden/mobile#2649]
### Steps To Reproduce

1. downloaded app from play store and attempt to login.
2. add correct email address of account
3. add correct password
4. screen changes to chrome browser with captcha.
5. correctly do the captcha test
6. when done screen goes blank
7. return to bitwarden app
8. back to step 2.

### Expected Result

i expected to login to my account

### Actual Result

I was sent to chrome to do a captcha test. when done I was not returned to the app but a blank page in chrome. i opened up bitwarden again and had to do the process again. this kept cycling thought the same uneventful routine.

### Operating System

Android

### Operating System Version

color os 13 (android 13)

### Device

OPPO A16s

### Build Version

2023.7.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MGatasa** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the Chrome browser/profile settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
