### ISSUE TITLE
Autofill on Samsung Internet Browser stopped working on all devices

### ISSUE THREAD

**Issue by SgtChrischi** [bitwarden/mobile#2658]
### Steps To Reproduce

1. Install Samsung Internet Browser (Beta).
2. Install Bitwarden and set it up
3. Visit any website and try to login.

### Expected Result

The autofill works and shows bitwarden content.

### Actual Result

The autofill does not work and does not show bitwarden content.

### Additional Context

Since a few days the Bitwarden Autofill stopped working with the Samsung Internet Browser. Both with the normal version and with the beta version. It always worked without any problems and now it doesn't work on any of the mentioned devices anymore. It still works with all other apps and browsers, only "Samsung Internet" and "Samsung Internet Beta" are affected. Various settings of the autofill in Bitwarden were tested.

### Operating System

Android

### Operating System Version

Android 12/One UI4.1 & Android 13/OneUI 5.1

### Device

Galaxy S10+, Galaxy Tab S8+, Galaxy S23 Ultra

### Build Version

2023.7.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of system settings that can affect auto-fill. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Catdoggy** [comment]
Can confirm, too. Bitwarden works for month, since latest update from samsung internet, BUT not immediately, but only after I (due to other problems) in the app "samsung internet" deleted the cache and data - no longer a function of bitwarden. With all other popular browsers there are no problems!

**Comment by lukewarmcustard** [comment]
I do indeed use nextdns will make some adjustments and see if this helps to resolve it.
Well spotted!

**Comment by lukewarmcustard** [comment]
@SgtChrischi  Are you using accessibility with Bitwarden?

**Comment by Catdoggy** [comment]
@SgtChrischi, wow, great.... I use dns too (adguard). After deactivating and clearing app data, everything works. Respect and many thanks for your help 🤝

**Comment by Yohan-Janolin** [comment]
@SgtChrischi, thank you so much!! Your solution works perfectly (with AdGuard).
