### ISSUE TITLE
feature request: allow both PIN and fingerprint unlock at same time

### ISSUE THREAD

**Issue by ElTopo** [bitwarden/mobile#269]
Right now "Unlock with Fingerprint" and "Unlock with PIN code" are exclusive to each other. Can we have both options enabled and either one of them can unlock the app? Normally I use fingerprint but it's not convenient when I have gloves on.

I like the way Norton App Lock does: it shows PIN unlock screen with fingerprint, and I can unlock either by using PIN or by fingerprint.

![screenshot_20180128-132836](https://user-images.githubusercontent.com/217195/35487382-cf9f749a-042f-11e8-86a3-ec0b76ffef44.png)

**Comment by BigNickBurgess** [comment]
Great idea and would fulfill my request here pretty much for if fingerprint failed

https://github.com/bitwarden/mobile/issues/176

**Comment by Daptonic** [comment]
This would be helpful for times when picking up the phone isn't convenient as well.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
