### ISSUE TITLE
Upgrade Error Fdroid: Hash not matching

### ISSUE THREAD

**Issue by babushanaelsa** [bitwarden/mobile#2726]
### Expected Result

Updating via Fdroid Client Works

### Actual Result

Does not work, hash of the previous version does not match with the most recent

### Operating System

Android

### Build Version

2023.7.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by babushanaelsa** [comment]
![IMG_20230826_111617](https://github.com/bitwarden/mobile/assets/122382732/5de4196b-8a79-4aae-9848-511b5230da99)

**Comment by Sanjay451** [comment]
I facing this issue right now. I tried to update the app using driod-ify, since then I am unable to update. Not able to update from f-droid and droid-ify right now.

**Comment by Lwfrancisco** [comment]
Doesn't add much to the discussion - but it also does not work on Neo Store (just another fancy client for Fdroid repos)

**Comment by unoukujou** [comment]
Same problem here. Hash check failed.

**Comment by babushanaelsa** [comment]
This is not a new thing, every second update...just takes time for Fdroid to fetch the new APK

**Comment by unoukujou** [comment]
> This is not a new thing, every second update...just takes time for Fdroid to fetch the new APK

I'll try it again later, thanks. But just because it isn't a new thing, doesn't make it any better. 😄 In fact, I'd say that makes it even worse. Obviously it's not something that's normal or acceptable? Needs to be fixed, no? Made me think somebody modified the apk from what was originally released. Next time it could be malware, but "it's normal". Know what I mean? 👍

**Comment by babushanaelsa** [comment]
Update via Fdroid worked, I close this issue.
