### ISSUE TITLE
app crash when using auto-fill with items that has master password re-prompt

### ISSUE THREAD

**Issue by Nonanne** [bitwarden/mobile#2728]
### Steps To Reproduce

1. go to any sites
2. click to use auto-fill service when detected by bitwarden
3. choosing item that master password re-prompt enable
4. typing my master password and click submit
5. app showing error message (Screenshot - 1)
6. can't choosing same item anymore

also
1. doing same as above (1. - 2.)
2. searching for item by search function
3. same as above (3. - 4.)
4. app crash with no error message

### Expected Result

when typing master password and click submit, it should auto-fill success with no error message or app crash

### Actual Result

as I says above

### Screenshots or Videos

Screenshot - 1
![Screenshot_20230829-001912](https://github.com/bitwarden/mobile/assets/94383254/ca4ae9c6-1920-4574-aeb4-4aca32e7e9ec)

> this one is error message when I click submit. In black screen cuz I did't allow screen record in bitwarden app.

### Operating System

Android

### Operating System Version

Android 13 (Aug 2023)

### Device

Xiaomi Mi9

### Build Version

2023.8.0 (7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Let's try a few things to see if they help resolve the issue:

1) Please first log in to https://vault.bitwarden.com to make sure that you know your master password so you will not be locked out.
2) Clear your cache and cookies on both your browser and Bitwarden app.
3) Restart your device.
4) Retry and see if the issue is resolved.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
