### ISSUE TITLE
Android - Can't login. Stuck on Captcha page.

### ISSUE THREAD

**Issue by wesley-prado** [bitwarden/mobile#2742]
### Steps To Reproduce

1. Open the app
2. Fill the email and password
3. Press to enter with master password
4. Solve the captcha that opens in the browser.

### Expected Result

Login the app

### Actual Result

Stuck on captcha page. Infinite loading the session.

### Additional Context

After the app opens the Captcha page and it's solved, nothing happens. There's no redirect and the app stays on infinite loading session.

### Operating System

Android

### Operating System Version

12 (Snow Cone)

### Device

Moto G60

### Build Version

2023.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of system settings or default browser.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
