### ISSUE TITLE
BitWarden doesn't show up as an installable option for Autofill service in Samsung Secure Folder

### ISSUE THREAD

**Issue by mxxcon** [bitwarden/mobile#2765]
### Steps To Reproduce

1. Enable Secure Folder on Samsung device
2. Go into Secure Folder settings
3. Go into More Settings
4. Go into Autofill service
5. tap Add service

### Expected Result

BitWarden should be listed as one of the apps to install

### Actual Result

A bunch of apps are listed, but not BitWarden

### Screenshots or Videos

![Screenshot_20230912_211540_Google Play Store](https://github.com/bitwarden/mobile/assets/847140/c8cdf3d0-f85c-4b4b-9f61-f897785112c6)

### Additional Context

I do have BitWarden installed on my phone, but Samsung Secure Folder acts like an isolated environment/virtual device and it doesn't have access to apps unless I install them from play/samsung store into the Secure Folder or add them from the "main" phone into the Secure Folder.

### Operating System

Android

### Operating System Version

13

### Device

Samsung Galaxy S20FE

### Build Version

2023.8.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by mxxcon** [comment]
Actually, if you skip the whole Secure Folder and just go into regular Autofill settings and tap on "Add service", BitWarden is not listed there.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of your auto-fill settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by mxxcon** [comment]
The issue not that I don't have BitWarden listed as Autofill service.

The issue is that if I tap on "Add service" it opens a page from Google Play Store and BitWarden is not listed on that page. There's no configuration on my end, it's downloaded from Google.
