### ISSUE TITLE
Scan QR Code Camera Blurry

### ISSUE THREAD

**Issue by warrenlayson** [bitwarden/mobile#2767]
### Steps To Reproduce

1. Go to My Vault
2. Click on any Login Card
3. Click on Edit FAB
4. Click on Set up TOTP
5. Try scanning a QR Code

### Expected Result

Be able to actually scan the QR Code and setup TOPT without needing to type or copy-paste the security key to the browser extension (my workaround).

### Actual Result

The Camera was blurry and couldn't scan any QR Code

### Screenshots or Videos

The app doesn't allow taking screen shot.

### Additional Context

Might have to downgrade back to basic plan

### Operating System

Android

### Operating System Version

Android 13

### Device

Redmi Note 11 pro 5G

### Build Version

2023.8.0 (7466)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Adedamola-Aina** [comment]
Hi @warrenlayson 

I attempted to reproduce your issue and was unable to do so. I think this could do with your camera, could you maybe clean the lens and the screen with the TOTP qr code i.e camera and the screen, monitor or display. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
