### ISSUE TITLE
Unable to turn off warning that "unlocking may fail due to insufficient memory"

### ISSUE THREAD

**Issue by danmarg** [bitwarden/mobile#2775]
### Steps To Reproduce

1. Switch to Argon2 with default iterations. 
2. Unlock vault on iOS *via the password autofill integration*.

Note that Bitwarden warns that "unlocking may fail due to insufficient memory".

### Expected Result

If the user is comfortable with the KDF iterations, Bitwarden should allow the user to permanently dismiss this warning.

### Actual Result

This warning is shown on every unlock, and there is no setting to permanently dismiss or disable it.

Interestingly: I do not get this warning when unlocking the app itself, but only when using autofill.

### Operating System

iOS

### Build Version

2023.8.0 (4566)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
