### ISSUE TITLE
iOS app crashing when exporting

### ISSUE THREAD

**Issue by ripskydog** [bitwarden/mobile#2788]
### Steps To Reproduce

Setting > Export Vault (.json) > Export Vault *crash*

### Expected Result

The ability to export my vault, I've successfully done it before

### Actual Result

App crashes

### Operating System

iOS

### Operating System Version

16.6.1

### Device

iPhone 11

### Build Version

2023.8.0 (4566)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by ripskydog** [comment]
just updated to 2023.9.1 (4890) -- same thing happening

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Even though you've updated the app already, can you uninstall/reinstall the application to see if the issue persists? 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
