### ISSUE TITLE
Add support for KeePassDX on Android

### ISSUE THREAD

**Issue by HarriBuh** [bitwarden/mobile#2790]
I'm just wondering why this app hasn't been officially accepted/ added as an import source yet. Since I do only use KeePass on Android (and NOT on Windows, which is currently the only available version on Bitwarden) and KeePassDX on F-Droid/ GitHub is my daily driver for this.
The app does only support export via "kdbx", not CSV. Please add it asap.

**Comment by SergeantConfused** [comment]
Hi @HarriBuh,

Thank you for your GitHub report. We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thank you again,
