### ISSUE TITLE
Connection to self hosted server only works via vpn (even local)

### ISSUE THREAD

**Issue by Baspla** [bitwarden/mobile#2792]
### Steps To Reproduce

1. Go to "Sync" (Synchronisieren in german)
2. Press "Sync now"
3. Long wait until it fails
4. Activate VPN to my router or PNPCap on device
5. Go to "Sync" (Synchronisieren in german)
6. Press "Sync now"
7. It works

### Expected Result

It should connect without using a vpn

### Actual Result

it works only when a vpn is active. even if that vpn is only for capturing packets and uses the normal wifi

### Additional Context

On the server side there is no sign that any attempt at connecting is even made if the vpn is off.
I reset the network settings and set up a new docker deployment with a different subdomain, didn't help.
every other device/web works. I also tried multiple wlans and mobile data.
Curiously it also doesn't work with Google One VPN.

### Operating System

Android

### Operating System Version

13

### Device

Pixel 7

### Build Version

2023.9.1 (7790)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I think your error could have its origin in a misconfiguration of network settings or firewall in your self-hosted instance.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Baspla** [comment]
I can access my vault using the Website without issue. The issue is only with the app. That sounds like a bug to me.
