### ISSUE TITLE
IOS 17 TOTP Camera Scan is empty

### ISSUE THREAD

**Issue by jonatino** [bitwarden/mobile#2825]
### Steps To Reproduce

Go to any account click edit and click "Set up TOTP". The camera  will attempt to open but it just results in an empty screen.

### Expected Result

Should be able to scan QR codes

### Actual Result

Cant scan QR codes cuz camera doesnt appear to open properly

### Screenshots or Videos

![image](https://github.com/bitwarden/mobile/assets/1808569/485953bd-34b9-44ed-97a6-37e92879c32c)

### Additional Context

IOS 17.0.3

### Operating System

iOS

### Operating System Version

17.0.3

### Device

iPhone 13 Pro Max

### Build Version

2023.9.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarikaBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin with regard to camera permissions.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

The issue here will be closed

Thanks
