### ISSUE TITLE
"We were unable to process your request. Please try again or contact us"

### ISSUE THREAD

**Issue by davterra** [bitwarden/mobile#2877]
### Steps To Reproduce

I have been using Bitwarden self-hosted for a few years with zero issues. Love it!
I just opened my Android app and it asked me for my user email address. 
When I input the correct address, I get the message in the issue title:

"We were unable to process your request. Please try again or contact us"

It's working fine on my linux desktop app.

If I open the mobile app and it goes directly to asking for my password, rather than my email, the app crashes when I enter my password. 

### Expected Result

Expect the app to open to my database

### Actual Result

Error message as shown

### Operating System

Android

### Operating System Version

13

### Device

Samsung Galaxy S21 FE

### Build Version

Unable to get to that info within the app.

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @davterra, 

I attempted to reproduce your issue and was unable to do so. Specifically:

- I connected to a self-hosted server using the Android app
- I did not encounter this error

I think your error could have its origin in a misconfiguration or issue that has developed with your server.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Please note that we do not provide tech-support via GitHub.

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by carlosala** [comment]
@atjbramley I can also reproduce the same issue using `bitwarden.com` regular server.

**Comment by atjbramley** [comment]
Thanks for this information @carlosala, please contact support as directed above.

**Comment by davterra** [comment]
I uninstalled the current/Google Play  version of Bitwarden on my phone, and installed the apk for a 9/2023 build, and it works fine now.

**Comment by carlosala** [comment]
@atjbramley I was able to debug the issue. The problem is that, when logging in, instead of getting the response, the extension (or android app, or desktop app) gets the Cloudflare "Verify that you are human" screen, and the request, of course, fails since it gets a different stuff than expected.
I'd say this is a problem in the relationship frontend - backend.
