### ISSUE TITLE
Button padding isn't working properly

### ISSUE THREAD

**Issue by meanindra** [bitwarden/mobile#2881]
### Steps To Reproduce

Go to Settings -> Auto fill -> Block auto fill -> See New Blocked URL (Button)

### Expected Result

Button padding should be like other buttons in bitwarden
. 

### Actual Result

Some below part of the button text hiding

### Screenshots or Videos

![Screenshot_20231124_084834](https://github.com/bitwarden/mobile/assets/36324543/de377ccd-defe-46e3-861b-60552b501187)
![Screenshot_20231124_084852](https://github.com/bitwarden/mobile/assets/36324543/5233049e-12b8-458a-9eae-6a85d8d33bdb)

### Operating System

Android

### Device

IQOO neo 7 5g 

### Build Version

2023.10.0 (8257)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by bjacksonbit** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin related to increasing the system font and size on your device.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
