### ISSUE TITLE
App crashes a few seconds after loading a large vault

### ISSUE THREAD

**Issue by mayel** [bitwarden/mobile#2882]
### Steps To Reproduce

1. Launch the app
2. Authenticate (eg. with fingerprint)
3. Wait quite a while for the vault to load/sync
4. The first page of favorites appears
5. Wait a few more seconds during which the app UI is unresponsive
6. There's usually a small window (from zero to a few seconds) in which to try to quickly search/copy a password
7. App crashes

### Expected Result

Launch the app and be able to use it leisurely 

### Actual Result

App crashes 

### Additional Context

Have tried on two different devices, and also have tried deleted app cache. 
May be similar to other open issues, such as https://github.com/bitwarden/mobile/issues/1715 and https://github.com/bitwarden/mobile/issues/2006

### Operating System

Android

### Operating System Version

13

### Device

OnePlus 7t and Realme GT2

### Build Version

8002

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @mayel ,

I attempted to reproduce your issue and was unable to do so. 

I would like to know more about your issue and would encourage you to contact us via support to see if we can re-produce this.  We do not offer tech support via GitHub.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
