### ISSUE TITLE
Bitwarden Android login to Microsoft live.com

### ISSUE THREAD

**Issue by MAMedici** [bitwarden/mobile#2888]
### Steps To Reproduce

1. Launch Microsoft app (i.e., Onedrive)
2. Select saved Microsoft login account from Bitwarden extensions.
3. App proceeds to new page and prompts for live.com password
4. Bitwarden only suggests TOTP

### Expected Result

Bitwarden should suggest the saved password for live.com password prompt

### Actual Result

Bitwarden only suggests the TOTP for this page, which is not correct

### Additional Context

The first login screen only accepts the username.  Live.com asks for the password on the next screen, but BW only suggests the TOTP on this page.  If you select the TOTP, BW puts the TOTP in the password field.  Then I can backspace to clear the TOTP from the password field, and BW will suggest my live.com password, and followed by a page to enter my  TOTP (the latter of which in the clipboard, but may have expired by this point)

### Operating System

Android

### Operating System Version

14

### Device

Google Pixel 8 Pro

### Build Version

2023.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so using a Pixel 7A. I think your error could be a result of not correctly auto-filling the password field, as the TOTP code being copied to the clipboard is expected behavior. I would take the time to review our Android auto-fill options, and get in touch with support if your issue persists.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
