### ISSUE TITLE
[Feature request] Open a popup window when a password field is detected on Android, instead of the whole app, just like LastPass

### ISSUE THREAD

**Issue by remewer** [bitwarden/mobile#291]
I really miss that feature, it mimics the behavior of password manager extensions in desktop browsers.

**Comment by BigNickBurgess** [comment]
I did like that feature of LastPass quite a lot.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
