### ISSUE TITLE
Autofill not working on iOS for entries with master password toggle turned on

### ISSUE THREAD

**Issue by ashutoshsaboo** [bitwarden/mobile#2923]
### Steps To Reproduce

1. Go to any site (I saw this with gmail and multiple other similar sites) - where you have a password entry saved in BW with master password toggle turned on. 
2. Click on the corresponding entry suggested near ios keyboard for autofill, it will do a faceid scan and ask for master pwd - enter it. It won't autofill anything, whereas it should autofill the data. 
3. Atleast in my usage - i couldn't see this autofill issue happening for entries with master pwd turned off on iOS. But i'm not exhaustively sure - Bitwarded team can test more exhaustively about this flow. 

For me issue specifically is happening on ios, not sure about android. 

### Expected Result

It should autofill email and password after entering master pwd. 

### Actual Result

It doesn't autofill email and password even after entering master pwd. 

### Operating System

iOS

### Operating System Version

iOS 17.2.1

### Device

iPhone 12

### Build Version

2023.12.0 (5688)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by atjbramley** [comment]
Hi @ashutoshsaboo, 

I attempted to reproduce your issue and was unable to do so.

In particular, I enabled 'Master Password Reprompt' and attempted to autofill a range of websites using Firefox, Safari and Chrome on iOS 17.1.1 on an iPhone SE with Bitwarden 2023.12.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).  Please include specific details as to the sites you are finding this with, as well as the browser you are using.

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by ashutoshsaboo** [comment]
Hi @atjbramley - I tried it just now again on gmail it's the same behaviour. In fact i've seen this happen with a range of websites and facing this issue since quite a few days (since the latest BW app update was installed from what I can recall briefly) - which is why I opened this issue. Just one thing I forgot to mention in the bug report - i'm on Brave browser on ios (and the mentioned iPhone/ios version configs above) if that matters. Can you try checking on the same please, if you're able to reproduce it?

**Comment by ashutoshsaboo** [comment]
@atjbramley please see if you can reproduce the issue on your iPhone with the above mentioned brave browser version and other details as mentioned above . If you can reproduce the issue, please re-open the issue.

**Comment by atjbramley** [comment]
@ashutoshsaboo we use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
