### ISSUE TITLE
Sync error Andoid APK 

### ISSUE THREAD

**Issue by ArthFink** [bitwarden/mobile#2932]
### Steps To Reproduce

I do not current know how to reproduce it.

The general issue / bug is. With since some releases i can't sync my Android 14 device, on IOS there is now issue. The account in question is self-hosted, but works flawlessly with other Operating systems. 

I have re-installed the app and I get an email notification that a new device was log in. I can see the login process in the access log of the Docker. But the sync is not sent to it.

### Expected Result

Normal sync from the server

### Actual Result

Sync faild

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/36709816/17c41b5e-dc06-43b9-8617-45190532ab96

### Operating System

Android

### Operating System Version

Andoid 14

### Device

Google Pixel 7a

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2023.12.0 (8588)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I'm unable to reproduce your issue due to the self-hosted environment, and am not able to reproduce it in my own environment - there may be specific networking considerations we need to consider. We use GitHub issues as a place to track bugs and other development related issues. I'd recommend contacting the support team using our “Contact support” form located on our Help Center (https://bitwarden.com/help/) so we can investigate this further with you.

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
