### ISSUE TITLE
Bug: Credentials are not found for DNS rewrites

### ISSUE THREAD

**Issue by flooxo** [bitwarden/mobile#2968]
### Steps To Reproduce

1. Configured an item for a page with a local IP address and for a DNS rewrite that points to the same page
2. When calling the IP address, the item is automatically recognized
3. When calling the DNS rewrite, no item is found

### Expected Result

Insert the credentials for the corresponding page

### Actual Result

No credentials are found
![image](https://github.com/bitwarden/mobile/assets/93255373/a5678786-bb7e-4671-ac85-3d4a9389fb7a)

### Additional Context

There is of course a corresponding item for the site, which is also synchronized with the app. The strange thing is that it is automatically entered when calling the page via IP address , but not when calling the DNS rewrite site.
Both pages work on the PC with the web extension, so this is only a mobile issue
![image](https://github.com/bitwarden/mobile/assets/93255373/a57f19d9-a24c-40d4-a13b-bb9a823dd6fb)

### Operating System

Android

### Build Version

2024.1.1 (8843)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by daniellbw** [comment]
Hi there,
I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration 
I did some digging on the issue and it lead me to this link https://issuetracker.google.com/issues/140786115?pli=1 specifically surrounding android.
We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.
Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 
The issue here will be closed.
Thanks!

**Comment by flooxo** [comment]
Thanks for the post. Maybe I have misunderstood or described something inaccurately, but I can access the page via mDNS (here: `proxmox.local`) and it is also displayed in the same way as when it is accessed directly with the IP. Only when I then want to use Bitwarden to enter the credentials, no entry is found 
I'll have to take another look at it, but I don't know what I could change about my configuration at the moment
