### ISSUE TITLE
Canceling Android password has unexpected result

### ISSUE THREAD

**Issue by VincentSC** [bitwarden/mobile#2996]
### Steps To Reproduce

1. Get phone without any security enabled
2. Enable fingerprint in Bitwarden. Then is stated, fingerprint-security needs a PIN or Password to get enabled
3. Choose password as primary security option
4. Get a question on the old password
5. Cancel it (reason: password unknown)
6. Leave the phone for a minute to let the screen turn off
7. Android suddenly has password enabled

### Expected Result

When canceling the password-question, it should _not_ get enabled!

It was back-and-forth between Android-settings and Bitwarden-settings. Still, it looked to be caused by Bitwarden client and not Android, as no such problem exists when just using Android.

### Actual Result

Phone is locked and cannot be used anymore. :(

### Additional Context

The phone used to have a PIN that was turned off years ago, as it was unknown to the user that there was a fingerprint-option on the phone, and the PIN was a hassle. The user has no memory of the password.

### Operating System

Android

### Operating System Version

Android 10 with latest patch (March 2023)

### Device

Samsung Note 9

### Build Version

2024.1.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the Android OS passcode/password settings, rather than something to do with Bitwarden specifically - Bitwarden doesn't have the ability to set an Android password for you.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by VincentSC** [comment]
Thanks for trying to replicate! I don't wish anybody to get into the same situation!

Does Bitwarden have the ability to enable fingerprint? Or does it just send the user to Android's configuration screens? If Bitwarden does the first, then it could actually result to get the system in such state - then make sure that the user is not helped too much here.

**Comment by VincentSC** [comment]
What I found before is that when an app requires some security, then an Android phone can get into such a state. This happens to people who install a bank-app in an alike situation. Seemingly Android/Samsung checks for such apps, and then turns it on - even if it was not actually checked with the user.

See https://eu.community.samsung.com/t5/mobile-apps-services/lock-screen-suddenly-asks-for-password-always-used-fingerprint/td-p/4149578/page/4 for who probably installed such app - can be installed by a phone-transfer. As my search focused on Samsung, I don't know the state of other brands.

So even though the bug is with Android, security-requesting apps trigger it. So my suggestion: use `fingerprintManager.hasEnrolledFingerprints()` and then just tell, don't help.

**Comment by VincentSC** [comment]
Immediately closing after answering? No response? And neither applied my proposed fix?

I hope this does not age well
