### ISSUE TITLE
Randomly crashing on launch (iOS, self-hosted Bitwarden)

### ISSUE THREAD

**Issue by Umiamz** [bitwarden/mobile#3034]
### Steps To Reproduce

1. Launch app on iPhone or iPad
2. As soon as Face ID authentication completes, app crashes
3. Launch app a second time
4. App runs correctly 

### Expected Result

App launches without crashing.

### Actual Result

App randomly crashes after Face ID authentication but runs correctly upon second launch.

### Additional Context

Bitwarden is self-hosted and up to date (24.02)

### Operating System

iOS

### Operating System Version

17.3.1

### Device

iPhone 15 Pro Max and iPad Pro M2

### Build Version

2024.2.0 (6100)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Umiamz** [comment]
Just to add that I’ve uninstalled the app, rebooted iPhone and iPad, then installed the app again but it hasn’t helped.

**Comment by Umiamz** [comment]
I think this is related to Face ID. Having disabled it and used master password or PIN, I haven’t experienced any more crashes on launch.

**Comment by Adedamola-Aina** [comment]
Hi @Umiamz 

Thank you for informing us about the issue not occurring again. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

The issue here will be closed.

Thanks!
