### ISSUE TITLE
Autocomplete not showing in browser

### ISSUE THREAD

**Issue by BHydden** [bitwarden/mobile#3067]
### Steps To Reproduce

1. Go to a webpage
2. Click on a username or password field
3. See that Bitwarden keyboard shortcut fails to appear

### Expected Result

Autocomplete should show up in the browser like it used to (still works in other apps) 

### Actual Result

Nothing shows up, as with a normal text box. 

### Additional Context

Browser version:
Vanadium  122.0.6261.105.0

org.chromium.chrome
versionCode 626110533

### Operating System

Android

### Operating System Version

Android 14 qpr 2 GrapheneOS 2024030800

### Device

Pixel 6

### Build Version

2024.2.1 (9705)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by daniellbw** [comment]
Hi there!
We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

Could you please fill in the form regarding the specific web page that you are encountering this on.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.
This issue will now be closed. 
Thanks!

**Comment by BHydden** [comment]
Thanks for pointing me in the right direction 👍
