### ISSUE TITLE
Automatic Dark/Light theme does not work

### ISSUE THREAD

**Issue by update-freak** [bitwarden/mobile#3072]
### Steps To Reproduce

1. Go to Einstellungen -> Aussehen -> Design -> Standard (System)

### Expected Result

Theme is according to System theme (dark/light)

### Actual Result

Currently it's dark all the time

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy S23

### Build Version

2024.2.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Can you verify that your Samsung Galaxy S23 isn't just staying in dark mode?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by update-freak** [comment]
After the new Samsung Firmware for the S23 (relased in March 2023) I restarted the phone and now it's working.
