### ISSUE TITLE
auto fill not working in hyperos(MIUI)

### ISSUE THREAD

**Issue by imtipi** [bitwarden/mobile#3107]
### Steps To Reproduce

1. press auto fill on any apps

### Expected Result

detected what website you are in while using chrome,and what apps you are in(example:X)

### Actual Result

bitwarden always detected miui.systemui.plugin as app and filling not work even manually choose

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/27230181/54c8d66f-6910-4489-9013-b6ec6cc49ad9

### Additional Context

already saw some case like me
https://www.reddit.com/r/Bitwarden/comments/1ayu7bs/accessibility_does_not_work/

### Operating System

Android

### Operating System Version

HyperOS 1.0.21.0 (Android 14)

### Device

Xiaomi 14 PRO

### Build Version

2024.3.0(9799)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Can you follow the steps listed here to make sure autofill is set up for that device: https://bitwarden.com/help/auto-fill-android/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
