### ISSUE TITLE
Improve the search feature

### ISSUE THREAD

**Issue by Hunsu** [bitwarden/mobile#311]
The search screen usually take 10s to show. Is it normal? 
I think we should ignore spaces  at the end of the search word. For example when I'm searching for Paypal password I usually type Pay and my keyboard suggest Paypal so when I accept that suggestion the keyboard add a space at the end and then the app show no results.

**Comment by kspearrin** [comment]
No, that is not normal. Its nearly instant on my test device. What type of device are you using? How large is your vault?

**Comment by keehun** [comment]
I’m on an iPhone 6 and around

**Comment by therealmorris** [comment]
I have a Samsung Galaxy S8 with around 900 sites. Clicking search regularly takes 10s or more for me.
I love the app otherwise but this really breaks up the workflow

**Comment by carlkibler** [comment]
It is far worse on my phone, on the order of 1 minute before the Search screen is loaded and ready to use. I have 1662 items (yikes). 

I haven't looked at the code yet to see, but does it build a ListView with all items, rather than lazy-loading them? Also, why show password items at all on the search screen? 

Well, I understand some people might want to scroll through them. I would prefer not, if that's causing the huge delay. It would be great to get a Settings toggle to not show all items in the Search window, shut that off automatically if user has > 500 items, or figure out a massive performance improvement for that page.

**Comment by SoreGums** [comment]
super slow here as well - 2,145 items

search list should not load the list and then search.

it ought to search then show matches.

**Comment by kspearrin** [comment]
Can you test v2.0 beta on play store and see if this has been improved?

**Comment by SoreGums** [comment]
Excellent, only have to wait ages for that first load. Doing a search is near instant now. Top job
