### ISSUE TITLE
IOS 12 autofill does not work after last update

### ISSUE THREAD

**Issue by jonknud** [bitwarden/mobile#3115]
### Steps To Reproduce

1. update bitwarden
2. open a website with login
3. autofill button apears
4. touch id confirmation
5. nothing happens

### Expected Result

passwort autofill

### Actual Result

nothing

### Additional Context

Before the last app update it worked. Now it is not working.

### Operating System

iOS

### Operating System Version

12.5.7

### Device

iPhone 6

### Build Version

2024.2.1 (6741)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
