### ISSUE TITLE
Undelete option has no effect on the Undelete line popping up

### ISSUE THREAD

**Issue by Mikefedkiw** [bitwarden/mobile#3120]
### Steps To Reproduce

1. Go to '...'settings
2. Click on '....'tab
3. Scroll down to '....'undelete
4. Click on '...'turning it on or off seems to have no effect on the undelete popping up after deleting a tab

### Expected Result

Under Settings/Tab there's an option called "Undelete" that can be turned on and off. The problem is that setting it either way has no impact in the undelete line continually popping up every time a tab is deleted.

### Actual Result

The popup of the undelete line covers what I want to access and forces me to look at it until it goes away so I can access what's under it. It wouldn't be such an issue if I only had a couple of tabs open I guess, but I usually have a ton of tabs in the browser.

### Screenshots or Videos

![Screenshot_20240327_100342_Soul](https://github.com/bitwarden/mobile/assets/92271076/51d56ac7-3a8f-46bb-ac4d-54ec1b9f251d)
![Screenshot_20240327_101155_Soul](https://github.com/bitwarden/mobile/assets/92271076/8476909f-d180-4786-8afc-06ac0b54cbae)

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy S24 Plus

### Build Version

1.4.12

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please make sure you are using the most up-to-date version of the Bitwarden app.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Mikefedkiw** [comment]
I took another video that shows how the undelete option seems to have zero affect on whether or not the undelete option shows up or not. I also tried forcing stop the app just in case it seeded to be restarted for the option to work but that also has zero affect on it.

I've tried multiple things and never does anything seem to have any affect on that darn undelete popping up. I even tried on an emulator on my PC and I get the exact same result. 

The version I have installed is v1.4.22 and my phone is an S24 Plus running Android 14.

Mike 


https://github.com/bitwarden/mobile/assets/92271076/d9c11d9b-339b-4381-a061-9c63ce8f72e1
