### ISSUE TITLE
Android Inline dropdown shows incorrect logins for certain App Logins

### ISSUE THREAD

**Issue by therealfacted** [bitwarden/mobile#3128]
### Steps To Reproduce

On various Android App logins, such as American Express app, when I use BitWarden to dropdown the credentials, I see the correctly linked American Express logins but I also see many (16) incorrect login associations. If I scroll down to "auto-fill with bitwarden/go to vault", I see the correctly associated logins at the top, but then I also see various "possible matching items" that have no association whatsoever.

The relevant URI's for American Express that I'm using:
https://americanexpress.com
androidapp://com.americanexpress.android.acctsvcs.us

However, I'm seeing 16 "possible matching items" including the following uri's:
androidapp://com.august.luna
https://august.com
https://chase.com
http://reg.usps.com
http://espn.com

There a few others as well.

### Expected Result

If there is a linked site that definitively matches the app via URI, the only sites that should be showing are the definitively matched sites. There is no need for "possible matching sites".

In addition, in this case, it's quite unclear how these sites are "possibly" matching and are showing up in the dropdown anyway.

### Actual Result

Multiple incorrectly associated login credentials are showing up in android app login fields (such as American Express app), when they in fact are not affiliated with the app.

### Operating System

Android

### Operating System Version

Android 14

### Device

Pixel 7

### Build Version

AP1A.240305.019.A1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by therealfacted** [comment]
> Hi there,
> 
> Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.
> 
> We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/
> 
> Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
> 
> This issue will now be closed.
> 
> Thanks!

Can you please explain how this is not a bug and instead a default behavior?

It's matching incorrect sites into the App fill dialog. For instance, if for the American Express app, if it suggested a login for "American Airlines" because of the crossover with "American", I would understand that. 

However, the sites it suggests as "possible matches" have no relation whatsoever as I showed in the bug report.
