### ISSUE TITLE
Unable to set Bitwarden as Passkey Provider 

### ISSUE THREAD

**Issue by dupondje** [bitwarden/mobile#3199]
### Steps To Reproduce

1. Go to 'Auto-Fill'
2. Click on 'Passkey management '

This fails

### Expected Result

Bitwarden should be set as Passkey Provider.

### Actual Result

Error
![Screenshot_2024-04-26-21-05-53-739_com miui bugreport](https://github.com/bitwarden/mobile/assets/723195/d3ac1a5b-3bd0-47aa-90ba-a61b18c65893)

### Operating System

Android

### Operating System Version

Android 14 (HyperOS 1.0.1.0)

### Device

Poco F4 GT

### Build Version

© Bitwarden Inc. 2015-2024  Versie: 2024.4.1 (10283)

### Beta

- [X] Using a pre-release version of the application.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Please try reinstalling the Bitwarden app from the official downloads page: https://bitwarden.com/download/

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by gurkburk76** [comment]
I have the same problem on a similar phone.
app version 2024.4.1 (10283)
phone: xiaomi 11T / Android 14 (Xiaomi HyperOS 1.0.2.0)

**Comment by gurkburk76** [comment]
this workaround seems to work, https://1password.community/discussion/145306/i-cant-enable-autofill-in-hyperos

**Comment by dupondje** [comment]
Today I received the 1.0.2.0 update for HyperOS on my phone.
And guess what, it works now :)

**Comment by gurkburk76** [comment]
Still dosen't work here, icreated a passkey for amazon that works just fine on windows but it when i try to use it with the phone it seems to try and use keys stored on google so no go. Oh well i guess i'll have to use some of that patience i don't have ;)

**Comment by michael-r-elp** [comment]
For me it was initially working on android with the 2024.4.1 version, but now it stopped working and I can't seem to get it working again, it just doesn't show passkeys from bitwarden and also doesn't let me store passkeys there anymore, reselecting bitwarden as password and passkey provider doesn't help either. Though on the pixel settings it also doesn't distinguish between a password manager and passkey provider so I have no idea if it is properly registering bitwarden as passkey provider again.
