### ISSUE TITLE
When using autofill on iOS, selecting an entry should not cause the entire app overlay to load in the background while face ID authentication is in progress

### ISSUE THREAD

**Issue by cooldude-91** [bitwarden/mobile#3236]
### Steps To Reproduce

1. Select an autofill entry using Bitwarden
2. While FaceID authentication is happening, while Bitwarden application gets popped up in the background which makes the experience not seamless.
3. For reference I have attached how Enpass handles this which is more clean, the overlay is transparent making it look seamless.

https://github.com/bitwarden/mobile/assets/156496036/535f0756-5dc1-455e-a26e-2b2f4afbb6cb

### Expected Result

As shown in the video

### Actual Result

Bitwarden application is visible during faceID authentication

### Operating System

iOS

### Operating System Version

17.4.1

### Device

iPhone 13

### Build Version

2024.4.2 (7528)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @cooldude-91,

Thank you for this report. This seems to be closer to an improvement suggestion or a feature request, than a report about a certain function not operating as expected; With that in mind, please feel free to submit this idea in the [Feature Requests](https://community.bitwarden.com/c/feature-requests/5/none) section of the Bitwarden Community Forums.

You can sign up to the Bitwarden Community Forums and search for this idea, just in case a similar request already exists. If you find one, you can vote for it and contribute to the discussions about it; If not, you can submit this idea as a new request so that it can be properly tracked.

Because we used GitHub to track bugs and other development related matters, this report will now be closed. Please note that the “Closed as not planned” status is for internal tracking purposes only; Please do not hesitate to submit your suggestion via the Community Forums.

Thank you again,
