### ISSUE TITLE
Toggle password view on log in

### ISSUE THREAD

**Issue by justinjk007** [bitwarden/mobile#324]
I had opened this issue on the web app page last year, which got implemented. I thought this would be implemented to the mobile apps as well. Is this a work in progress if not can you consider it?

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
