### ISSUE TITLE
[iOS] Unable to modify items when 'Re-enter master password' is selected

### ISSUE THREAD

**Issue by deiyanfott** [bitwarden/mobile#3245]
### Steps To Reproduce

1. Login to your Bitwarden account
2. Create an item and ensure 'Master Password re-prompt' option is select
3. Save item
4. Open record created step 2
5. Modify record
6. Enter master password when re-prompt pop up shows

### Expected Result

Record will be saved successfully

### Actual Result

Mobile app crashes

### Operating System

iOS

### Operating System Version

17.5

### Device

iPhone 13 Pro

### Build Version

2024.4.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
