### ISSUE TITLE
Autofill fails with different subdomains on iOS

### ISSUE THREAD

**Issue by mr-n0cturne** [bitwarden/mobile#3272]
### Steps To Reproduce

1. Open Edge on iPadOS/iOS 17.51
2. Open sub2.mydomain.com
3. Autofill at the bottom suggests sub1.mydomain.com (FAIL)
4. Klick on the key icon, beside the wrong autofill entrry, to open Bitwarden
5. Bitwarden shows sub2.mydomain.com
6. Klick on sub2.mydomain.com
7. Correct credentials are inserted (SUCCESS)

### Expected Result

The by autofill suggested credentials are matching to the actually opened website.

### Actual Result

On [sub1, sub2, sub3, sub4, ect.].mydomain.com autofill suggests sub1.mydomain.com until klicking the key icon.

### Additional Context

I was excessively playing with matching methods. Basically Host/Server, Begins with and a valid RegEx should work. But none of my configurations on all existing subdomains wored.

### Operating System

iOS

### Operating System Version

17.51

### Device

iPad Pro M4, iPhone 15 Pro

### Build Version

2024.5.1 (7674)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment]
Hi @mr-n0cturne,

Thank you for this report. What you're describing is the expected behaviour of the [Autofill flow on iOS](https://bitwarden.com/help/uri-match-detection/#host); The operating system would match based on Host, when it comes to the autofill banner. With that in mind, and as you mentioned, you can open the Bitwarden client to see and select the relevant vault item.

I will now close this GitHub report. If you have any questions or concerns, please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/), and please include a link to this GitHub report in your message if you do so.

Thank you again,

**Comment by mr-n0cturne** [comment]
Thanks for the quick reply. What a mess, that it’s not possible in iOS to match a subdomain.
