### ISSUE TITLE
Password is set back to hidden

### ISSUE THREAD

**Issue by legnusv2** [bitwarden/mobile#3325]
### Steps To Reproduce

1. Go to 'My vault'
2. Click on 'an item with TOTP'
3. Click on ' 👁️ ' to show password

### Expected Result

Password should be visible indefinitely

### Actual Result

Password is set back to hidden when TOTP count down is refreshed

### Screenshots or Videos

https://github.com/bitwarden/mobile/assets/38706593/0cc23a0c-6386-463c-9df2-8c916a27e9f5

### Additional Context

Only happens in items with TOTP

### Operating System

Android

### Operating System Version

14

### Device

Pixel 7 Pro

### Build Version

AP2A.240605.024

### Beta

- [X] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by legnusv2** [comment]
I still think it's a bug. In items with no TOTP I'm able to see my password
for more than a second.

**Comment by likevi9528** [comment]
@Greenderella, Hello, this is a bug. I have been troubled by this bug for a long time. I can reproduce this bug below.
Clicking ‘👁️’ to show the hidden password will cancel the display due to the TOTP countdown. After deleting TOTP, the hidden password can be displayed normally.

https://github.com/bitwarden/android/assets/81839775/5aee7ee9-b74a-443a-8cb8-3163e1ab81a2
