### ISSUE TITLE
Android beta login incorrect

### ISSUE THREAD

**Issue by GitStudying** [bitwarden/mobile#3329]
### Steps To Reproduce

1. Install Android bitwarden beta 2024.6.1
2. Click on 'correct bitwarden server'
3. Login with email continue
4. Fill in password and click login with password. 
5. Get error incorrect username or password

### Expected Result

Login to Bitwarden account or possibly even a 2FA of the account as that is the method when logging into browser where the client is unknown.

### Actual Result

Error message about incorrect username or password.

### Additional Context

Web and release Bitwarden work perfectly.

### Operating System

Android

### Operating System Version

Android 14 (update 5 June / build 240605)

### Device

Pixel 7a

### Build Version

2024.6.1

### Beta

- [X] Using a pre-release version of the application.

**Comment by daniellbw** [comment]
Hi @GitStudying ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration could you try uninstalling and reinstalling the application.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
