### ISSUE TITLE
iOS App: Creating Secure Note Text Field with 2 or more consecutive hyphens crashes the app

### ISSUE THREAD

**Issue by shawalli** [bitwarden/mobile#3330]
### Steps To Reproduce

1. Create a secure note.
2. Add a text custom field. Add a title.
3. For the text field value, make it "--" or "---" (without quotes).
4. Click Save.
5. App crashes.
6. Re-open app.
7. Find secure note and try to open it.
8. App crashes.

### Expected Result

Saves the secure note and renders it.

### Actual Result

Saves the secure note and crashes.

### Additional Context

Additionally, this does not happen on the Chrome extension, which is how I introduced this problematic series of characters in the first place. This is also where I confirmed that the app was able to save the note changes before crashing.

### Operating System

iOS

### Operating System Version

17.5.1

### Device

iPhone 13

### Build Version

2024.5.1 (7674)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so, the note gets created, and the app doesn't crash. You may want to try updating your Bitwarden mobile application, 2024.6.0 is already available for iOS.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by shawalli** [comment]
Sorry about that, I didn't realize there was a separate process for filing bugs for the app. I can also file it there, but I did make a video to show exactly what you need to do to crash it. This is using the latest version of the app (I upgraded and tried it again before creating the video).https://github.com/bitwarden/mobile/assets/2999598/bfa21446-4e84-4fd4-832b-266c2f586754

This video shows opening that note once it has been created.

https://github.com/bitwarden/mobile/assets/2999598/b2b383fd-eb36-4a30-a43c-2671fc6147f8

**Comment by Greenderella** [comment]
Hi @shawalli

Revisiting this report, I've retested by creating an item directly through the web app to circumvent the long dash substitution issue caused by my keyboard. Despite that the mobile app remains stable when I open or edit the item, it’s worth noting that I'm currently using the beta version of the native app. 

Could you try replicating this issue using the beta version as well? The beta program can be joined, and the app downloaded from here: https://community.bitwarden.com/t/about-the-beta-program/39185

Given the recent updates to the beta builds, it would be beneficial to verify if the problem persists with the latest version.

Thanks for your assistance, and I eagerly await your feedback!

**Comment by shawalli** [comment]
I downloaded the beta and re-created a test password, using the exact same steps as before. I tried it two ways: creating the password entry on the desktop and in the iOS app, then re-opening it in the iOS app. In both cases, the crash no longer happens! This can now be marked as closed, thank you!
