### ISSUE TITLE
Android beta login with 2FA.

### ISSUE THREAD

**Issue by BertoMejia** [bitwarden/mobile#3333]
### Steps To Reproduce

Cloud or self-hosted?: Cloud
Device Type: Galaxy S24 ultra
OS and version: Android 14
Bitwarden version: beta 2024.6.1

Steps to reproduce the issue:

Input email and password
Pass captcha
Go redirected back to application
Receive error message that says, “Username or password is incorrect. Try again.”
The username and password are correct. The app never asked for my 2 factor Auth.

### Expected Result

Log in. 

### Actual Result

Login fails 

### Operating System

Android

### Build Version

2024.6 1

### Beta

- [X] Using a pre-release version of the application.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
