### ISSUE TITLE
Opening attached image should open internally

### ISSUE THREAD

**Issue by grrosminet** [bitwarden/mobile#3356]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. modify an element to add an image as attachment (let's call it "my_photo.jpg")
2. go back on "display element" view, the image is listed at the bottom
3. you cannot open the image, the only thing you can do is store it on the device

### Expected Result

we should be able to display the image without storing it, looking for it in the file explorer, and the forget to delete it after usage

### Actual Result

you cannot open the image, the only thing you can do is store it on the device, then look for it in the files explorer, use it and forget to remove.
During this whole time, the image is exposed to other apps on the phone (not relly secure ...)

### Operating System

Android

### Operating System Version

14

### Device

Galaxy Z-Flip

### Build Version

2024.6.0 (10746)

**Comment by daniellbw** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
