### ISSUE TITLE
Switching between Bitwarden user accounts (enterprise to personal) , cant see items in my vault

### ISSUE THREAD

**Issue by s101-99** [bitwarden/mobile#3363]
### Production Build

- [x] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. In the android app, be logged into 2 accounts, both with MFA enabled
2. Switch back to the 1st account , by clicking on the user initals in the top right
3. it asks for biometric auth - press thumbprint
4. it logs in ok, and syncs the vault i.e. (1000+ items)
5. all the contents of the vault are shown as many rows of blank data- I click on an item and its empty.
6. The only way to recover, is to remove the app, and login again fresh (with only 1 account), then the vault appears ok

### Expected Result

List of all vault items with data should be visible

### Actual Result

List of empty vault items appear - if you open any they are empty (no data, apart from a timestamp)

### Additional Context

i have tried manually sync'ing, and this has no effect

### Operating System

Android

### Operating System Version

Android 14 - One UI 6.1 - security Patch 1 June 2024

### Device

Samsung Galaxy S24

### Build Version

2024.6.0 (10746)

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. This could be an account specific issue, in which case I would recommend contacting support due to the sensitive nature of troubleshooting account related issues.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
