### ISSUE TITLE
discord passkey not working

### ISSUE THREAD

**Issue by Shiroe93** [bitwarden/mobile#3381]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Go to discord app
2. Click on settings then account then security keys
3. Add a new security keys
4. Try to use it and it see it not working 

### Expected Result

Being able to access to discord app with a passkey 

### Actual Result

Unexpected error

### Operating System

Android

### Operating System Version

14 one ui 6.1

### Device

Samsung Galaxy S24

### Build Version

discord 243.16 bitwarden 2024.7.1 (11086)

**Comment by sammbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by Shiroe93** [comment]
> Hi there!
> 
> We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:
> 
> Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
> 
> Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform
> 
> In this case, we will go ahead and file an autofill report for you with the information you added here.
> 
> In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.
> 
> This issue will now be closed. 
> 
> Thanks!

I don't think it's an autofill issue because it doesn't save the passkey at all 
Works fine on browser extension on Firefox accessing discord web app

**Comment by maco2035** [comment]
I have the same issue. I can't login. The passkey doesn't show up. I have a the same one ui 6.1, android 14 but with a s22 ultra.
