### ISSUE TITLE
Unable to copy text from a secret note

### ISSUE THREAD

**Issue by drimchansky** [bitwarden/mobile#3388]
### Production Build

- [x] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Open a secret note
2. Select a text from "NOTES" section and copy it

### Expected Result

Text selected and copied successfully

### Actual Result

It is impossible either select and copy text

### Additional Context

Tested it on Android, everything works fine

### Operating System

iOS

### Operating System Version

17.6.1

### Device

iPhone 11

### Build Version

2024.8.1 (1051)

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Next to the note there is a **...** toggle that you should press and there is a copy note.

![IMG_E399CB703F73-1](https://github.com/user-attachments/assets/fb3c9671-6a93-40e1-b60f-7c5d461bf949)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by drimchansky** [comment]
@daniellbw Hi!
Yes, I know about this toggle, but in some cases users need to copy just a part of a note.
I don’t agree with closing this issue, it worked several weeks ago but now some use cases are broken.
