### ISSUE TITLE
No bitwarden autofill or bitwarden pop-up on U.S. bank mobile app

### ISSUE THREAD

**Issue by iaminov** [bitwarden/mobile#3396]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

Go to the U.S. bank mobile app and try to login. Bitwarden doesn't show up to offer to fill the password. 

### Expected Result

Bitwarden offering the fill password

### Actual Result

Nothing happens at all

### Operating System

Android

### Device

Samsung Galaxy S23

### Build Version

2024.7.1

**Comment by Neonwarden** [comment]
Hi there, 

Thank you for bringing this matter to our attention. Due to the specific requirements of addressing autofill issues, we manage them through distinct tracking forms based on the application:

For mobile-related reports, please use: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

For browser extension reports, please use: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

Completing the relevant form will greatly assist us in resolving the problem efficiently.

Thank you for your cooperation and understanding.  This issue will now be closed.
