### ISSUE TITLE
Bitwarden Authenticator iPAD  won't allow exporting  *json (*csv) 

### ISSUE THREAD

**Issue by stritch-ua** [bitwarden/mobile#3397]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Go to '.Setting..'
2. Click on 'Export'
3. Click on 'Export items'
4. Click on 'Export items'
5. The application closes and shows the desktop

### Expected Result

Open a choice of where to save the file as on iphone iOS 18 where these steps lead to a successful result

### Actual Result

There is no export of json or csv files. Doesn't give an opportunity to choose what to do including saving.
After trying to export the application closes and exits.

### Screenshots or Videos

https://www.youtube.com/shorts/4gi4kWdjrEg

### Operating System

iOS

### Operating System Version

18,0

### Device

Apple iPad Air 11" M2 2024

### Build Version

2024.6.1 (45)

**Comment by SergeantConfused** [comment]
Hi @stritch-ua,

Thank you for this report. This matter has already been captured internally and has been highlighted to Engineering. With that in mind, I will now proceed and close this GitHub report, also because this repository belongs to the older mobile (Android/iOS) Bitwarden Password Manager clients; The Bitwarden Authenticator for iOS repository is [here](https://github.com/bitwarden/authenticator-ios/).

Thank you again,
