### ISSUE TITLE
Families Plan 2019 not able to use premium feature in organization (attachments)

### ISSUE THREAD

**Issue by IV-95** [bitwarden/mobile#3398]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Create a new password entry
2. Move newly created entry to the family organization
3. Edit password entry and try to add an attachment

### Expected Result

Are able to attach a file of your choice

### Actual Result

unable to attach a file

Error message: A premium membership is required to use this feature.

Was working fine in previous version

### Screenshots or Videos

![error](https://github.com/user-attachments/assets/0eace521-eb97-49cc-b422-294168af6ace)

### Operating System

iOS

### Operating System Version

17.6.1

### Device

iPhone 14

### Build Version

2024.9.2 (1106)

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so - this may be something we can resolve by discussing account related information in a support ticket.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
