### ISSUE TITLE
Can't login using YubiKey NFC 5 after iOS app update

### ISSUE THREAD

**Issue by SebDominguez** [bitwarden/mobile#3401]
### Production Build

- [x] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. On the login screen: enter your email.
2. Fill in your master password.
3. When the app asks you to scan the YubiKey, scan the key.
4. The app will return to the previous screen, asking you to scan the key again.

### Expected Result

Once the YubiKey is scanned, the app should open your vault.

### Actual Result

When the key is scanned, the app keeps showing you the 2FA screen.

### Screenshots or Videos

https://github.com/user-attachments/assets/cf92440c-0270-43f1-a9b1-9a00064d01d6

### Additional Context

The WebUI is working fine.

### Operating System

iOS

### Operating System Version

18

### Device

iPhone 12 Pro Max

### Build Version

2024.9.2 (1106)

**Comment by cbw23** [comment]
Hi there,

I attempted to reproduce your issue on an iPhone 12, iOS 18, Bitwarden (2024.9.2) with the same key, and was unable to do so. Consider reinstalling the Bitwarden app, restarting your device and testing again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
