### ISSUE TITLE
Error when syncing on mobile between PC and mobile (bitwarden.eu)

### ISSUE THREAD

**Issue by basketshoe** [bitwarden/mobile#3411]
### Production Build

- [x] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Go to 'settings'
2. Click on 'other'
3. Click on 'Sync now'

### Expected Result

Bitwarden should sync correctly

### Actual Result

ERROR MESSAGE: An error has occurred.
(Last sync on mobile is from 23/09/2024, on PC is today)

### Operating System

iOS

### Operating System Version

iOS 17.5.1

### Device

iPhone 11

### Build Version

2024.9.2 (1106)

**Comment by Adedamola-Aina** [comment]
Hello @basketshoe 

I am unable to reproduce this issue, We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.
Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
Thanks!
