### ISSUE TITLE
Cannot create Passkey on PayPal Mobile Android App through Bitwarden ("asset links" error)

### ISSUE THREAD

**Issue by raywdude** [bitwarden/mobile#3412]
### Production Build

- [X] I'm using the legacy Bitwarden app pubicly available in App Store / Play Store and I'm aware that Bitwarden Beta bugs should be reported in [bitwarden/android](https://github.com/bitwarden/android) or [bitwarden/ios](https://github.com/bitwarden/ios)

### Steps To Reproduce

1. Login to Bitwarden (from Play Store, not beta), enable Bitwarden as Passkey provider in the system
2. Login to PayPal app (from Play Store)
3. Go into PayPal profile settings and "Create Passkey"
4. Choose to create the passkey in Bitwarden

### Expected Result

The passkey is created successfully

### Actual Result

Bitwarden shows "Passkey operation failed because app not found in asset links" and the creation process fails

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy S24 Ultra (SM-S928U1)

### Build Version

2024.7.1 (11086)

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and my understanding this is a restriction that relates to the type of passkey PayPal is using, rather than an issue with Bitwarden - referring to [their article here](https://www.paypal.com/us/cshelp/article/what-is-a-passkey-and-how-do-i-use-it-to-log-in-to-my-paypal-account-help997), it states:

_On Android devices, you can use the face or fingerprint scan, PIN, or Pattern to unlock your device (depending on what device lock is set up on your device). You should be automatically directed to your PayPal home screen when completed._

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by raywdude** [comment]
Hmm...that doesn't seem right to me. If it's an issue with the passkey itself then I should not have been able to do the following, successfully:

1. Set up PayPal passkey on bitwarden through Chrome Android
2. Install the PayPal app on an iPhone
3. Login using the saved and synced passkey from the android phone into the PayPal app on iPhone


It works every time.

However if I try to login using the android PayPal app it doesn't work it gives the same error as when you try to create it with the Android app.

I can use the same passkey synced in bitwarden to login to PayPal web site in chrome on Android as well as iPhone app and through the site on Safari.

**Comment by HypedLama** [comment]
Same Problem on the mobile app. Works in the web though. Also works via Google passwords on Android.

I cannot choose a passkey provider different to my password manager...

**Comment by doitranch** [comment]
Also experiencing this, wish there was a way to check logs on something like this... It's like the package name is wrong or something in BW. I checked the name for PayPal and it's the same that's in BW (androidapp://com.paypal.android.p2pmobile).

**Comment by prediscover** [comment]
I also experience this error with Bitwarden and the Playstation App. Package name is correct

**Comment by HypedLama** [comment]
> Hi all.
> 
> There is an issue with the `assetlinks.json` file that PayPal is hosting. In short, they are missing the `relation` entries that are required to perform passkey operations. Unfortunately this is not something we can resolve on our end. For more details see my response on [#3419 (comment)](https://github.com/bitwarden/mobile/issues/3419#issuecomment-2576366443).

What's confusing me is that switching the passkey provider in the settings to Google passwords (and saving a passkey there) works for PayPal.
Doing the Same steps with Bitwarden give the asset link error.

Question is what is Google doing differently ?
Is android behaving differently for third party password managers ?

**Comment by TechnoSparks** [comment]
Proton Pass also able to add passkeys without this pesky error.

**Comment by lacrima08** [comment]
Same error too, here, with Android 14 freshly formatted (stock, rom , non rooted) , and bitwarden 2025.1.2

**Comment by kub04** [comment]
Same issue, Galaxy S25 Ultra Android 15, Bitwarden 2025.1.2, PayPal 8.78.1

**Comment by SaintPatrck** [comment]
Hi all,

I could have overlooked it in their source, but I  don't see any validation of digital asset links occurring in Proton Pass, which would explain why PayPal is working in their app. 

I did confirm that relaxing the requirement on `common.get_all_creds` resolves the issue in Bitwarden, which reinforces my theory that Proton Pass is not checking the digital asset links file and subsequently not validating the authenticity of the calling application.

I suggest reporting this to Proton Pass as it is a potential security risk. In theory, Proton Pass would respond to challenges from imposter applications because they are not checking the authenticity of the requesting application. It is clearly stated in the Android documentation that password managers are responsible for verifying the authenticity of a request and the owner has granted that application permission to handle user credentials.

I can't speak to why it works with Google Password Manager. I've opened an inquiry and will provide any updates that I receive.
