### ISSUE TITLE
"Never for this app" feature?

### ISSUE THREAD

**Issue by Vistaus** [bitwarden/mobile#352]
Every time I enable my hotspot, Bitwarden keeps asking me to save the password even though it's already saved. Could you maybe implement a "never for this app" option so that it stops asking me?

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
