### ISSUE TITLE
Android Bitwarden freezes 

### ISSUE THREAD

**Issue by mladiucitelj** [bitwarden/mobile#378]
On my Samsung Galaxy S8 and my Galaxy Tab A10 when I browse in my Chrome Mobile and want to fill in the form, I slide down and open the Bitwarden, but almost every time it freezes everything for a minute or two. Sometimes it crashes too.

It's really annoying and I'm experiencing this for almost a month now. Now I've decided to search for support or to report this issue here. 

Otherwise Bitwarden is just great!

**Comment by kspearrin** [comment]
I am guessing you are using the accessibility autofill service? Have you tried reinstalling to see if that helps? Also, how large is your vault?

**Comment by mladiucitelj** [comment]
> I am guessing you are using the accessibility autofill service?
Yes. Should I disable it?

> Have you tried reinstalling to see if that helps?
Not yet, but it's weird that it happens on two different devices for almost a month now.

> Also, how large is your vault?
Around 700 entries...


Also, it mostly happens when I try to open it when browsing a page. When I open Bitwarden like an app on my phone it opens normally.

**Comment by kspearrin** [comment]
Thanks for the info. We'll have to investigate further.

**Comment by mladiucitelj** [comment]
Hello,

I'm still experiencing this issue I've posted in the first post. Not much new to say.

**Comment by DougParker1992** [comment]
I've honestly noticed this with the Android version of Bitwarden as well. I've had the delay when opening Bitwarden via the accessibility service with the Samsung Galaxy Note 8 on Oreo for sure. I have also had the issue on my Google Pixel 3 XL running Android Pie.

This has been an issie for as long as I can remember. It is not a consistent delay, but it happens frequently enough that it is very annoying when it locks up.

I will say the lockup might be just before the fingerprint prompt opens up. @mladiucitelj do you have Fingerprint enabled on both?

I should try disabling the fingerprint for a day or two and see how that goes to help narrow the issue down.

I only have about 300 entries in Bitwarden. The hang doesn't seem to happen when opening Bitwarden normally. Just via the accessibility service. I am not sure if the issue happens using the autofill framework or not. Out of habit I use the accessibility service because the autofill framework doesn't pickup everything.

**Comment by mladiucitelj** [comment]
> I will say the lockup might be just before the fingerprint prompt opens up. @mladiucitelj do you have Fingerprint enabled on both?

No, I have fingerprint enabled on mobile, but not on my tablet.


> The hang doesn't seem to happen when opening Bitwarden normally. Just via the accessibility service.

Exactly. 



> I am not sure if the issue happens using the autofill framework or not. Out of habit I use the accessibility service because the autofill framework doesn't pickup everything.

Well, currently, I'm using both.

**Comment by mladiucitelj** [comment]
Not sure why, but I haven't seen this issue for a while now.

**Comment by rashidrupani** [comment]
Experiencing the same issue on my Oppo phone from the beginning. On my laptop it is working fine but on my android, it is always freezes when I use autofill service on my browser or even app freezes on splash screen and frequently getting crash

**Comment by calvez** [comment]
Why closed.
It's definitely an issue.
I experience the same on android

**Comment by douglasparker** [comment]
Simply closing issues with no explanation or a commit hash / PR reference isn't helpful for anyone.

A lot of us take the time to try and help the team make Bitwarden better.
