### ISSUE TITLE
Unable to share passwords to organizations from mobile.

### ISSUE THREAD

**Issue by viertaxa** [bitwarden/mobile#387]
I am unable to share existing, un-share existing, or create new shared logins from the iOS app.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by PrplHaz4** [comment]
@viertaxa here is the relevant feature request i think you're looking for - it's not unpopular but could use some votes...

https://community.bitwarden.com/t/manage-collection-associations-from-more-than-just-the-web-vault
