### ISSUE TITLE
Enhancement: Make it easier to favorite logins using the 3 dots menu

### ISSUE THREAD

**Issue by arunsathiya** [bitwarden/mobile#394]
### Current behaviour 

One has to edit the login and toggle the favorite option over there.

***

### Suggested behaviour 

It would be helpful if the 3 dots menu available next to the logins, on the primary view, has an option to favorite them.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by arunsathiya** [comment]
Thanks! I have gone ahead and voted for this request [here](https://community.bitwarden.com/t/additional-way-to-add-to-favorites/2298).
