### ISSUE TITLE
Allow search on autofill

### ISSUE THREAD

**Issue by a-m-s** [bitwarden/mobile#41]
When autofill fails to find a match (or if it finds the wrong match) then the only thing to do is tap X, find the right entry, and fill the form manually via the clipboard.

Please add an autofill search box so that I can fill arbitrary entries into apps and websites.

For apps, it would be helpful if there were a way to record the association for future.
For websites, a big red anti-phishing warning might be appropriate, but please make it possible.

**Comment by sreich** [comment]
I agree. I have lastpass set as a persistent notification for this very reason. Filling in certain credentials can't get detected very well, like wifi password.

LastPass in their auto fill also has a search button. It also can add that association for other people who use the app

**Comment by kspearrin** [comment]
We're working on a solution for this.

**Comment by kspearrin** [comment]
I've added some improvements to autofill that is now in beta to test:

1. Added two groups of logins in the autofill listing: matching logins and possible matching logins.
  - Matching logins are the results from the way the current version works (complete matches).
  - Possible matching logins are ones were the app tries to make a guess based on the reverse domain of the package name on an app. For example, `androidapp://com.google.plus` will match `https://google.com`. A warning alert is shown whenever you select a possible matching login for autofill since it is possible to exploit this method.
2. Added ability to search your full vault to select anything for the autofill.

Get the beta here: https://play.google.com/apps/testing/com.x8bit.bitwarden

Let me know any feedback and I'll plan on publishing this soon.

**Comment by a-m-s** [comment]
Excellent. This does exactly what I needed. Thanks for the quick fix. :+1: 

If I'm being picky, the "You are searching for an ...." message should persist. Right now it disappears around the same time as I switch tabs, which is disconcerting, but turned out not to be a problem. Also, for bonus points it should open at the vault tab with the search activated, but now I'm getting carried away. :-)

**Comment by kspearrin** [comment]
Available in next release.

**Comment by laserstrike** [comment]
Hi. Is this feature only available on android? I'm on iOS and when using Simplenote, for example, I tap on the keyhole icon and am taken to a screen that says There are no logins in your vault for this website. Tap to add one. Well, I actually already have a simplenote login, so that's one thing, but besides that there's no search function visible. Even when I delete my simplenote login and create another one when it says tap to add one -- I'm taken to the login creation window, where I input the necessary credentials, hit save & am taken back to the empty There are no logins window. Any idea? Didn't want to create a new issue, since I guess having the search function would resolve it.

**Comment by kspearrin** [comment]
@laserstrike there is no search on iOS. I just checked the simple note app and there is something weird going on with it. You are right, it's not finding a login there. Can you open a separate issue for that app and I will have a look?
