### ISSUE TITLE
Android: Auto fill dialog only shows entries with standard match detection

### ISSUE THREAD

**Issue by quthla** [bitwarden/mobile#432]
Entries with other match detection not shown. No issues with same entries on either iOS or browser.

**Comment by kspearrin** [comment]
Not enough information. Please explain the issue further.

**Comment by kspearrin** [comment]
Which autofill service are you using? Accessibility or Oreo/Pie autofill?

**Comment by quthla** [comment]
Pie autofill

**Comment by djboge** [comment]
I'm pretty sure I have this issue as well.

I have a bunch of logins for various subdomains of ".state.xx.us" i.e. mail or apps or payroll, etc. I have them all set to "begins with" match detection, because they all have separate logins.

When I visit any of them on Android Chrome, it says "no logins" if I tap the little box that comes up next to the login fields. If I tap out of that and go to the notification, it will show the login there.

**Comment by xcffl** [comment]
Setting match detection to Host also still has the same effect as Base Domain.

E.g. A Login entry with URI `www.example.com` matches website `abc.example.com`

**Comment by Loakii** [comment]
I have the same issue with Pie autofill.

Bitwarden version: 2.1.0 (8 Jul 2019) (beta)
Google Chrome version: 75.0.3770.101

For example: I have a password stored for https://example.com:8443 with **start with** detection. Bitwarden would fail to give an option to autofill the information as shown below

![2019-07-09 16 23 33](https://user-images.githubusercontent.com/47106497/60896539-d119be80-a266-11e9-90a2-377d3f064bc8.jpg)

If I set the detection to **base domain** the autofill option works as shown below.

![2019-07-09 16 24 06](https://user-images.githubusercontent.com/47106497/60896617-f1497d80-a266-11e9-8342-bfc1fb9dd719.jpg)

**Comment by kspearrin** [comment]
The reason this happens is that the autofill APIs were only returning the "WebDomain" property of the page, which is just "domain.com" and does not include the scheme (http vs https). Therefore, when no scheme is present, we assume `http://`. If your "starts with" match detection is on a URI such as http**s**://domain (s), then we do not have a match.

However, in Android Pie (API 28), they added an additional property to get the scheme as well (called WebScheme). We can now accurately detect the scheme of the page. I have added a fix. You can test the latest dev build with this fix here if you like: https://ci.appveyor.com/project/bitwarden/mobile/build/job/4ai23fw0a3frhsrm/artifacts

Devices on < Pie (28) will still default to `http://` scheme and match detection against https:// stored URIs will not work.

**Comment by kspearrin** [comment]
Fix is also going out to play store beta, build 2019.

**Comment by Loakii** [comment]
I'm either doing something wrong or it's still not working on the dev build.

URI is saved with https://

Current version: 2.1.0 (2020)

**Comment by kspearrin** [comment]
@Loakii Are you using Android P? I was able to reproduce the issue before, but seems to work in my tests now.

1. URI: starts with "https://gith"
2. Visit github sign in page
3. Login is properly shown

**Comment by Loakii** [comment]
@kspearrin Ah yes! I guess it's the ports at the end that screw it up in my case.
I assume there's no way of making that work for now?

I have one domain with multiple webapps running on different ports and they all use different credentials.

**Comment by kspearrin** [comment]
Unfortunately, I do not think that android autofill APIs will give me the ports. Only the domain and scheme.

**Comment by Loakii** [comment]
I can work with base domains it's not a problem at all.
My purpose of using it was to add an extra filter.

The start with works correctly on on pie with partial domains now. Cheers!

**Comment by jeffgoh** [comment]
Not sure how to make this work, but even when I set default to match by host rather than domain, the default for Android auto fill remains match by domain. Is this an Android Api problem? Or something @kspearrin can fix?

**Comment by jffernandez** [comment]
Hi, sorry for comenting in a closed issue, but, I have same problem as @jeffgoh a couple of days ago. The filter for entries does not take in account the default match type from the settings and is filtering allways by domain.
I think that it's caused because the setting is not applyed on filter.
Here is readed:
https://github.com/bitwarden/mobile/blob/b2abcda1117044ce6b7a30fc652bb3781b924ee9/src/Core/Services/CipherService.cs#L319-L323
But a few lines after, is ignored:
https://github.com/bitwarden/mobile/blob/b2abcda1117044ce6b7a30fc652bb3781b924ee9/src/Core/Services/CipherService.cs#L345-L349

I submitted a PR with the modification I made and is working for me on the Android emulator: https://github.com/bitwarden/mobile/pull/830
