### ISSUE TITLE
Cannot edit long notes on iOS after latest mobile update. 

### ISSUE THREAD

**Issue by dustindauncey** [bitwarden/mobile#456]
Since the latest 1.22.0 version of Bitwarden on iOS, I cannot edit lengthy notes sections as it refuses to scroll the note when in edit mode. Trying to scroll the note field while editing simply drags around the whole edit page rather than just the note field itself. I do not believe I had this issue in prior versions, it seems like a new bug just recently introduced in 1.22.0. I am running the latest iOS 12.1.3.

**Comment by MarcusE1W** [comment]
Same here. 
I think I have have noticed that for a while, so I am not sure if it is a new bug.

My note has about about 35 lines. In read mode they are all shown correctly.
When attempting to edit the note 19 line are visible, but cannot be scrolled down, so that the lower part of the note is not accessible.

This is on an iPad iOS 12.1.4
Bitwarden app v1.22.0 (46)

**Comment by bradmanz** [comment]
Also able to duplicate. Note shows in the view, but when editing, the user cannot move the cursor or scroll below the bottom of the text box. I’ve found the only way to work around this is to do a “select all”, cut the text, edit elsewhere, then paste it back.

**Comment by kspearrin** [comment]
Should be fixed in v2.0. Notes field will now auto-grow with its content.

**Comment by revlisoft** [comment]
I was able to duplicate this. Work around is to put a carriage return and rest of field comes back
