### ISSUE TITLE
Suggets

### ISSUE THREAD

**Issue by unknowtech** [bitwarden/mobile#459]
Very good but litle problem

- apps contain tracking google (firebase) deleted please or use others open source trackers 

- night / darkness theme 

i think take premiun account but for the momnent no because trackers google

**Comment by kspearrin** [comment]
We use firebase for push notifications to the app. It’s not used for tracking anything.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by unknowtech** [comment]
exists others system for notification 

websockets

**Comment by unknowtech** [comment]
telegram , tutanota fedilab use websockets , for push notification
