### ISSUE TITLE
New subdomain login updates different subdomain's login

### ISSUE THREAD

**Issue by Deebster** [bitwarden/mobile#479]
I have two logins for the domain thetvdb.com: 
* #1 website:www.thetvdb.com
* #2 website:forums.thetvdb.com (same username, different password)

The forums.thetvdb.com login was my most recently used.

I registered under gitlab.thetvdb.com (again the same username and different password) and expected to be prompted to create a new login item since the subdomain didn't match either existing. Instead, I was asked if I wanted to update - worse, when I clicked yes (didn't read properly), my password for forums.thetvdb.com was updated.

I can see the logic for www.thetvdb.com being updated (treating www as the default), but updating a sibling subdomain is very unexpected and is surely a bug.

(nb: the password history function was very helpful here, cheers)

Firefox 66.0.2 (64-bit)
BitWarden 1.39.3
Windows 10 Home

**Comment by kspearrin** [comment]
By default, URLs are treated the same across subdomains. If you have two items with the same username for the same URL, they would be considered the same for a password update. To distinguish the two, you can change them to "Host" URL match detection.

**Comment by Deebster** [comment]
As a software developer this answer is enlightening, but as a user it is unsatisfying.

Given that there were multiple matching logins, the software should at least ask which of the two to update. How _was_ the record to update decided? I assume the most recently used.

In fact, in the case of multiple logins, the choice should be between add and update existing (this being a dropdown or triggering a modal).

**Comment by kspearrin** [comment]
When you log into a website, we lookup all logins associated with the current URL. In this case there were two. We then grab the first login that matches the username you used to log in with. In this case it could have been either one since I assume you have the same username value for them both. It then checks if the password you used to log in is different than the one stored. If so, it prompts you to update it. Since you use the same username for both of these logins, you should further distinguish them by URL match detection to prevent the issue.
