### ISSUE TITLE
Allow selecting Notes field in 'view login' mode.

### ISSUE THREAD

**Issue by sreich** [bitwarden/mobile#50]
Currently the Notes field in a login behaves oddly, at least on Android. Touching the text field highlights the field but won't let you select any text. For that you have to go to edit mode. It should allow you to select text but in a read only mode.

**Comment by kspearrin** [comment]
It uses a standard Xamarin Label so I'm not sure why you cant select it for copy. Will have to investigate.

**Comment by kspearrin** [comment]
I added a copy when tapped function in the next release. Is this sufficient?

https://github.com/bitwarden/mobile/commit/952935de23678cb65c571cfb913cf2edd5682526

**Comment by sreich** [comment]
It won't allow me to copy individual words, would it?

In my password manager I have security questions(randomized, because questions are insecure) and other important stuff, as well as previous passwords, stored in the notes, these things are often complex or randomized, etc so I'd need to be able to copy them individually.

**Comment by kspearrin** [comment]
I am a little leery to enable the TextIsSelectable option mentioned above that @Shan11812 mentioned. I'll have to test it out more.

**Comment by sreich** [comment]
I hear you, but I know that lastpass handles this just fine with the behavior I described. Admittedly I should use custom fields, but those aren't trivial to add in any password manager on a per site basis and they seem to be inflexible in general.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
