### ISSUE TITLE
Splash screen doesn't follow app theme

### ISSUE THREAD

**Issue by killoid** [bitwarden/mobile#528]
hello,
in my opinion, the splash screen should follow the app's current theme. i am using the latest beta from google play & the splash screen is always light themed no matter what theme i use.

**Comment by kspearrin** [comment]
As far as I know, it is not possible to set a gene at runtime for the splash screen.

**Comment by killoid** [comment]
ahh! my bad. i guess i will close the issue then. thank you!

**Comment by franga2000** [comment]
If I may resurrect an old issue, I believe there is at least a way to have it follow the _system_ theme.  
Since most people will probably want to set their app to match their system theme (so Light->Light and Dark->Dark/Black/Nord), would you consider doing that instead? 

There's supposedly an option to target different versions of assets based on the system theme (_according to a friend - I have zero Xamarin experience_) and looking around the web, I stumbled onto [this article](https://codetraveler.io/2019/10/11/creating-a-dark-mode-splash-screen/) that does exactly that.
