### ISSUE TITLE
Allow saving new credentials while offline.

### ISSUE THREAD

**Issue by CrimsonFinale** [bitwarden/mobile#541]
I self-host my bitwarden server in a private NAT(For security reasons). The downside of this being when you are away from the private network, you cannot create new credentials or save any data in the bitwarden vault from your client device.

1) Please allow writing data to the vault while being offline. 
2) Option to sync it later with the server when online.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by ohadschn** [comment]
Requested here: https://community.bitwarden.com/t/offline-management-of-writeable-vault-items/107

**Comment by DUOLabs333** [comment]
Where is the code that deals with editing, then syncing after (I'm assuming that the changes are saved temporarily on the device, then synced immediately. Or are the changes streamed to the server in real-time?) This affects me too, and I want to see if I can work on this (if Bitwarden allows outside contributors, that is).
