### ISSUE TITLE
Slight issue on Portuguese Translation

### ISSUE THREAD

**Issue by andre-paulo98** [bitwarden/mobile#584]
Every word in Portuguese has a gender, either female/male.
When a password is copied, the toast says: "_Palavra-passe foi copiado_".
And on AppResources.pt-PT.resx it has:
```
  <data name="ValueHasBeenCopied" xml:space="preserve">
    <value>{0} foi copiado.</value>
    <comment>Confirmation message after suceessfully copying a value to the clipboard.</comment>
  </data>
```

This is not right. "Palavra-passe" in Portuguese is "female" so it should be instead "_Palavra-passe foi copiada_" (difference is the last letter)

Now you can't change ValueHasBeenCopied to the "female" version because that would break other strings.
From what I could tell from the usage of that string, only the Password needs to be changed.

**Comment by kspearrin** [comment]
Hi,
Please see the following for contributing to translations. Thanks!

https://github.com/bitwarden/mobile/blob/master/CONTRIBUTING.md

**Comment by andre-paulo98** [comment]
This issue can't be fixed just by changing the one line on Crowdin because it's depending on one specific word.

**Comment by andre-paulo98** [comment]
This issue can't be fixed just by changing the one line on Crowdin because it's depending on one specific word.

**Comment by Crocmagnon** [comment]
I guess this issue is not relevant to Crowdin and maybe should be reopened. As stated, you can't change all `ValueHasBeenCopied` because in various languages (Portuguese and French being two examples) the translation would vary depending on the `{0}` parameter.

Or, another solution would be to use something more invariant, like `{0} foi copiado/a`. Would that seem acceptable @andre-paulo98 ? If yes, please suggest the modification on Crowdin 🙂

**Comment by andre-paulo98** [comment]
I guess that could work yes, while not perfect.
I'll make an account on Crowdin and suggest it.

**Comment by Crocmagnon** [comment]
I applied a similar fix in French, thanks for bringing this to our attention 🙂
