### ISSUE TITLE
Two Page sign in not working

### ISSUE THREAD

**Issue by VijayGawade** [bitwarden/mobile#598]
when we try to login in amazon.in, it will first asked for username(mail) then after click next it will asked for password.In this case bitwarden not prompt for auto filling. This app prompt after focusing on password page(2-page).Issuse is at 1st page we need to manually type usrname.

I have changed some setting in app:
Setting->Option : 
    change to "persist Notification"

after this auto-fill notification prompt was there ,but after selecting it is unable to set username as shoen in below screenshot.

![Screenshot_20190910-102604](https://user-images.githubusercontent.com/49547658/64585274-bf16e200-d3b5-11e9-8c21-05abeb2bcbf6.jpg)
![Screenshot_20190910-102615](https://user-images.githubusercontent.com/49547658/64585275-bf16e200-d3b5-11e9-87f5-fabfc91d7c1e.jpg)

try to fixed for 2 page login.

**Comment by kspearrin** [comment]
Autofilling usernames only will not be possible on Android. I don't have any way of detecting a username field if it is not accompanied by a password field.

**Comment by mindrunner** [comment]
What is the difference between a `username` field and a `password` field from the perspective of an auto-fill service?

**Comment by kspearrin** [comment]
@mindrunner A password field can be detected because there is a type that labels it as such. Based on this, we assume that the username field is field just before the password field. If a password field is not present, I cannot make that assumption and the username field becomes indistinguishable.

**Comment by mindrunner** [comment]
Often websites `id` their fields with `user` `username` `pass` `password`, and maybe some others. I think with that, you would be able to detect 80% of the pages. Since you also fill `custom fields` on websites, I assumed, that the heuristic in bitwarden is more than only relying on the type of the field, but also identifying fields by their `id`.

**Comment by kspearrin** [comment]
@mindrunner We do not have access to that data with accessibility services. This is also why custom fields are not supported with accessibility autofill.

**Comment by mindrunner** [comment]
Ah, now I got it. :) thanks for elaboration.

**Comment by tweekmonster** [comment]
@kspearrin I did what @VijayGawade did and enabled the persistent notification.  But, when I selected my account to fill in the username field, it was my password that got filled in.  Going by what you said above, I'm assuming that the username is filled, but the password overwrites it since it's being forced to fill the fields?  Couldn't this be resolved by simply not allowing passwords to go into non-password fields or at least not attempt to fill two fields when there's only one present?

It would be nice to have an option to have the autofill dropdown on any field that could reasonably be a login form.  What I would think is reasonable assumptions:

- The obvious input + password fields
- A lone non-password input
  - If you can distinguish that it's an `email` field, that should be a strong enough indication that this is a multi-page login
- A lone password input

In any case, if Bitwarden can't determine if a field is fillable, couldn't the user be given the option to make that final decision?

**Comment by mindrunner** [comment]
I feel like it could be quite helpful if I (as a user) can choose a specific field and tell bitwarden what to fill in there. (e.g. rightclick into field -> opens menu -> bitwarden -> <entry> -> <user|password|custom>)

This could also help with other issues I have with autofill (e.g. logins with multiple fields and/or having lots of different credentials for the same page/domain)

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
