### ISSUE TITLE
F-Droid Support

### ISSUE THREAD

**Issue by cwmke** [bitwarden/mobile#6]
Any chance of adding this to [F-droid](https://f-droid.org/)?

**Comment by mpeter50** [comment]
@shuvashish76 @RokeJulianLockhart it seems there is still no issue for it, and indeed the app is unreasonably large. The current latest version (2024.11.3) is 67,8 MB, which will consume storage on your phone twice, possibly more (because often both the APK and its extracted version is kept by the system).
However it seems it is no longer possible to open an issue for a feature request here, because the accepted issue templates do not allow that.

Do you (or anyone else reading this) agree that a request for per-ABI builds should be considered a bug report, when the reasoning for it is to reduce the app size?
I assume there are a few such people even among those who receives notification for this issue.

If I receive such reactions, I may open a bugreport issue for it. The reactions will be the proof that people other than me consider this worthy of a bug report.
Best to keep it unambigous by only using the thumbs up and down symbols.
