### ISSUE TITLE
iOS main app and app extension don't share unlock state

### ISSUE THREAD

**Issue by danielresnick** [bitwarden/mobile#603]
It seems that the main app and the autofill app extension don't share unlock state which results in frequently needing to re-enter the master password even within the auto lock time limits. 

This is WAI to avoid writing the master password (or some derived data) to disk?  If so perhaps we could use CFNotificationCenter to share state if both the main app and the app extension happen to be alive at the same time.

**Comment by kspearrin** [comment]
The main app and app extensions do not share memory space. An unlocked vault holds the encryption key in memory. I do not know of any way this could work.

**Comment by danielresnick** [comment]
https://www.atomicbird.com/blog/sharing-with-app-extensions gives a nice overview of what's possible. You could share the encryption key via CFNotificationCenterGetDarwinNotifyCenter in either direction (from extension to app or vice-versa) and avoid writing anything to disk.

**Comment by danielresnick** [comment]
Actually that might be problematic since AFAICT there isn't any way to lock down darwin notifications to your app group only. I wonder if it's possible to share a file descriptor that points at a memory backed file which is locked down to the bitwarden app group only. Will investigate further.

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

Here's a link to the existing feature request on our forums:
https://community.bitwarden.com/t/login-to-browser-extensions-when-logging-into-desktop-app-and-vice-versa/1635

This issue will now be closed. Thanks!
