### ISSUE TITLE
[Feature Request] Ability to Save Password Database on Own Cloud Storage

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#61]
Giving the ability to save password Database on users own cloud storage like Drive, Dropbox , onedrive etc will be a good feature for a open source project like this .

Refer : Keepass2android & Enpass

**Comment by Primokorn** [comment]
Drive and Onedrive for a better privacy?
Our files are already stored on Microsoft's server so I see no advantage to use Onedrive.
Google tries to read every single byte of your files so how could it be an advantage for our privacy?

Anyway data are encrypted before being sent to the server so I don't understand how this could improve the privacy.

**Comment by jerryn70** [comment]
I thought saving database on our cloud is safe. Thanks for correcting me

**Comment by Primokorn** [comment]
@jerryn70 Of course it's safe but Drive, Dropbox, Onedrive... is not your cloud. It's the computer of a big company ;)
I just wanted to point out that nobody can read the credentials without the master data (+ 2FA) so I don't think the place where it's stored doesn't really matter.
The implementation of the security features is more important. That's why being open source is one of the main advantages of bitwarden.

**Comment by jerryn70** [comment]
@Primokorn Then there is no need if this. But i will keep this issue open because some users suggested this same request on xda . So we will wait for the reply from developer whether he is interested in this feature or not.

**Comment by kspearrin** [comment]
@jerryn70 We currently have no plans on implementing other methods of storage such as Google Drive. For those interested in hosting their own data, there are plans in the distant future to document a path for self-hosting the bitwarden API/database yourself, though this would require that you run your own server. This will be geared towards our enterprise offerings to businesses, however, a personal user could also do the same if they wish.
