### ISSUE TITLE
[Feature Request] Keyboard integration for entering user credentials

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#62]
Adding a keyboard feature like keepass2android will be a good move. The one benefits of this feature is security and the other is , we all know that auto fill wont work on some apps, example UC browser. If we have a keyboard feature we can switch to that keyboard and get user credentials. 
I have tested the keyboard method of keepass2android with UC browser and got worked so that I'm requesting this for our bitwarden.

Refer : keepass2android

**Comment by kspearrin** [comment]
This will likely not be necessary anymore once we integrate with Android O autofill APIs.

**Comment by Livven** [comment]
Any chance this could still be considered, even with Oreo autofill implemented? There are plenty of devices that will never get Oreo, and probably not all apps will (reliably) support it either. A keyboard is guaranteed to work everywhere so it can be used as a fallback while being more secure than the clipboard.

**Comment by ocrete** [comment]
Also even with my Oreo enabled Pixel, the autofill feature doesn't work in all apps. In particular those that use a WebView for authentication seem to be broken. Especially that gboard doesn't even allow pasting into those password fields.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by isleshocky77** [comment]
With all the issues with chrome autofill this seems more relevant than ever. I'm sick of the only password manager option on the gboard keyboard being Google's.

**Comment by ionsquare** [comment]
@isleshocky77 [passwdsafe](https://sourceforge.net/p/passwdsafe/wiki/Home/) has a keyboard for entering passwords directly.
