### ISSUE TITLE
[Feature Request] Ability to Add/Edit Credentials when no Internet Connection

### ISSUE THREAD

**Issue by jerryn70** [bitwarden/mobile#63]
Add Ability to Add and Edit Credentials when no Internet Connection.  Because of this we are not able to add or edit data when no Internet Connection. Maybe in developed countries all have internet on their phones but coming towards developing countries like india not everyone have internet  everyday on their phone.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/offline-management-of-writeable-vault-items/107

This issue will now be closed. Thanks!
