### ISSUE TITLE
Text colour issue on iOS password keyboard filling activation screen

### ISSUE THREAD

**Issue by ntimo** [bitwarden/mobile#650]
Hello,
the text on the Screen when you activate the password filling via the keyboard on iOS is a bit too dark is looks kind of strange.

![image](https://user-images.githubusercontent.com/6145026/68965688-b3440380-07dc-11ea-86d3-8d6565444d65.jpg)

**Comment by tamet83** [comment]
I have the same problem on the search bar, can’t what I’m typing.

**Comment by PTRFRLL** [comment]
I believe this is happening because [this line is returning false when the iOS system setting is in light mode but the app is using a dark theme](https://github.com/bitwarden/mobile/blob/master/src/iOS.Core/Services/DeviceActionService.cs#L396). If you toggle iOS into dark mode, the text in the search box becomes white as expected.

**Comment by sleeping10** [comment]
> I believe this is happening because [this line is returning false when the iOS system setting is in light mode but the app is using a dark theme](https://github.com/bitwarden/mobile/blob/master/src/iOS.Core/Services/DeviceActionService.cs#L396). If you toggle iOS into dark mode, the text in the search box becomes white as expected.

Not anymore on iOS 14 you can't see anything ![image](https://user-images.githubusercontent.com/37278143/93711562-aa843280-fb4f-11ea-827c-0450feb1f2ae.png)
