### ISSUE TITLE
buttons copy login and copy password should be in result list row, not in an overflow menu

### ISSUE THREAD

**Issue by letroll** [bitwarden/mobile#691]
Buttons copy login and copy password should be in result list row, not in an overflow menu.

There are enought space on 2020 screen

**Comment by ShirokaiLon** [comment]
It should be responsive, displaying or hiding the buttons depending on how much space is available. 

I wouldn't want it when holding my phone vertically, it'd feel too cluttered (Pixel 3 XL). But it'd make sense on a tablet or in horizontal orientation.

**Comment by letroll** [comment]
+1 for the responsive part and there is priority like in toolbar I think:
1 overflow menu always present
2 password if room
3 login if room

I'm newbie on xamarin dev, but I will try to help on this part

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
