### ISSUE TITLE
SSL error in Android 4.4.4

### ISSUE THREAD

**Issue by kauron** [bitwarden/mobile#701]
I have an SSL error on Android 4.4.4, which didn't occur in the app version 2.2.6.

## Versions

* OS: Android 4.4.4
* App: 2.2.8 installed from FDroid (Official Bitwarden FDroid repo)

## Repro steps

The app hangs if asked to explicitly sync, and when logging in, the following error occurs

```
Exception message: Couldn't bind to method 'GetGetDefaultCipherSuitesHandler'.
```

Then, if I click "Log In" again, the following error is shown (once every button click).

```
Exception message: Native method not found:
xamarin.android.net.OldAndroidSSLSocketFactory.n_createSocket:(Ljava/net/Socket;Ljava/lang/String;lZ)Ljava/net/Socket;
```

**Comment by ChrisLane** [comment]
The problem is discussed on the Xamarin repo with various solutions: https://github.com/xamarin/xamarin-android/issues/2993

**Comment by kspearrin** [comment]
I added a possible for mentioned in that issue linked by @ChrisLane . Skipping linking on `Xamarin.Android.Net.OldAndroidSSLSocketFactory`. It will go out in the next beta on the play store.

**Comment by mqus** [comment]
I still have the same problem and have v2.3.1 installed now (also via fdroid, not play store). I get the same error messages. 

If I log in with an earlier version (don't know which exactly right now, but it works there) and upgrade to the current version, I can unlock the vault but bitwarden crashes on the next attempted sync, which is often within one minute of starting the app.

**Comment by bcronce** [comment]
Just have to fyi that Android 4.4.x Kitkat was EOL'd 3 years ago and has not gotten security patches in forever.

**Comment by mqus** [comment]
So I should throw away my perfectly usable phone because the vendor couldn't be bothered to release updates? Fyi, android 4.4 supports all tls standards which are considered "not broken", which is really the only important security-relevant feature for this app. 

More importantly, bitwarden still supports android 4.4 (i can install it), so it should be expected that issues from this version arise. I'm definitely not advocating for this but if bitwarden wants to drop Support for android 4.4, then I would understand it.

But anyway this is not the right place to discuss this.

**Comment by kspearrin** [comment]
For this and other compatibility reasons with newer versions of xamarin, Android 4.4 support has been dropped in the next Bitwarden release.

**Comment by mqus** [comment]
:cry: But I can totally understand it.
