### ISSUE TITLE
Android problem with "TOPT"

### ISSUE THREAD

**Issue by sleeping10** [bitwarden/mobile#710]
The feature that automatically copies the TOPT code on the clipboard don't work except when you go to settings and change "lock option" to immediately or kill the app. Don't know if this is a android bug only or also on iOS.

I'm currently running Android 10

**Comment by kspearrin** [comment]
Which autofill feature are you using? Autofill service or accessibility service?

**Comment by sleeping10** [comment]
Both

**Comment by Bluetexon** [comment]
The bug regarding the clipboard is caused by Android 10s restricted clipboard permissions. An app only has clipboard access, if it has been used some seconds ago. That's why the TOTP copy works, when you have to open the app before autofilling.
But I think there is a way to get access. Tasker for example always has clipboard access due to a workaround.

**Comment by xcffl** [comment]
Actually Android's Autofill framework already allows this action. We only need to detect weather the form is for TOTP code.

**Comment by sleeping10** [comment]
Any update ?

**Comment by sleeping10** [comment]
Fixed #851
