### ISSUE TITLE
Iphone 5 support

### ISSUE THREAD

**Issue by iamfilipc** [bitwarden/mobile#72]
Please add support for iPhone 5 to iOS app.

**Comment by kspearrin** [comment]
This is not possible at the moment due to the fact that adding 32bit architectures to the iOS app balloons the size of the app to 120mb+. This is really a Xamarin problem. There is talk that the next version of Xamarin.iOS will make some optimizations to app size, so we can consider it again then.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
