### ISSUE TITLE
Apple Watch app

### ISSUE THREAD

**Issue by midi** [bitwarden/mobile#76]
Would love if you could add an Apple Watch app, like 1Password has.
My use case, having access to card PINs from cards I can't set a custom PIN.
And also for two factor codes, like for work accounts I need every day.

For reference: https://blog.agilebits.com/2015/04/24/1password-for-apple-watch-putting-security-within-arms-reach/

**Comment by kspearrin** [comment]
Should be doable, but this will probably be pretty low priority until some other things get out of the way.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
