### ISSUE TITLE
Disable Google Analytics Setting

### ISSUE THREAD

**Issue by kspearrin** [bitwarden/mobile#8]
We use google analytics to to better learn how the app is being used by users so that improvements can be made. Some users to not want to be tracked in this way. Add an option in settings to allow a user to opt-out of of google analytics.

**Comment by Akerele20** [comment]
Needed to opt out, you can download and install the add-on for any of  web browser. The Google Analytics opt-out add-on is designed to be compatible with Chrome, Internet Explorer 11, Safari, Firefox and Opera. In order to function, the opt-out add-on must be able to load and execute properly on your browser. For Internet Explorer, 3rd-party cookies must be enabled. Learn more about the opt-out and how to properly install the browser add-on here. I did try it and it  worked.

**Comment by lpummer** [comment]
The Google Analytics opt-out add-on doesn't work for the iOS app, does it?

**Comment by kspearrin** [comment]
No. The addon linked above is for desktop users, not mobile.

**Comment by keshto** [comment]
yes please to this.

**Comment by Shan11812** [comment]
Added a switch under Account in Settings, checkout 1f03555065a48e739edf67163a725d2dd90c4298
Need translations for other languages.

**Comment by kspearrin** [comment]
@Shan11812 Thanks! I lift you some feedback and you an PR it.
