### ISSUE TITLE
Oh Browser Support

### ISSUE THREAD

**Issue by miguelang611** [bitwarden/mobile#897]
## Describe the Bug
The Oh Browser, which is a Chrome fork isn't supported.

## Steps To Reproduce

Install and use Oh Browser

## Expected Result

To be able to use my passwords as with Edge or normal Chrome

## Actual Result

There are no results in your wallet for com.oh.bro

## Environment

- Device: Samsung Galaxy S10+
- Operating system: Android 10
- Build Version (go to "Settings" → "About" in the app): G975FXXS5CTD1
- Is this a Beta release? [Y/N] N

**Comment by Perfect875** [comment]
Same issue here with "OH Browser". Bitwarden does not detect any url in which I am browsing, it only detects "com.oh.bro" and therefore my stored passwords do not appear

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
