### ISSUE TITLE
Auto-Fill Problem with app on Android 10

### ISSUE THREAD

**Issue by Sn1cket** [bitwarden/mobile#970]
## Describe the Bug
I’m using the autofill service of Android 10 and would like to fill a PIN into my banking app.
The autofill pop-up doesn’t show up when bitwarden is selected as android autofill service.
When I use e.g. Keepass2Android in the autofill settings the pop-up does show up, so I my guess is that the problem is on the bitwarden side.

Banking app:
[https://play.google.com/store/apps/details?id=at.erstebank.securityapp](https://play.google.com/store/apps/details?id=at.erstebank.securityapp)

## Steps To Reproduce
These are the steps I can do to reproduce the behavior but I think the app needs to be activated for a bank account so I don't know if you can use this app at all.
1. Open banking app
2. Long press in the pin field
3. Select Autofill

## Expected Result
A pop-up where i can open bitwarden or select an entry for autofill.

## Actual Result
Nothing happens after selecting Autofill from the context menu.

## Environment

- Device: OnePlus 7
- Operating system: OxygenOS 10.0.5 (Android 10)
- Build Version: 2.4.2 (2501)
- Is this a Beta release? No

**Comment by hashhar** [comment]
I think this is specific to OnePlus and their Android 10 release since.

I can reproduce this but I wanted @Sn1cket to confirm if he means "Autofill Service" or "Autofill Accessibility Service".

For me, even after enabling the Accessibility Service, Bitwarden settings show Auto-fill Accessibility Service as "Disabled". What's peculiar is that opening Bitwarden and then switching back to the application sometimes allows the auto-fill popup to show.

**Comment by Sn1cket** [comment]
> 
> 
> I think this is specific to OnePlus and their Android 10 release since.
> 
> I can reproduce this but I wanted @Sn1cket to confirm if he means "Autofill Service" or "Autofill Accessibility Service".
> 
> For me, even after enabling the Accessibility Service, Bitwarden settings show Auto-fill Accessibility Service as "Disabled". What's peculiar is that opening Bitwarden and then switching back to the application sometimes allows the auto-fill popup to show.

I mean the "Autofill Service".

**Comment by MarcMogdanz** [comment]
I have the same issue on my OnePlus 5 since the latest update (Oxygen 10.0.0 and Android 10). If I try to click in the text field like 10 times and also restart Bitwarden a few times it will magically appear.

I'm also having the same issue as @hashhar is describing since the last update. The autofill accessibility service popup/notification bar does not appear since the last update. In the Bitwarden settings the service appears as "disabled" but if I open the accessibility settings (via the bitwarden app) on my phone it will list Bitwarden as "on".

**Comment by eliykat** [comment]
Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
