### ISSUE TITLE
Feature Request: Firefox Preview "Fenix" support

### ISSUE THREAD

**Issue by ensiform** [bitwarden/mobile#974]
Could you work with Mozilla to get Bitwarden added to the list of add-ons they allow in this version? It seems they are taking a minimal/curated approach to add-ons for now.

https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by tgreer-bw** [comment]
I have sent comms to Mozilla to see what the options are - awaiting a response.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
