### ISSUE TITLE
Feature Request: iOS Autofill only show Face ID/Touch ID animation only

### ISSUE THREAD

**Issue by wuxinli1025** [bitwarden/mobile#989]
https://www.youtube.com/watch?v=LrhMmNTmOno
From 2:12 to 2:13 in the above video, when auto-fill Vaults, would you be able to make Bitwarden not show the black Bitwarden app background (only show Apple's Face ID/Touch ID animation), but do require master password/PIN/Face ID/Touch ID when opening Bitwarden app itself?

**Comment by cscharf** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
